#  6.13 Lab: Data exploration

---

<a id="learning-objectives"></a>
## Learning Objectives
*After completing this lab, you will be able to:*

- Explore and interrogate different data sets using our pandas and Plotly skills.
- Interpret the findings to understand what the data tells us about the real world.

---

<a id="air-quality"></a>

# <font color='blue'> Air Quality APIs </font>

### Part A

In this section, we're requesting and analyzing air quality data from OpenWeather's API.

Take a few moments to glance at OpenWeather's API: https://openweathermap.org/api. Note that you'll need to create an account and generate a free API key. A free API key entitles you to 60 calls per minute and _one million_ calls per month.

Take a few moments to read through some of the information on OpenWeather's site (https://openweathermap.org) and figure out:

* What this organization and its data are all about
* Where this API gets its data from (and whether it's a reputable source)
* What kind of data is available in the API
    
Remember, the documentation tells us:

* What sort of data is available
* Whether it’s free to access
* How we can build a url to get the exact data we want

Spend some time exploring the documentation and familiarizing yourself with it, and then let's get started!

Let's start by importing the **requests** library, which we'll be using to make API requests.

#### **ABOUT OPENWEATHER**

OpenWeather is a global provider of weather and environmental data, offering a wide range of information through structured APIs that support applications, analytics, and research. Its services include real-time weather conditions, forecasts, historical climate data, and air quality information, making it suitable for both commercial and academic use. 

The data provided by OpenWeather is aggregated from multiple reputable sources, including ground-based weather stations, satellite systems, radar networks, and established global forecasting models such as the Global Forecast System (GFS) and the ECMWF model. These sources are widely recognized in the meteorological community, and the data is updated frequently—approximately every 10 minutes—ensuring timely and reliable information. 

Through its APIs, OpenWeather provides diverse datasets, including current and forecasted weather conditions, over 47 years of historical weather records, statistical climate data, weather alerts, and detailed air quality metrics such as the Air Quality Index (AQI) and pollutant concentrations (e.g., PM2.5, PM10, CO, NO₂, SO₂, O₃, and NH₃). 

Overall, OpenWeather serves as a comprehensive and credible platform for accessing global weather and environmental data in a format that is easy to integrate and analyze.

In [390]:
import requests

#Refresh Jupyter cache. Prevents use of old or previous imports / caches.
import importlib
import config

importlib.reload(config)

In [391]:
# Account Key is stored in a config file
from config import OPENWEATHER_API_KEY

The OpenWeather API is a little odd in that it accesses weather data via latitude and longitude coordinates - not by city name! Luckily, it does contain a few API endpoints that can **geocode** for you. (Geocoding is the act of taking a city name and getting lat/long coordinates and vice versa).

Let's query the current weather data for Chicago, IL. You can find the documentation for this [here](https://openweathermap.org/current#builtin), under "Built-in geocoding".

In [392]:
# Get the API result for WEATHER for Chicago here.

city='Chicago'
state='IL'
country='US'

#Unit of measurement: metric
units = 'metric'

url = f'https://api.openweathermap.org/data/2.5/weather?q={city},{state},{country}&appid={OPENWEATHER_API_KEY}&units={units}'

# Call the API
response = requests.get(url)

# Check API call status
response.raise_for_status()
print(f"API Call Status: {response.status_code}")

# Convert the response to JSON
chicago_weather = response.json()

# View the response
chicago_weather

API Call Status: 200

{'coord': {'lon': -87.65, 'lat': 41.85},
 'weather': [{'id': 801,
   'main': 'Clouds',
   'description': 'few clouds',
   'icon': '02n'}],
 'base': 'stations',
 'main': {'temp': 4.73,
  'feels_like': 4.73,
  'temp_min': 4.73,
  'temp_max': 4.73,
  'pressure': 1011,
  'humidity': 87,
  'sea_level': 1011,
  'grnd_level': 990},
 'visibility': 10000,
 'wind': {'speed': 0.8, 'deg': 32, 'gust': 0.64},
 'clouds': {'all': 22},
 'dt': 1778234274,
 'sys': {'country': 'US', 'sunrise': 1778236686, 'sunset': 1778288165},
 'timezone': -18000,
 'id': 4887398,
 'name': 'Chicago',
 'cod': 200}

Now, use your dictionary and list-indexing skills to access the **coord** and **main** keys in this result. Save these values as their own variables.

In [393]:
# Identify the keys
chicago_weather.keys()

dict_keys(['coord', 'weather', 'base', 'main', 'visibility', 'wind', 'clouds', 'dt', 'sys', 'timezone', 'id', 'name', 'cod'])

In [394]:
# Access coord key
longitude = chicago_weather['coord']['lon']
latitude = chicago_weather['coord']['lat']

print(f"📍 Chicago coordinates: Longitude: {longitude}, Latitude: {latitude}")

📍 Chicago coordinates: Longitude: -87.65, Latitude: 41.85

In [395]:
# Check the data
chicago_weather['coord']

{'lon': -87.65, 'lat': 41.85}

### <font color='green'>**Additional API Documentation**</font>

Units in API response: https://openweathermap.org/api/weather-data  

Default is standard. For this lab, I used units=metric.

Temperature: Celsius

Pressure, Sea level, Ground level: hPa

Humidity: %

Date Time: unix, UTC

In [397]:
# Access main key
temperature = chicago_weather['main']['temp']
feels_like = chicago_weather['main']['feels_like']
temp_min = chicago_weather['main']['temp_min']
temp_max = chicago_weather['main']['temp_max']

humidity = chicago_weather['main']['humidity']

pressure = chicago_weather['main']['pressure']
sea_level = chicago_weather['main']['sea_level']
ground_level = chicago_weather['main']['grnd_level']

print(f"""
🌤️ Current Weather Report — Chicago, IL

Temperature         : {temperature}°C
Feels Like          : {feels_like}°C
Temperature (Min)   : {temp_min}°C
Temperature (Max)   : {temp_max}°C
Humidity            : {humidity}%
Pressure            : {pressure}hPa
Sea Level           : {sea_level}hPa
Ground Level        : {ground_level}hPa
""")

🌤️ Current Weather Report — Chicago, IL

Temperature         : 4.73°C
Feels Like          : 4.73°C
Temperature (Min)   : 4.73°C
Temperature (Max)   : 4.73°C
Humidity            : 87%
Pressure            : 1011hPa
Sea Level           : 1011hPa
Ground Level        : 990hPa

In [398]:
#Check the data in the main dictionary

chicago_weather['main']

{'temp': 4.73,
 'feels_like': 4.73,
 'temp_min': 4.73,
 'temp_max': 4.73,
 'pressure': 1011,
 'humidity': 87,
 'sea_level': 1011,
 'grnd_level': 990}

Next, let's get the air quality data for Chicago. You can find the documentation for this endpoint [here](https://openweathermap.org/api/air-pollution). Notice that you'll need the coordinates from the previous step here.

In [399]:
# Get the AIR QUALITY result for Chicago

url = f'http://api.openweathermap.org/data/2.5/air_pollution?lat={latitude}&lon={longitude}&appid={OPENWEATHER_API_KEY}&units={units}'

# Call the API
air_quality_response = requests.get(url)

# Check API call status
air_quality_response.raise_for_status()
print(f"API Call Status: {air_quality_response.status_code}")

# Convert the response to JSON
chicago_air_quality = air_quality_response.json()

# View the response
chicago_air_quality

API Call Status: 200

{'coord': {'lon': -87.65, 'lat': 41.85},
 'list': [{'main': {'aqi': 2},
   'components': {'co': 154.69,
    'no': 0,
    'no2': 5.1,
    'o3': 60.46,
    'so2': 0.26,
    'pm2_5': 3.18,
    'pm10': 3.42,
    'nh3': 8.96},
   'dt': 1778234376}]}

In [400]:
#View Chicago's Air Quality

result=chicago_air_quality['list'][0]['main']['aqi']

if result == 1:
    air_quality = 'Good'
elif result == 2:
    air_quality = 'Fair'
elif result == 3:
    air_quality = 'Moderate'
elif result == 4:
    air_quality = 'Poor'
else:
    air_quality = 'Very Poor'

print(f"🌫️ Chicago's Air Quality is {air_quality} with Air Quality Index={chicago_air_quality['list'][0]['main']['aqi']}")

🌫️ Chicago's Air Quality is Fair with Air Quality Index=2


Now that you're familiar with using this API, we're going reveal **our end goal: To create a large dataset of weather data for various cities!** This will come in two parts:

1. Creating one row of a dataframe via our API output
1. Doing this many times for different cities and joining them

So let's do **Step 1** now: Create a large dictionary that contains all of the following for Chicago:

* City name (Chicago, duh)
* Lat/long coordinates
* All data contained in `main` from the weather output
* The air quality index (AQI) (contained in the air pollution data)
* All data contained in `components` from the air pollution output

This is a large, tricky problem. A good strategy is to take all the above data that are contained in dictionaries and [merge those dictionaries](https://stackoverflow.com/questions/38987/how-do-i-merge-two-dictionaries-in-a-single-expression-in-python). Then, take all the standalone data and add onto this dictionary.

In [401]:
# Create a dictionary for Chicago

chicago_data = {
    'city': chicago_weather['name'],
    
    'coordinates': {
        'lat': chicago_weather['coord']['lat'],
        'lon': chicago_weather['coord']['lon']
    },
    
    'weather_main': chicago_weather['main'],
    
    'air_quality': {
        'aqi': chicago_air_quality['list'][0]['main']['aqi'],
        'components': chicago_air_quality['list'][0]['components']
    }
}

# View the dictionary
chicago_data

{'city': 'Chicago',
 'coordinates': {'lat': 41.85, 'lon': -87.65},
 'weather_main': {'temp': 4.73,
  'feels_like': 4.73,
  'temp_min': 4.73,
  'temp_max': 4.73,
  'pressure': 1011,
  'humidity': 87,
  'sea_level': 1011,
  'grnd_level': 990},
 'air_quality': {'aqi': 2,
  'components': {'co': 154.69,
   'no': 0,
   'no2': 5.1,
   'o3': 60.46,
   'so2': 0.26,
   'pm2_5': 3.18,
   'pm10': 3.42,
   'nh3': 8.96}}}

Next, convert the dictionary you just made into a dataframe. It might help to set the index equal to the city name.

In [402]:
import pandas as pd

# Convert to DataFrame
chicago_df = pd.json_normalize(chicago_data)

# Note:
# json.normalize flattens nested fields like coordinates, weather_main, air_quality & components

# Set index as city name
chicago_df.index = [chicago_data['city']]

chicago_df

,city,coordinates.lat,coordinates.lon,weather_main.temp,weather_main.feels_like,weather_main.temp_min,weather_main.temp_max,weather_main.pressure,weather_main.humidity,weather_main.sea_level,weather_main.grnd_level,air_quality.aqi,air_quality.components.co,air_quality.components.no,air_quality.components.no2,air_quality.components.o3,air_quality.components.so2,air_quality.components.pm2_5,air_quality.components.pm10,air_quality.components.nh3
Chicago,Chicago,41.85,-87.65,4.73,4.73,4.73,4.73,1011,87,1011,990,2,154.69,0,5.10,60.46,0.26,3.18,3.42,8.96

In [403]:
# Simplify column names

chicago_df.columns = chicago_df.columns.str.replace('.', '_', regex=False)
chicago_df

# Note:
# regex=False treats the dot (.) character as a literal dot and not a regular expression that matches any character
# Without regex=False, it will replace every character with underscore ('_')

,city,coordinates_lat,coordinates_lon,weather_main_temp,weather_main_feels_like,weather_main_temp_min,weather_main_temp_max,weather_main_pressure,weather_main_humidity,weather_main_sea_level,weather_main_grnd_level,air_quality_aqi,air_quality_components_co,air_quality_components_no,air_quality_components_no2,air_quality_components_o3,air_quality_components_so2,air_quality_components_pm2_5,air_quality_components_pm10,air_quality_components_nh3
Chicago,Chicago,41.85,-87.65,4.73,4.73,4.73,4.73,1011,87,1011,990,2,154.69,0,5.10,60.46,0.26,3.18,3.42,8.96

Now for **Step 2: Doing this many times for different cities and joining them**

Let's create this dataframe for several cities. Write a loop through the below cities that creates a list of dictionaries in the same format as the one above. In the next step, you'll call merge this list to join all the rows into one large dataframe.

Your loop will involve two API calls: one for weather, one for air pollution.

In [405]:
# Create a list of dictionaries for the 10 cities

import requests

cities = [
    'Chicago,IL,US',
    'Boston,MA,US',
    'Austin,TX,US',
    'New York City,NY,US',
    'Atlanta,GA,US',
    'Los Angeles,CA,US',
    'Seattle,WA,US',
    'Minneapolis,MN,US',
    'Denver,CO,US',
    'Washington,DC,US'
]

city_data_list = []

for city in cities:
    
    #1. Weather API call
    weather_url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={OPENWEATHER_API_KEY}&units={units}"
    weather_response = requests.get(weather_url)
    weather_response.raise_for_status()
    weather_data = weather_response.json()
    
    #Get coordinates from weather response
    latitude = weather_data['coord']['lat']
    longitude = weather_data['coord']['lon']
    
    #2. Air Pollution API call
    air_url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={latitude}&lon={longitude}&appid={OPENWEATHER_API_KEY}&units=metric"
    air_response = requests.get(air_url)
    air_response.raise_for_status()
    air_data = air_response.json()
    
    #3. Create dictionary in same format as Chicago
    city_dict = {
        'city': weather_data['name'],
        
        'coordinates': {
            'lat': latitude,
            'lon': longitude
        },
        
        'weather_main': weather_data['main'],
        
        'air_quality': {
            'aqi': air_data['list'][0]['main']['aqi'],
            'components': air_data['list'][0]['components']
        }
    }
    
    # Add dictionary to the list
    city_data_list.append(city_dict)

# View the list
city_data_list

[{'city': 'Chicago',
  'coordinates': {'lat': 41.85, 'lon': -87.65},
  'weather_main': {'temp': 4.73,
   'feels_like': 4.73,
   'temp_min': 4.73,
   'temp_max': 4.73,
   'pressure': 1011,
   'humidity': 87,
   'sea_level': 1011,
   'grnd_level': 990},
  'air_quality': {'aqi': 2,
   'components': {'co': 154.69,
    'no': 0,
    'no2': 5.1,
    'o3': 60.46,
    'so2': 0.26,
    'pm2_5': 3.18,
    'pm10': 3.42,
    'nh3': 8.96}}},
 {'city': 'Boston',
  'coordinates': {'lat': 42.3584, 'lon': -71.0598},
  'weather_main': {'temp': 7.79,
   'feels_like': 6.61,
   'temp_min': 7.79,
   'temp_max': 7.79,
   'pressure': 1010,
   'humidity': 53,
   'sea_level': 1010,
   'grnd_level': 1005},
  'air_quality': {'aqi': 2,
   'components': {'co': 147.4,
    'no': 0,
    'no2': 4.18,
    'o3': 67.53,
    'so2': 0.7,
    'pm2_5': 1.21,
    'pm10': 1.66,
    'nh3': 0.65}}},
 {'city': 'Austin',
  'coordinates': {'lat': 30.2672, 'lon': -97.7431},
  'weather_main': {'temp': 17.24,
   'feels_like': 17.24,
   'temp_min': 17.24,
   'temp_max': 17.24,
   'pressure': 1013,
   'humidity': 85,
   'sea_level': 1013,
   'grnd_level': 989},
  'air_quality': {'aqi': 1,
   'components': {'co': 142.56,
    'no': 0,
    'no2': 3.49,
    'o3': 59.05,
    'so2': 1.05,
    'pm2_5': 5.7,
    'pm10': 6.42,
    'nh3': 1.68}}},
 {'city': 'New York',
  'coordinates': {'lat': 40.7143, 'lon': -74.006},
  'weather_main': {'temp': 20.28,
   'feels_like': 20.19,
   'temp_min': 20.28,
   'temp_max': 20.28,
   'pressure': 1012,
   'humidity': 70,
   'sea_level': 1012,
   'grnd_level': 1010},
  'air_quality': {'aqi': 2,
   'components': {'co': 183.68,
    'no': 0,
    'no2': 10.27,
    'o3': 61.02,
    'so2': 3.04,
    'pm2_5': 5.12,
    'pm10': 6.39,
    'nh3': 2.03}}},
 {'city': 'Atlanta',
  'coordinates': {'lat': 33.749, 'lon': -84.388},
  'weather_main': {'temp': 11.58,
   'feels_like': 10.86,
   'temp_min': 11.58,
   'temp_max': 11.58,
   'pressure': 1015,
   'humidity': 79,
   'sea_level': 1015,
   'grnd_level': 982},
  'air_quality': {'aqi': 1,
   'components': {'co': 135.32,
    'no': 0,
    'no2': 2.71,
    'o3': 54.31,
    'so2': 1.21,
    'pm2_5': 6.81,
    'pm10': 8.12,
    'nh3': 1.59}}},
 {'city': 'Los Angeles',
  'coordinates': {'lat': 34.0522, 'lon': -118.2437},
  'weather_main': {'temp': 16.88,
   'feels_like': 16.58,
   'temp_min': 16.88,
   'temp_max': 16.88,
   'pressure': 1015,
   'humidity': 75,
   'sea_level': 1015,
   'grnd_level': 996},
  'air_quality': {'aqi': 2,
   'components': {'co': 115.85,
    'no': 0,
    'no2': 0.49,
    'o3': 91.43,
    'so2': 0.84,
    'pm2_5': 4.95,
    'pm10': 18.46,
    'nh3': 0}}},
 {'city': 'Seattle',
  'coordinates': {'lat': 47.6062, 'lon': -122.3321},
  'weather_main': {'temp': 10.51,
   'feels_like': 9.84,
   'temp_min': 10.51,
   'temp_max': 10.51,
   'pressure': 1017,
   'humidity': 85,
   'sea_level': 1017,
   'grnd_level': 1007},
  'air_quality': {'aqi': 1,
   'components': {'co': 131.51,
    'no': 0.01,
    'no2': 4.31,
    'o3': 25.55,
    'so2': 0.28,
    'pm2_5': 2.15,
    'pm10': 5.51,
    'nh3': 0.86}}},
 {'city': 'Minneapolis',
  'coordinates': {'lat': 44.98, 'lon': -93.2638},
  'weather_main': {'temp': 5.47,
   'feels_like': 4.44,
   'temp_min': 5.47,
   'temp_max': 5.47,
   'pressure': 1008,
   'humidity': 51,
   'sea_level': 1008,
   'grnd_level': 977},
  'air_quality': {'aqi': 2,
   'components': {'co': 156.85,
    'no': 0,
    'no2': 4.38,
    'o3': 61.43,
    'so2': 0.06,
    'pm2_5': 2.59,
    'pm10': 3.14,
    'nh3': 16.71}}},
 {'city': 'Denver',
  'coordinates': {'lat': 39.7392, 'lon': -104.9847},
  'weather_main': {'temp': 9.29,
   'feels_like': 8.25,
   'temp_min': 9.29,
   'temp_max': 9.29,
   'pressure': 1013,
   'humidity': 74,
   'sea_level': 1013,
   'grnd_level': 834},
  'air_quality': {'aqi': 1,
   'components': {'co': 99.7,
    'no': 0,
    'no2': 1.8,
    'o3': 50.14,
    'so2': 0.01,
    'pm2_5': 1.02,
    'pm10': 1.22,
    'nh3': 2.15}}},
 {'city': 'Washington D.C.',
  'coordinates': {'lat': 38.8951, 'lon': -77.0364},
  'weather_main': {'temp': 7.69,
   'feels_like': 7.07,
   'temp_min': 7.69,
   'temp_max': 7.69,
   'pressure': 1014,
   'humidity': 75,
   'sea_level': 1014,
   'grnd_level': 1007},
  'air_quality': {'aqi': 1,
   'components': {'co': 136.79,
    'no': 0,
    'no2': 2.87,
    'o3': 49.03,
    'so2': 0.76,
    'pm2_5': 4.2,
    'pm10': 5.04,
    'nh3': 1.34}}}]

It's time to join all of these dictionaries to create one large dataframe of 10 rows of weather data! To do this, simply call `pd.DataFrame()` on your list of dictionaries and you should be good to go!

In [406]:
# Convert list into 1 dataframe

import pandas as pd

cities_df = pd.json_normalize(city_data_list)

# Clean column names
cities_df.columns = cities_df.columns.str.replace('.', '_', regex=False)

cities_df

,city,coordinates_lat,coordinates_lon,weather_main_temp,weather_main_feels_like,weather_main_temp_min,weather_main_temp_max,weather_main_pressure,weather_main_humidity,weather_main_sea_level,weather_main_grnd_level,air_quality_aqi,air_quality_components_co,air_quality_components_no,air_quality_components_no2,air_quality_components_o3,air_quality_components_so2,air_quality_components_pm2_5,air_quality_components_pm10,air_quality_components_nh3
0,Chicago,41.85,-87.65,4.73,4.73,4.73,4.73,1011,87,1011,990,2,154.69,0.00,5.10,60.46,0.26,3.18,3.42,8.96
1,Boston,42.36,-71.06,7.79,6.61,7.79,7.79,1010,53,1010,1005,2,147.40,0.00,4.18,67.53,0.70,1.21,1.66,0.65
2,Austin,30.27,-97.74,17.24,17.24,17.24,17.24,1013,85,1013,989,1,142.56,0.00,3.49,59.05,1.05,5.70,6.42,1.68
3,New York,40.71,-74.01,20.28,20.19,20.28,20.28,1012,70,1012,1010,2,183.68,0.00,10.27,61.02,3.04,5.12,6.39,2.03
4,Atlanta,33.75,-84.39,11.58,10.86,11.58,11.58,1015,79,1015,982,1,135.32,0.00,2.71,54.31,1.21,6.81,8.12,1.59
5,Los Angeles,34.05,-118.24,16.88,16.58,16.88,16.88,1015,75,1015,996,2,115.85,0.00,0.49,91.43,0.84,4.95,18.46,0.00
6,Seattle,47.61,-122.33,10.51,9.84,10.51,10.51,1017,85,1017,1007,1,131.51,0.01,4.31,25.55,0.28,2.15,5.51,0.86
7,Minneapolis,44.98,-93.26,5.47,4.44,5.47,5.47,1008,51,1008,977,2,156.85,0.00,4.38,61.43,0.06,2.59,3.14,16.71
8,Denver,39.74,-104.98,9.29,8.25,9.29,9.29,1013,74,1013,834,1,99.70,0.00,1.80,50.14,0.01,1.02,1.22,2.15
9,Washington D.C.,38.90,-77.04,7.69,7.07,7.69,7.69,1014,75,1014,1007,1,136.79,0.00,2.87,49.03,0.76,4.20,5.04,1.34

### Let's continue to use this API for forecasting and data viz!
Next, let's use the 5-day forecast endpoint to get some forecasts. Pick your city of choice and call up the 5-day forecast from [this endpoint](https://openweathermap.org/forecast5).

In [407]:
import requests
import pandas as pd

pd.options.display.float_format = '{:,.2f}'.format

# Chicago coordinates
latitude = chicago_weather['coord']['lat']
longitude = chicago_weather['coord']['lon']

# 5-day forecast endpoint
# Set the units to metric
forecast_url = (
    f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={OPENWEATHER_API_KEY}&units={units}"
)

# Call the API
forecast_response = requests.get(forecast_url)

# Check API call status
forecast_response.raise_for_status()
print(f"API Call Status: {forecast_response.status_code}")

# Convert response to JSON
chicago_forecast = forecast_response.json()

# View response
chicago_forecast

API Call Status: 200

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1778241600,
   'main': {'temp': 5.58,
    'feels_like': 5.58,
    'temp_min': 5.58,
    'temp_max': 7.27,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 990,
    'humidity': 87,
    'temp_kf': -1.69},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 26},
   'wind': {'speed': 0.62, 'deg': 107, 'gust': 0.85},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-08 12:00:00'},
  {'dt': 1778252400,
   'main': {'temp': 12.05,
    'feels_like': 10.9,
    'temp_min': 12.05,
    'temp_max': 15.71,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 990,
    'humidity': 61,
    'temp_kf': -3.66},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 29},
   'wind': {'speed': 2.17, 'deg': 136, 'gust': 2.15},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-08 15:00:00'},
  {'dt': 1778263200,
   'main': {'temp': 17.3,
    'feels_like': 16.5,
    'temp_min': 17.3,
    'temp_max': 17.3,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 988,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 66},
   'wind': {'speed': 1.91, 'deg': 165, 'gust': 3.29},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.17},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-08 18:00:00'},
  {'dt': 1778274000,
   'main': {'temp': 16.5,
    'feels_like': 16.03,
    'temp_min': 16.5,
    'temp_max': 16.5,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 986,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 3.37, 'deg': 181, 'gust': 3.58},
   'visibility': 10000,
   'pop': 0.8,
   'rain': {'3h': 1.02},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-08 21:00:00'},
  {'dt': 1778284800,
   'main': {'temp': 14.86,
    'feels_like': 14.23,
    'temp_min': 14.86,
    'temp_max': 14.86,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 986,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 85},
   'wind': {'speed': 3.39, 'deg': 217, 'gust': 4.9},
   'visibility': 10000,
   'pop': 0.68,
   'rain': {'3h': 0.1},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-09 00:00:00'},
  {'dt': 1778295600,
   'main': {'temp': 11.83,
    'feels_like': 11.21,
    'temp_min': 11.83,
    'temp_max': 11.83,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 985,
    'humidity': 82,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 48},
   'wind': {'speed': 2.39, 'deg': 180, 'gust': 4.2},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-09 03:00:00'},
  {'dt': 1778306400,
   'main': {'temp': 10.71,
    'feels_like': 10.06,
    'temp_min': 10.71,
    'temp_max': 10.71,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 984,
    'humidity': 85,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 34},
   'wind': {'speed': 3.18, 'deg': 201, 'gust': 7.73},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-09 06:00:00'},
  {'dt': 1778317200,
   'main': {'temp': 10.45,
    'feels_like': 9.8,
    'temp_min': 10.45,
    'temp_max': 10.45,
    'pressure': 1004,
    'sea_level': 1004,
    'grnd_level': 983,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 14},
   'wind': {'speed': 3.67, 'deg': 217, 'gust': 10.58},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-09 09:00:00'},
  {'dt': 1778328000,
   'main': {'temp': 11.74,
    'feels_like': 11.14,
    'temp_min': 11.74,
    'temp_max': 11.74,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 983,
    'humidity': 83,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 47},
   'wind': {'speed': 4.77, 'deg': 223, 'gust': 13.41},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.2},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-09 12:00:00'},
  {'dt': 1778338800,
   'main': {'temp': 16.93,
    'feels_like': 16.19,
    'temp_min': 16.93,
    'temp_max': 16.93,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 984,
    'humidity': 58,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 29},
   'wind': {'speed': 4.99, 'deg': 252, 'gust': 7.72},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-09 15:00:00'},
  {'dt': 1778349600,
   'main': {'temp': 20.45,
    'feels_like': 19.44,
    'temp_min': 20.45,
    'temp_max': 20.45,
    'pressure': 1005,
    'sea_level': 1005,
    'grnd_level': 984,
    'humidity': 34,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 65},
   'wind': {'speed': 4.7, 'deg': 293, 'gust': 11.28},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-09 18:00:00'},
  {'dt': 1778360400,
   'main': {'temp': 16.69,
    'feels_like': 15.72,
    'temp_min': 16.69,
    'temp_max': 16.69,
    'pressure': 1006,
    'sea_level': 1006,
    'grnd_level': 985,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 62},
   'wind': {'speed': 3.24, 'deg': 21, 'gust': 7.24},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-09 21:00:00'},
  {'dt': 1778371200,
   'main': {'temp': 13.47,
    'feels_like': 12.49,
    'temp_min': 13.47,
    'temp_max': 13.47,
    'pressure': 1009,
    'sea_level': 1009,
    'grnd_level': 987,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 61},
   'wind': {'speed': 3.56, 'deg': 43, 'gust': 4.78},
   'visibility': 10000,
   'pop': 0.2,
   'rain': {'3h': 0.11},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-10 00:00:00'},
  {'dt': 1778382000,
   'main': {'temp': 11.65,
    'feels_like': 10.67,
    'temp_min': 11.65,
    'temp_max': 11.65,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 990,
    'humidity': 69,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 38},
   'wind': {'speed': 1.36, 'deg': 28, 'gust': 4.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-10 03:00:00'},
  {'dt': 1778392800,
   'main': {'temp': 11.38,
    'feels_like': 10.32,
    'temp_min': 11.38,
    'temp_max': 11.38,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 992,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 57},
   'wind': {'speed': 1.74, 'deg': 303, 'gust': 3.11},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-10 06:00:00'},
  {'dt': 1778403600,
   'main': {'temp': 10.17,
    'feels_like': 8.94,
    'temp_min': 10.17,
    'temp_max': 10.17,
    'pressure': 1015,
    'sea_level': 1015,
    'grnd_level': 993,
    'humidity': 65,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04n'}],
   'clouds': {'all': 99},
   'wind': {'speed': 2.64, 'deg': 338, 'gust': 6.06},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-10 09:00:00'},
  {'dt': 1778414400,
   'main': {'temp': 9.84,
    'feels_like': 8.67,
    'temp_min': 9.84,
    'temp_max': 9.84,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 995,
    'humidity': 63,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 2.45, 'deg': 325, 'gust': 4.14},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-10 12:00:00'},
  {'dt': 1778425200,
   'main': {'temp': 13.16,
    'feels_like': 11.71,
    'temp_min': 13.16,
    'temp_max': 13.16,
    'pressure': 1017,
    'sea_level': 1017,
    'grnd_level': 995,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 69},
   'wind': {'speed': 3.36, 'deg': 359, 'gust': 4.54},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-10 15:00:00'},
  {'dt': 1778436000,
   'main': {'temp': 14.6,
    'feels_like': 13.19,
    'temp_min': 14.6,
    'temp_max': 14.6,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 996,
    'humidity': 41,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 58},
   'wind': {'speed': 5.13, 'deg': 47, 'gust': 4.97},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-10 18:00:00'},
  {'dt': 1778446800,
   'main': {'temp': 14.34,
    'feels_like': 12.85,
    'temp_min': 14.34,
    'temp_max': 14.34,
    'pressure': 1018,
    'sea_level': 1018,
    'grnd_level': 996,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 78},
   'wind': {'speed': 4.05, 'deg': 70, 'gust': 4.9},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-10 21:00:00'},
  {'dt': 1778457600,
   'main': {'temp': 13.04,
    'feels_like': 11.5,
    'temp_min': 13.04,
    'temp_max': 13.04,
    'pressure': 1019,
    'sea_level': 1019,
    'grnd_level': 997,
    'humidity': 42,
    'temp_kf': 0},
   'weather': [{'id': 804,
     'main': 'Clouds',
     'description': 'overcast clouds',
     'icon': '04d'}],
   'clouds': {'all': 90},
   'wind': {'speed': 2.34, 'deg': 31, 'gust': 4.68},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-11 00:00:00'},
  {'dt': 1778468400,
   'main': {'temp': 11.37,
    'feels_like': 9.87,
    'temp_min': 11.37,
    'temp_max': 11.37,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 999,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 33},
   'wind': {'speed': 1.53, 'deg': 326, 'gust': 4.93},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-11 03:00:00'},
  {'dt': 1778479200,
   'main': {'temp': 9.9,
    'feels_like': 8.49,
    'temp_min': 9.9,
    'temp_max': 9.9,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 999,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 19},
   'wind': {'speed': 2.84, 'deg': 351, 'gust': 6.88},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-11 06:00:00'},
  {'dt': 1778490000,
   'main': {'temp': 7.53,
    'feels_like': 5.42,
    'temp_min': 7.53,
    'temp_max': 7.53,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1000,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 3.19, 'deg': 13, 'gust': 6.39},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-11 09:00:00'},
  {'dt': 1778500800,
   'main': {'temp': 7.54,
    'feels_like': 5.55,
    'temp_min': 7.54,
    'temp_max': 7.54,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1002,
    'humidity': 65,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 1},
   'wind': {'speed': 3.01, 'deg': 20, 'gust': 5.07},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-11 12:00:00'},
  {'dt': 1778511600,
   'main': {'temp': 10.54,
    'feels_like': 8.82,
    'temp_min': 10.54,
    'temp_max': 10.54,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1003,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.16, 'deg': 36, 'gust': 4.07},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-11 15:00:00'},
  {'dt': 1778522400,
   'main': {'temp': 12.43,
    'feels_like': 10.72,
    'temp_min': 12.43,
    'temp_max': 12.43,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1002,
    'humidity': 38,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 1},
   'wind': {'speed': 4.92, 'deg': 59, 'gust': 5.34},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-11 18:00:00'},
  {'dt': 1778533200,
   'main': {'temp': 12.25,
    'feels_like': 10.55,
    'temp_min': 12.25,
    'temp_max': 12.25,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1001,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 3},
   'wind': {'speed': 4.89, 'deg': 79, 'gust': 4.69},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-11 21:00:00'},
  {'dt': 1778544000,
   'main': {'temp': 9.65,
    'feels_like': 7.79,
    'temp_min': 9.65,
    'temp_max': 9.65,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1001,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 28},
   'wind': {'speed': 3.56, 'deg': 94, 'gust': 4.42},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-12 00:00:00'},
  {'dt': 1778554800,
   'main': {'temp': 8.48,
    'feels_like': 6.85,
    'temp_min': 8.48,
    'temp_max': 8.48,
    'pressure': 1024,
    'sea_level': 1024,
    'grnd_level': 1002,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 13},
   'wind': {'speed': 2.75, 'deg': 128, 'gust': 5.77},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-12 03:00:00'},
  {'dt': 1778565600,
   'main': {'temp': 8.32,
    'feels_like': 6.84,
    'temp_min': 8.32,
    'temp_max': 8.32,
    'pressure': 1023,
    'sea_level': 1023,
    'grnd_level': 1001,
    'humidity': 49,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 9},
   'wind': {'speed': 2.49, 'deg': 164, 'gust': 6.1},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-12 06:00:00'},
  {'dt': 1778576400,
   'main': {'temp': 7.73,
    'feels_like': 6.19,
    'temp_min': 7.73,
    'temp_max': 7.73,
    'pressure': 1022,
    'sea_level': 1022,
    'grnd_level': 1000,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 72},
   'wind': {'speed': 2.43, 'deg': 176, 'gust': 7.14},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-12 09:00:00'},
  {'dt': 1778587200,
   'main': {'temp': 8.78,
    'feels_like': 6.57,
    'temp_min': 8.78,
    'temp_max': 8.78,
    'pressure': 1021,
    'sea_level': 1021,
    'grnd_level': 999,
    'humidity': 48,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 74},
   'wind': {'speed': 3.86, 'deg': 175, 'gust': 10.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-12 12:00:00'},
  {'dt': 1778598000,
   'main': {'temp': 6.66,
    'feels_like': 3.12,
    'temp_min': 6.66,
    'temp_max': 6.66,
    'pressure': 1020,
    'sea_level': 1020,
    'grnd_level': 998,
    'humidity': 89,
    'temp_kf': 0},
   'weather': [{'id': 501,
     'main': 'Rain',
     'description': 'moderate rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 5.69, 'deg': 174, 'gust': 13.87},
   'visibility': 9573,
   'pop': 1,
   'rain': {'3h': 5.08},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-12 15:00:00'},
  {'dt': 1778608800,
   'main': {'temp': 8.3,
    'feels_like': 4.5,
    'temp_min': 8.3,
    'temp_max': 8.3,
    'pressure': 1014,
    'sea_level': 1014,
    'grnd_level': 992,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 7.87, 'deg': 162, 'gust': 17.78},
   'visibility': 8309,
   'pop': 1,
   'rain': {'3h': 2.06},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-12 18:00:00'},
  {'dt': 1778619600,
   'main': {'temp': 12.24,
    'feels_like': 11.56,
    'temp_min': 12.24,
    'temp_max': 12.24,
    'pressure': 1011,
    'sea_level': 1011,
    'grnd_level': 989,
    'humidity': 78,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 6.49, 'deg': 172, 'gust': 15.58},
   'visibility': 10000,
   'pop': 0.36,
   'rain': {'3h': 0.32},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-12 21:00:00'},
  {'dt': 1778630400,
   'main': {'temp': 15.01,
    'feels_like': 14.76,
    'temp_min': 15.01,
    'temp_max': 15.01,
    'pressure': 1008,
    'sea_level': 1008,
    'grnd_level': 986,
    'humidity': 84,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10d'}],
   'clouds': {'all': 100},
   'wind': {'speed': 4.6, 'deg': 198, 'gust': 12.32},
   'visibility': 10000,
   'pop': 0.28,
   'rain': {'3h': 0.2},
   'sys': {'pod': 'd'},
   'dt_txt': '2026-05-13 00:00:00'},
  {'dt': 1778641200,
   'main': {'temp': 13.29,
    'feels_like': 13.16,
    'temp_min': 13.29,
    'temp_max': 13.29,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 986,
    'humidity': 95,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',
     'icon': '10n'}],
   'clouds': {'all': 40},
   'wind': {'speed': 2.5, 'deg': 274, 'gust': 7.54},
   'visibility': 10000,
   'pop': 1,
   'rain': {'3h': 2.22},
   'sys': {'pod': 'n'},
   'dt_txt': '2026-05-13 03:00:00'},
  {'dt': 1778652000,
   'main': {'temp': 12.49,
    'feels_like': 12.07,
    'temp_min': 12.49,
    'temp_max': 12.49,
    'pressure': 1007,
    'sea_level': 1007,
    'grnd_level': 986,
    'humidity': 87,
    'temp_kf': 0},
   'weather': [{'id': 500,
     'main': 'Rain',
     'description': 'light rain',

In [408]:
# The forecast data is stored in the 'list' key
# Convert the 'list' into 1 dataframe

forecast_list = chicago_forecast['list']
forecast_list

[{'dt': 1778241600,
  'main': {'temp': 5.58,
   'feels_like': 5.58,
   'temp_min': 5.58,
   'temp_max': 7.27,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 990,
   'humidity': 87,
   'temp_kf': -1.69},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 26},
  'wind': {'speed': 0.62, 'deg': 107, 'gust': 0.85},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-08 12:00:00'},
 {'dt': 1778252400,
  'main': {'temp': 12.05,
   'feels_like': 10.9,
   'temp_min': 12.05,
   'temp_max': 15.71,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 990,
   'humidity': 61,
   'temp_kf': -3.66},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 29},
  'wind': {'speed': 2.17, 'deg': 136, 'gust': 2.15},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-08 15:00:00'},
 {'dt': 1778263200,
  'main': {'temp': 17.3,
   'feels_like': 16.5,
   'temp_min': 17.3,
   'temp_max': 17.3,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 988,
   'humidity': 54,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 66},
  'wind': {'speed': 1.91, 'deg': 165, 'gust': 3.29},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.17},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-08 18:00:00'},
 {'dt': 1778274000,
  'main': {'temp': 16.5,
   'feels_like': 16.03,
   'temp_min': 16.5,
   'temp_max': 16.5,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 986,
   'humidity': 70,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 3.37, 'deg': 181, 'gust': 3.58},
  'visibility': 10000,
  'pop': 0.8,
  'rain': {'3h': 1.02},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-08 21:00:00'},
 {'dt': 1778284800,
  'main': {'temp': 14.86,
   'feels_like': 14.23,
   'temp_min': 14.86,
   'temp_max': 14.86,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 986,
   'humidity': 70,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 85},
  'wind': {'speed': 3.39, 'deg': 217, 'gust': 4.9},
  'visibility': 10000,
  'pop': 0.68,
  'rain': {'3h': 0.1},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-09 00:00:00'},
 {'dt': 1778295600,
  'main': {'temp': 11.83,
   'feels_like': 11.21,
   'temp_min': 11.83,
   'temp_max': 11.83,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 985,
   'humidity': 82,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 48},
  'wind': {'speed': 2.39, 'deg': 180, 'gust': 4.2},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-09 03:00:00'},
 {'dt': 1778306400,
  'main': {'temp': 10.71,
   'feels_like': 10.06,
   'temp_min': 10.71,
   'temp_max': 10.71,
   'pressure': 1006,
   'sea_level': 1006,
   'grnd_level': 984,
   'humidity': 85,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 34},
  'wind': {'speed': 3.18, 'deg': 201, 'gust': 7.73},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-09 06:00:00'},
 {'dt': 1778317200,
  'main': {'temp': 10.45,
   'feels_like': 9.8,
   'temp_min': 10.45,
   'temp_max': 10.45,
   'pressure': 1004,
   'sea_level': 1004,
   'grnd_level': 983,
   'humidity': 86,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 14},
  'wind': {'speed': 3.67, 'deg': 217, 'gust': 10.58},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-09 09:00:00'},
 {'dt': 1778328000,
  'main': {'temp': 11.74,
   'feels_like': 11.14,
   'temp_min': 11.74,
   'temp_max': 11.74,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 983,
   'humidity': 83,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 47},
  'wind': {'speed': 4.77, 'deg': 223, 'gust': 13.41},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.2},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-09 12:00:00'},
 {'dt': 1778338800,
  'main': {'temp': 16.93,
   'feels_like': 16.19,
   'temp_min': 16.93,
   'temp_max': 16.93,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 984,
   'humidity': 58,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 29},
  'wind': {'speed': 4.99, 'deg': 252, 'gust': 7.72},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-09 15:00:00'},
 {'dt': 1778349600,
  'main': {'temp': 20.45,
   'feels_like': 19.44,
   'temp_min': 20.45,
   'temp_max': 20.45,
   'pressure': 1005,
   'sea_level': 1005,
   'grnd_level': 984,
   'humidity': 34,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 65},
  'wind': {'speed': 4.7, 'deg': 293, 'gust': 11.28},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-09 18:00:00'},
 {'dt': 1778360400,
  'main': {'temp': 16.69,
   'feels_like': 15.72,
   'temp_min': 16.69,
   'temp_max': 16.69,
   'pressure': 1006,
   'sea_level': 1006,
   'grnd_level': 985,
   'humidity': 50,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 62},
  'wind': {'speed': 3.24, 'deg': 21, 'gust': 7.24},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-09 21:00:00'},
 {'dt': 1778371200,
  'main': {'temp': 13.47,
   'feels_like': 12.49,
   'temp_min': 13.47,
   'temp_max': 13.47,
   'pressure': 1009,
   'sea_level': 1009,
   'grnd_level': 987,
   'humidity': 62,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 61},
  'wind': {'speed': 3.56, 'deg': 43, 'gust': 4.78},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.11},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-10 00:00:00'},
 {'dt': 1778382000,
  'main': {'temp': 11.65,
   'feels_like': 10.67,
   'temp_min': 11.65,
   'temp_max': 11.65,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 990,
   'humidity': 69,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 38},
  'wind': {'speed': 1.36, 'deg': 28, 'gust': 4.32},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-10 03:00:00'},
 {'dt': 1778392800,
  'main': {'temp': 11.38,
   'feels_like': 10.32,
   'temp_min': 11.38,
   'temp_max': 11.38,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 992,
   'humidity': 67,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 57},
  'wind': {'speed': 1.74, 'deg': 303, 'gust': 3.11},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-10 06:00:00'},
 {'dt': 1778403600,
  'main': {'temp': 10.17,
   'feels_like': 8.94,
   'temp_min': 10.17,
   'temp_max': 10.17,
   'pressure': 1015,
   'sea_level': 1015,
   'grnd_level': 993,
   'humidity': 65,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04n'}],
  'clouds': {'all': 99},
  'wind': {'speed': 2.64, 'deg': 338, 'gust': 6.06},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-10 09:00:00'},
 {'dt': 1778414400,
  'main': {'temp': 9.84,
   'feels_like': 8.67,
   'temp_min': 9.84,
   'temp_max': 9.84,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 995,
   'humidity': 63,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 2.45, 'deg': 325, 'gust': 4.14},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-10 12:00:00'},
 {'dt': 1778425200,
  'main': {'temp': 13.16,
   'feels_like': 11.71,
   'temp_min': 13.16,
   'temp_max': 13.16,
   'pressure': 1017,
   'sea_level': 1017,
   'grnd_level': 995,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 69},
  'wind': {'speed': 3.36, 'deg': 359, 'gust': 4.54},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-10 15:00:00'},
 {'dt': 1778436000,
  'main': {'temp': 14.6,
   'feels_like': 13.19,
   'temp_min': 14.6,
   'temp_max': 14.6,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 996,
   'humidity': 41,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 58},
  'wind': {'speed': 5.13, 'deg': 47, 'gust': 4.97},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-10 18:00:00'},
 {'dt': 1778446800,
  'main': {'temp': 14.34,
   'feels_like': 12.85,
   'temp_min': 14.34,
   'temp_max': 14.34,
   'pressure': 1018,
   'sea_level': 1018,
   'grnd_level': 996,
   'humidity': 39,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 78},
  'wind': {'speed': 4.05, 'deg': 70, 'gust': 4.9},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-10 21:00:00'},
 {'dt': 1778457600,
  'main': {'temp': 13.04,
   'feels_like': 11.5,
   'temp_min': 13.04,
   'temp_max': 13.04,
   'pressure': 1019,
   'sea_level': 1019,
   'grnd_level': 997,
   'humidity': 42,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 90},
  'wind': {'speed': 2.34, 'deg': 31, 'gust': 4.68},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-11 00:00:00'},
 {'dt': 1778468400,
  'main': {'temp': 11.37,
   'feels_like': 9.87,
   'temp_min': 11.37,
   'temp_max': 11.37,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 999,
   'humidity': 50,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 33},
  'wind': {'speed': 1.53, 'deg': 326, 'gust': 4.93},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-11 03:00:00'},
 {'dt': 1778479200,
  'main': {'temp': 9.9,
   'feels_like': 8.49,
   'temp_min': 9.9,
   'temp_max': 9.9,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 999,
   'humidity': 57,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 19},
  'wind': {'speed': 2.84, 'deg': 351, 'gust': 6.88},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-11 06:00:00'},
 {'dt': 1778490000,
  'main': {'temp': 7.53,
   'feels_like': 5.42,
   'temp_min': 7.53,
   'temp_max': 7.53,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1000,
   'humidity': 70,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 1},
  'wind': {'speed': 3.19, 'deg': 13, 'gust': 6.39},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-11 09:00:00'},
 {'dt': 1778500800,
  'main': {'temp': 7.54,
   'feels_like': 5.55,
   'temp_min': 7.54,
   'temp_max': 7.54,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1002,
   'humidity': 65,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 1},
  'wind': {'speed': 3.01, 'deg': 20, 'gust': 5.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-11 12:00:00'},
 {'dt': 1778511600,
  'main': {'temp': 10.54,
   'feels_like': 8.82,
   'temp_min': 10.54,
   'temp_max': 10.54,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1003,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.16, 'deg': 36, 'gust': 4.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-11 15:00:00'},
 {'dt': 1778522400,
  'main': {'temp': 12.43,
   'feels_like': 10.72,
   'temp_min': 12.43,
   'temp_max': 12.43,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1002,
   'humidity': 38,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 1},
  'wind': {'speed': 4.92, 'deg': 59, 'gust': 5.34},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-11 18:00:00'},
 {'dt': 1778533200,
  'main': {'temp': 12.25,
   'feels_like': 10.55,
   'temp_min': 12.25,
   'temp_max': 12.25,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1001,
   'humidity': 39,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 3},
  'wind': {'speed': 4.89, 'deg': 79, 'gust': 4.69},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-11 21:00:00'},
 {'dt': 1778544000,
  'main': {'temp': 9.65,
   'feels_like': 7.79,
   'temp_min': 9.65,
   'temp_max': 9.65,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1001,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 28},
  'wind': {'speed': 3.56, 'deg': 94, 'gust': 4.42},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-12 00:00:00'},
 {'dt': 1778554800,
  'main': {'temp': 8.48,
   'feels_like': 6.85,
   'temp_min': 8.48,
   'temp_max': 8.48,
   'pressure': 1024,
   'sea_level': 1024,
   'grnd_level': 1002,
   'humidity': 50,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 13},
  'wind': {'speed': 2.75, 'deg': 128, 'gust': 5.77},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-12 03:00:00'},
 {'dt': 1778565600,
  'main': {'temp': 8.32,
   'feels_like': 6.84,
   'temp_min': 8.32,
   'temp_max': 8.32,
   'pressure': 1023,
   'sea_level': 1023,
   'grnd_level': 1001,
   'humidity': 49,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 9},
  'wind': {'speed': 2.49, 'deg': 164, 'gust': 6.1},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-12 06:00:00'},
 {'dt': 1778576400,
  'main': {'temp': 7.73,
   'feels_like': 6.19,
   'temp_min': 7.73,
   'temp_max': 7.73,
   'pressure': 1022,
   'sea_level': 1022,
   'grnd_level': 1000,
   'humidity': 52,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 72},
  'wind': {'speed': 2.43, 'deg': 176, 'gust': 7.14},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-12 09:00:00'},
 {'dt': 1778587200,
  'main': {'temp': 8.78,
   'feels_like': 6.57,
   'temp_min': 8.78,
   'temp_max': 8.78,
   'pressure': 1021,
   'sea_level': 1021,
   'grnd_level': 999,
   'humidity': 48,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 74},
  'wind': {'speed': 3.86, 'deg': 175, 'gust': 10.51},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-12 12:00:00'},
 {'dt': 1778598000,
  'main': {'temp': 6.66,
   'feels_like': 3.12,
   'temp_min': 6.66,
   'temp_max': 6.66,
   'pressure': 1020,
   'sea_level': 1020,
   'grnd_level': 998,
   'humidity': 89,
   'temp_kf': 0},
  'weather': [{'id': 501,
    'main': 'Rain',
    'description': 'moderate rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 5.69, 'deg': 174, 'gust': 13.87},
  'visibility': 9573,
  'pop': 1,
  'rain': {'3h': 5.08},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-12 15:00:00'},
 {'dt': 1778608800,
  'main': {'temp': 8.3,
   'feels_like': 4.5,
   'temp_min': 8.3,
   'temp_max': 8.3,
   'pressure': 1014,
   'sea_level': 1014,
   'grnd_level': 992,
   'humidity': 86,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 7.87, 'deg': 162, 'gust': 17.78},
  'visibility': 8309,
  'pop': 1,
  'rain': {'3h': 2.06},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-12 18:00:00'},
 {'dt': 1778619600,
  'main': {'temp': 12.24,
   'feels_like': 11.56,
   'temp_min': 12.24,
   'temp_max': 12.24,
   'pressure': 1011,
   'sea_level': 1011,
   'grnd_level': 989,
   'humidity': 78,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 6.49, 'deg': 172, 'gust': 15.58},
  'visibility': 10000,
  'pop': 0.36,
  'rain': {'3h': 0.32},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-12 21:00:00'},
 {'dt': 1778630400,
  'main': {'temp': 15.01,
   'feels_like': 14.76,
   'temp_min': 15.01,
   'temp_max': 15.01,
   'pressure': 1008,
   'sea_level': 1008,
   'grnd_level': 986,
   'humidity': 84,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10d'}],
  'clouds': {'all': 100},
  'wind': {'speed': 4.6, 'deg': 198, 'gust': 12.32},
  'visibility': 10000,
  'pop': 0.28,
  'rain': {'3h': 0.2},
  'sys': {'pod': 'd'},
  'dt_txt': '2026-05-13 00:00:00'},
 {'dt': 1778641200,
  'main': {'temp': 13.29,
   'feels_like': 13.16,
   'temp_min': 13.29,
   'temp_max': 13.29,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 986,
   'humidity': 95,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 40},
  'wind': {'speed': 2.5, 'deg': 274, 'gust': 7.54},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 2.22},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-13 03:00:00'},
 {'dt': 1778652000,
  'main': {'temp': 12.49,
   'feels_like': 12.07,
   'temp_min': 12.49,
   'temp_max': 12.49,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 986,
   'humidity': 87,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 30},
  'wind': {'speed': 3.14, 'deg': 284, 'gust': 9.38},
  'visibility': 10000,
  'pop': 1,
  'rain': {'3h': 0.21},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-13 06:00:00'},
 {'dt': 1778662800,
  'main': {'temp': 11.78,
   'feels_like': 11.31,
   'temp_min': 11.78,
   'temp_max': 11.78,
   'pressure': 1007,
   'sea_level': 1007,
   'grnd_level': 986,
   'humidity': 88,
   'temp_kf': 0},
  'weather': [{'id': 500,
    'main': 'Rain',
    'description': 'light rain',
    'icon': '10n'}],
  'clouds': {'all': 55},
  'wind': {'speed': 4.59, 'deg': 281, 'gust': 10.97},
  'visibility': 10000,
  'pop': 0.2,
  'rain': {'3h': 0.24},
  'sys': {'pod': 'n'},
  'dt_txt': '2026-05-13 09:00:00'}]

In [409]:
# Flatten the nested dictionaries
forecast_df = pd.json_normalize(forecast_list)

# Extract the key-value pairs inside the weather list
forecast_df['weather_id'] = forecast_df['weather'].apply(lambda x: x[0]['id'])
forecast_df['weather_main'] = forecast_df['weather'].apply(lambda x: x[0]['main'])
forecast_df['weather_description'] = forecast_df['weather'].apply(lambda x: x[0]['description'])
forecast_df['weather_icon'] = forecast_df['weather'].apply(lambda x: x[0]['icon'])

forecast_df

,dt,weather,visibility,pop,dt_txt,main.temp,main.feels_like,main.temp_min,main.temp_max,main.pressure,...,clouds.all,wind.speed,wind.deg,wind.gust,sys.pod,rain.3h,weather_id,weather_main,weather_description,weather_icon
0,1778241600,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-08 12:00:00,5.58,5.58,5.58,7.27,1011,...,26,0.62,107,0.85,d,NaN,802,Clouds,scattered clouds,03d
1,1778252400,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-08 15:00:00,12.05,10.90,12.05,15.71,1011,...,29,2.17,136,2.15,d,NaN,802,Clouds,scattered clouds,03d
2,1778263200,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.20,2026-05-08 18:00:00,17.30,16.50,17.30,17.30,1009,...,66,1.91,165,3.29,d,0.17,500,Rain,light rain,10d
3,1778274000,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.80,2026-05-08 21:00:00,16.50,16.03,16.50,16.50,1008,...,100,3.37,181,3.58,d,1.02,500,Rain,light rain,10d
4,1778284800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.68,2026-05-09 00:00:00,14.86,14.23,14.86,14.86,1007,...,85,3.39,217,4.90,d,0.10,500,Rain,light rain,10d
5,1778295600,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-09 03:00:00,11.83,11.21,11.83,11.83,1007,...,48,2.39,180,4.20,n,NaN,802,Clouds,scattered clouds,03n
6,1778306400,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-09 06:00:00,10.71,10.06,10.71,10.71,1006,...,34,3.18,201,7.73,n,NaN,802,Clouds,scattered clouds,03n
7,1778317200,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-09 09:00:00,10.45,9.80,10.45,10.45,1004,...,14,3.67,217,10.58,n,NaN,801,Clouds,few clouds,02n
8,1778328000,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.20,2026-05-09 12:00:00,11.74,11.14,11.74,11.74,1005,...,47,4.77,223,13.41,d,0.20,500,Rain,light rain,10d
9,1778338800,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-09 15:00:00,16.93,16.19,16.93,16.93,1005,...,29,4.99,252,7.72,d,NaN,802,Clouds,scattered clouds,03d
10,1778349600,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-09 18:00:00,20.45,19.44,20.45,20.45,1005,...,65,4.70,293,11.28,d,NaN,803,Clouds,broken clouds,04d
11,1778360400,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-09 21:00:00,16.69,15.72,16.69,16.69,1006,...,62,3.24,21,7.24,d,NaN,803,Clouds,broken clouds,04d
12,1778371200,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.20,2026-05-10 00:00:00,13.47,12.49,13.47,13.47,1009,...,61,3.56,43,4.78,d,0.11,500,Rain,light rain,10d
13,1778382000,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 03:00:00,11.65,10.67,11.65,11.65,1011,...,38,1.36,28,4.32,n,NaN,802,Clouds,scattered clouds,03n
14,1778392800,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 06:00:00,11.38,10.32,11.38,11.38,1014,...,57,1.74,303,3.11,n,NaN,803,Clouds,broken clouds,04n
15,1778403600,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 09:00:00,10.17,8.94,10.17,10.17,1015,...,99,2.64,338,6.06,n,NaN,804,Clouds,overcast clouds,04n
16,1778414400,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 12:00:00,9.84,8.67,9.84,9.84,1017,...,100,2.45,325,4.14,d,NaN,804,Clouds,overcast clouds,04d
17,1778425200,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 15:00:00,13.16,11.71,13.16,13.16,1017,...,69,3.36,359,4.54,d,NaN,803,Clouds,broken clouds,04d
18,1778436000,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 18:00:00,14.60,13.19,14.60,14.60,1018,...,58,5.13,47,4.97,d,NaN,803,Clouds,broken clouds,04d
19,1778446800,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-10 21:00:00,14.34,12.85,14.34,14.34,1018,...,78,4.05,70,4.90,d,NaN,803,Clouds,broken clouds,04d
20,1778457600,"[{'id': 804, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-11 00:00:00,13.04,11.50,13.04,13.04,1019,...,90,2.34,31,4.68,d,NaN,804,Clouds,overcast clouds,04d
21,1778468400,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-11 03:00:00,11.37,9.87,11.37,11.37,1021,...,33,1.53,326,4.93,n,NaN,802,Clouds,scattered clouds,03n
22,1778479200,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-11 06:00:00,9.90,8.49,9.90,9.90,1021,...,19,2.84,351,6.88,n,NaN,801,Clouds,few clouds,02n
23,1778490000,"[{'id': 800, 'main': 'Clear', 'description': '...",10000,0.00,2026-05-11 09:00:00,7.53,5.42,7.53,7.53,1023,...,1,3.19,13,6.39,n,NaN,800,Clear,clear sky,01n
24,1778500800,"[{'id': 800, 'main': 'Clear', 'description': '...",10000,0.00,2026-05-11 12:00:00,7.54,5.55,7.54,7.54,1024,...,1,3.01,20,5.07,d,NaN,800,Clear,clear sky,01d
25,1778511600,"[{'id': 800, 'main': 'Clear', 'description': '...",10000,0.00,2026-05-11 15:00:00,10.54,8.82,10.54,10.54,1025,...,0,3.16,36,4.07,d,NaN,800,Clear,clear sky,01d
26,1778522400,"[{'id': 800, 'main': 'Clear', 'description': '...",10000,0.00,2026-05-11 18:00:00,12.43,10.72,12.43,12.43,1024,...,1,4.92,59,5.34,d,NaN,800,Clear,clear sky,01d
27,1778533200,"[{'id': 800, 'main': 'Clear', 'description': '...",10000,0.00,2026-05-11 21:00:00,12.25,10.55,12.25,12.25,1023,...,3,4.89,79,4.69,d,NaN,800,Clear,clear sky,01d
28,1778544000,"[{'id': 802, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-12 00:00:00,9.65,7.79,9.65,9.65,1023,...,28,3.56,94,4.42,d,NaN,802,Clouds,scattered clouds,03d
29,1778554800,"[{'id': 801, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-12 03:00:00,8.48,6.85,8.48,8.48,1024,...,13,2.75,128,5.77,n,NaN,801,Clouds,few clouds,02n
30,1778565600,"[{'id': 800, 'main': 'Clear', 'description': '...",10000,0.00,2026-05-12 06:00:00,8.32,6.84,8.32,8.32,1023,...,9,2.49,164,6.10,n,NaN,800,Clear,clear sky,01n
31,1778576400,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-12 09:00:00,7.73,6.19,7.73,7.73,1022,...,72,2.43,176,7.14,n,NaN,803,Clouds,broken clouds,04n
32,1778587200,"[{'id': 803, 'main': 'Clouds', 'description': ...",10000,0.00,2026-05-12 12:00:00,8.78,6.57,8.78,8.78,1021,...,74,3.86,175,10.51,d,NaN,803,Clouds,broken clouds,04d
33,1778598000,"[{'id': 501, 'main': 'Rain', 'description': 'm...",9573,1.00,2026-05-12 15:00:00,6.66,3.12,6.66,6.66,1020,...,100,5.69,174,13.87,d,5.08,501,Rain,moderate rain,10d
34,1778608800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",8309,1.00,2026-05-12 18:00:00,8.30,4.50,8.30,8.30,1014,...,100,7.87,162,17.78,d,2.06,500,Rain,light rain,10d
35,1778619600,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.36,2026-05-12 21:00:00,12.24,11.56,12.24,12.24,1011,...,100,6.49,172,15.58,d,0.32,500,Rain,light rain,10d
36,1778630400,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.28,2026-05-13 00:00:00,15.01,14.76,15.01,15.01,1008,...,100,4.60,198,12.32,d,0.20,500,Rain,light rain,10d
37,1778641200,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,1.00,2026-05-13 03:00:00,13.29,13.16,13.29,13.29,1007,...,40,2.50,274,7.54,n,2.22,500,Rain,light rain,10n
38,1778652000,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,1.00,2026-05-13 06:00:00,12.49,12.07,12.49,12.49,1007,...,30,3.14,284,9.38,n,0.21,500,Rain,light rain,10n
39,1778662800,"[{'id': 500, 'main': 'Rain', 'description': 'l...",10000,0.20,2026-05-13 09:00:00,11.78,11.31,11.78,11.78,1007,...,55,4.59,281,10.97,n,0.24,500,Rain,light rain,10n

In [410]:
# Drop the original weather column 
forecast_df = forecast_df.drop(columns=['weather'])

# Clean column names
forecast_df.columns = forecast_df.columns.str.replace('.', '_', regex=False)

forecast_df

,dt,visibility,pop,dt_txt,main_temp,main_feels_like,main_temp_min,main_temp_max,main_pressure,main_sea_level,...,clouds_all,wind_speed,wind_deg,wind_gust,sys_pod,rain_3h,weather_id,weather_main,weather_description,weather_icon
0,1778241600,10000,0.00,2026-05-08 12:00:00,5.58,5.58,5.58,7.27,1011,1011,...,26,0.62,107,0.85,d,NaN,802,Clouds,scattered clouds,03d
1,1778252400,10000,0.00,2026-05-08 15:00:00,12.05,10.90,12.05,15.71,1011,1011,...,29,2.17,136,2.15,d,NaN,802,Clouds,scattered clouds,03d
2,1778263200,10000,0.20,2026-05-08 18:00:00,17.30,16.50,17.30,17.30,1009,1009,...,66,1.91,165,3.29,d,0.17,500,Rain,light rain,10d
3,1778274000,10000,0.80,2026-05-08 21:00:00,16.50,16.03,16.50,16.50,1008,1008,...,100,3.37,181,3.58,d,1.02,500,Rain,light rain,10d
4,1778284800,10000,0.68,2026-05-09 00:00:00,14.86,14.23,14.86,14.86,1007,1007,...,85,3.39,217,4.90,d,0.10,500,Rain,light rain,10d
5,1778295600,10000,0.00,2026-05-09 03:00:00,11.83,11.21,11.83,11.83,1007,1007,...,48,2.39,180,4.20,n,NaN,802,Clouds,scattered clouds,03n
6,1778306400,10000,0.00,2026-05-09 06:00:00,10.71,10.06,10.71,10.71,1006,1006,...,34,3.18,201,7.73,n,NaN,802,Clouds,scattered clouds,03n
7,1778317200,10000,0.00,2026-05-09 09:00:00,10.45,9.80,10.45,10.45,1004,1004,...,14,3.67,217,10.58,n,NaN,801,Clouds,few clouds,02n
8,1778328000,10000,0.20,2026-05-09 12:00:00,11.74,11.14,11.74,11.74,1005,1005,...,47,4.77,223,13.41,d,0.20,500,Rain,light rain,10d
9,1778338800,10000,0.00,2026-05-09 15:00:00,16.93,16.19,16.93,16.93,1005,1005,...,29,4.99,252,7.72,d,NaN,802,Clouds,scattered clouds,03d
10,1778349600,10000,0.00,2026-05-09 18:00:00,20.45,19.44,20.45,20.45,1005,1005,...,65,4.70,293,11.28,d,NaN,803,Clouds,broken clouds,04d
11,1778360400,10000,0.00,2026-05-09 21:00:00,16.69,15.72,16.69,16.69,1006,1006,...,62,3.24,21,7.24,d,NaN,803,Clouds,broken clouds,04d
12,1778371200,10000,0.20,2026-05-10 00:00:00,13.47,12.49,13.47,13.47,1009,1009,...,61,3.56,43,4.78,d,0.11,500,Rain,light rain,10d
13,1778382000,10000,0.00,2026-05-10 03:00:00,11.65,10.67,11.65,11.65,1011,1011,...,38,1.36,28,4.32,n,NaN,802,Clouds,scattered clouds,03n
14,1778392800,10000,0.00,2026-05-10 06:00:00,11.38,10.32,11.38,11.38,1014,1014,...,57,1.74,303,3.11,n,NaN,803,Clouds,broken clouds,04n
15,1778403600,10000,0.00,2026-05-10 09:00:00,10.17,8.94,10.17,10.17,1015,1015,...,99,2.64,338,6.06,n,NaN,804,Clouds,overcast clouds,04n
16,1778414400,10000,0.00,2026-05-10 12:00:00,9.84,8.67,9.84,9.84,1017,1017,...,100,2.45,325,4.14,d,NaN,804,Clouds,overcast clouds,04d
17,1778425200,10000,0.00,2026-05-10 15:00:00,13.16,11.71,13.16,13.16,1017,1017,...,69,3.36,359,4.54,d,NaN,803,Clouds,broken clouds,04d
18,1778436000,10000,0.00,2026-05-10 18:00:00,14.60,13.19,14.60,14.60,1018,1018,...,58,5.13,47,4.97,d,NaN,803,Clouds,broken clouds,04d
19,1778446800,10000,0.00,2026-05-10 21:00:00,14.34,12.85,14.34,14.34,1018,1018,...,78,4.05,70,4.90,d,NaN,803,Clouds,broken clouds,04d
20,1778457600,10000,0.00,2026-05-11 00:00:00,13.04,11.50,13.04,13.04,1019,1019,...,90,2.34,31,4.68,d,NaN,804,Clouds,overcast clouds,04d
21,1778468400,10000,0.00,2026-05-11 03:00:00,11.37,9.87,11.37,11.37,1021,1021,...,33,1.53,326,4.93,n,NaN,802,Clouds,scattered clouds,03n
22,1778479200,10000,0.00,2026-05-11 06:00:00,9.90,8.49,9.90,9.90,1021,1021,...,19,2.84,351,6.88,n,NaN,801,Clouds,few clouds,02n
23,1778490000,10000,0.00,2026-05-11 09:00:00,7.53,5.42,7.53,7.53,1023,1023,...,1,3.19,13,6.39,n,NaN,800,Clear,clear sky,01n
24,1778500800,10000,0.00,2026-05-11 12:00:00,7.54,5.55,7.54,7.54,1024,1024,...,1,3.01,20,5.07,d,NaN,800,Clear,clear sky,01d
25,1778511600,10000,0.00,2026-05-11 15:00:00,10.54,8.82,10.54,10.54,1025,1025,...,0,3.16,36,4.07,d,NaN,800,Clear,clear sky,01d
26,1778522400,10000,0.00,2026-05-11 18:00:00,12.43,10.72,12.43,12.43,1024,1024,...,1,4.92,59,5.34,d,NaN,800,Clear,clear sky,01d
27,1778533200,10000,0.00,2026-05-11 21:00:00,12.25,10.55,12.25,12.25,1023,1023,...,3,4.89,79,4.69,d,NaN,800,Clear,clear sky,01d
28,1778544000,10000,0.00,2026-05-12 00:00:00,9.65,7.79,9.65,9.65,1023,1023,...,28,3.56,94,4.42,d,NaN,802,Clouds,scattered clouds,03d
29,1778554800,10000,0.00,2026-05-12 03:00:00,8.48,6.85,8.48,8.48,1024,1024,...,13,2.75,128,5.77,n,NaN,801,Clouds,few clouds,02n
30,1778565600,10000,0.00,2026-05-12 06:00:00,8.32,6.84,8.32,8.32,1023,1023,...,9,2.49,164,6.10,n,NaN,800,Clear,clear sky,01n
31,1778576400,10000,0.00,2026-05-12 09:00:00,7.73,6.19,7.73,7.73,1022,1022,...,72,2.43,176,7.14,n,NaN,803,Clouds,broken clouds,04n
32,1778587200,10000,0.00,2026-05-12 12:00:00,8.78,6.57,8.78,8.78,1021,1021,...,74,3.86,175,10.51,d,NaN,803,Clouds,broken clouds,04d
33,1778598000,9573,1.00,2026-05-12 15:00:00,6.66,3.12,6.66,6.66,1020,1020,...,100,5.69,174,13.87,d,5.08,501,Rain,moderate rain,10d
34,1778608800,8309,1.00,2026-05-12 18:00:00,8.30,4.50,8.30,8.30,1014,1014,...,100,7.87,162,17.78,d,2.06,500,Rain,light rain,10d
35,1778619600,10000,0.36,2026-05-12 21:00:00,12.24,11.56,12.24,12.24,1011,1011,...,100,6.49,172,15.58,d,0.32,500,Rain,light rain,10d
36,1778630400,10000,0.28,2026-05-13 00:00:00,15.01,14.76,15.01,15.01,1008,1008,...,100,4.60,198,12.32,d,0.20,500,Rain,light rain,10d
37,1778641200,10000,1.00,2026-05-13 03:00:00,13.29,13.16,13.29,13.29,1007,1007,...,40,2.50,274,7.54,n,2.22,500,Rain,light rain,10n
38,1778652000,10000,1.00,2026-05-13 06:00:00,12.49,12.07,12.49,12.49,1007,1007,...,30,3.14,284,9.38,n,0.21,500,Rain,light rain,10n
39,1778662800,10000,0.20,2026-05-13 09:00:00,11.78,11.31,11.78,11.78,1007,1007,...,55,4.59,281,10.97,n,0.24,500,Rain,light rain,10n

Now, using any method you'd like, use the API output to generate a dataframe of exactly two columns: the date (converted to a pandas `datetime` type!) and temperature. Notice the given temperatures are in Kelvin. So convert to Celsius, simply subtract 273.15 from Kelvin.

In [411]:
forecast_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dt                   40 non-null     int64
 1   visibility           40 non-null     int64
 2   pop                  40 non-null     float64
 3   dt_txt               40 non-null     str
 4   main_temp            40 non-null     float64
 5   main_feels_like      40 non-null     float64
 6   main_temp_min        40 non-null     float64
 7   main_temp_max        40 non-null     float64
 8   main_pressure        40 non-null     int64
 9   main_sea_level       40 non-null     int64
 10  main_grnd_level      40 non-null     int64
 11  main_humidity        40 non-null     int64
 12  main_temp_kf         40 non-null     float64
 13  clouds_all           40 non-null     int64
 14  wind_speed           40 non-null     float64
 15  wind_deg             40 non-null     int64
 16  wind_gust            40 non-null     float64
 17  sys_pod              40 non-null     str
 18  rain_3h              12 non-null     float64
 19  weather_id           40 non-null     int64
 20  weather_main         40 non-null     str
 21  weather_description  40 non-null     str
 22  weather_icon         40 non-null     str
dtypes: float64(9), int64(9), str(5)
memory usage: 7.3 KB

In [413]:
# Convert dt_txt to datetime
forecast_df['dt_txt'] = pd.to_datetime(forecast_df['dt_txt'])

# Check the datatype of dt_txt >> datetime64[us]
forecast_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dt                   40 non-null     int64
 1   visibility           40 non-null     int64
 2   pop                  40 non-null     float64
 3   dt_txt               40 non-null     datetime64[us]
 4   main_temp            40 non-null     float64
 5   main_feels_like      40 non-null     float64
 6   main_temp_min        40 non-null     float64
 7   main_temp_max        40 non-null     float64
 8   main_pressure        40 non-null     int64
 9   main_sea_level       40 non-null     int64
 10  main_grnd_level      40 non-null     int64
 11  main_humidity        40 non-null     int64
 12  main_temp_kf         40 non-null     float64
 13  clouds_all           40 non-null     int64
 14  wind_speed           40 non-null     float64
 15  wind_deg             40 non-null     int64
 16  wind_gust            40 non-null     float64
 17  sys_pod              40 non-null     str
 18  rain_3h              12 non-null     float64
 19  weather_id           40 non-null     int64
 20  weather_main         40 non-null     str
 21  weather_description  40 non-null     str
 22  weather_icon         40 non-null     str
dtypes: datetime64[us](1), float64(9), int64(9), str(4)
memory usage: 7.3 KB

In [414]:
# Create a dataframe 

temperature_forecast = forecast_df[['dt_txt', 'main_temp']]
temperature_forecast

                dt_txt  main_temp
0  2026-05-08 12:00:00       5.58
1  2026-05-08 15:00:00      12.05
2  2026-05-08 18:00:00      17.30
3  2026-05-08 21:00:00      16.50
4  2026-05-09 00:00:00      14.86
5  2026-05-09 03:00:00      11.83
6  2026-05-09 06:00:00      10.71
7  2026-05-09 09:00:00      10.45
8  2026-05-09 12:00:00      11.74
9  2026-05-09 15:00:00      16.93
10 2026-05-09 18:00:00      20.45
11 2026-05-09 21:00:00      16.69
12 2026-05-10 00:00:00      13.47
13 2026-05-10 03:00:00      11.65
14 2026-05-10 06:00:00      11.38
15 2026-05-10 09:00:00      10.17
16 2026-05-10 12:00:00       9.84
17 2026-05-10 15:00:00      13.16
18 2026-05-10 18:00:00      14.60
19 2026-05-10 21:00:00      14.34
20 2026-05-11 00:00:00      13.04
21 2026-05-11 03:00:00      11.37
22 2026-05-11 06:00:00       9.90
23 2026-05-11 09:00:00       7.53
24 2026-05-11 12:00:00       7.54
25 2026-05-11 15:00:00      10.54
26 2026-05-11 18:00:00      12.43
27 2026-05-11 21:00:00      12.25
28 2026-05-12 00:00:00       9.65
29 2026-05-12 03:00:00       8.48
30 2026-05-12 06:00:00       8.32
31 2026-05-12 09:00:00       7.73
32 2026-05-12 12:00:00       8.78
33 2026-05-12 15:00:00       6.66
34 2026-05-12 18:00:00       8.30
35 2026-05-12 21:00:00      12.24
36 2026-05-13 00:00:00      15.01
37 2026-05-13 03:00:00      13.29
38 2026-05-13 06:00:00      12.49
39 2026-05-13 09:00:00      11.78

Finally, create a line chart of your temperature forecast. That is, your x-axis should be the date and your y-axis should be the temperature in Celsius. Make sure to include all appropriate labels and make the graph as pretty as you'd like.

In [415]:
import plotly.express as px

fig = px.line(
        temperature_forecast, 
        x='dt_txt', 
        y='main_temp', 
        title='🌤️ 5-Day Temperature Forecast in Chicago, IL',
        labels={
            'dt_txt': 'Date & Time',
            'main_temp': 'Temperature (°C)'
        },
)

#Enhance graph layout
fig.update_layout(
    template='plotly_white',
    title_font=dict(size=22, family='Helvetica', color='#2c3e50'),
    xaxis_title='Date & Time',
    yaxis_title='Temperature (°C)',
    hovermode='x unified'
)

#Enhance lines & markers
fig.update_traces(
    mode='lines+markers',
    line=dict(color='#1f77b4', width=3),
    marker=dict(size=6)
)

fig.show()

#### Export
Your report is ready to ship! [Save the dataframe you created as a CSV](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv) and [the plot you made as a PNG](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html).

In [416]:
#Save dataframe as CSV
temperature_forecast.to_csv("chicago_5day_forecast.csv", index=False)

#Save line chart as PNG 
fig.write_image(
    "chicago_5day_forecast.png",
    width=1200,
    height=600,
    scale=2 #increase resolution
)

# Air quality part B - Free Exploration


> **Objective:** Gain hands-on experience in using the OpenAQ API to analyze air quality data and create meaningful visualizations.

For Part B your task is to complete a much more open-ended activity using a different API (https://openaq.org/).

While you can take this activity in the direction of your choosing, here are some general steps for you to follow:

* Spend some time familiarizing yourself with the OpenAQ interface and documentation (hint: go to `Developers`)

* Explore the various endpoints and develop a few questions that will help drive your analysis

* **Extract** the data needed to complete your analysis

* **Analyze** the data you have obtained, draw conclusions, and try to answer the questions you formulated earlier

* **Visualize** the data

* **Export** the data to a CSV


**Note: some things to bear in mind:**

* It's good practice to include comments in your code to explain your thought process and any challenges you encountered
* It's a good idea to use the `time` library to "sleep" a second or so between calls, to avoid going over the rate limit
* Sometimes the API returns a server error. You may want to code your solution to ignore these instances

### <font color='green'> **OPENAQ API DOCUMENTATION**</font>

**VERSION: OpenAQ API version 3** </br>

https://docs.openaq.org/about/about </br>
https://docs.openaq.org/using-the-api/quick-start </br>
https://docs.openaq.org/examples/examples </br>

**UNDER RESOURCES:** </br>

https://docs.openaq.org/resources/countries </br>
https://docs.openaq.org/resources/measurements </br>
https://docs.openaq.org/resources/sensors </br>

### <font color='green'>**WHEN IS AIR POLLUTION WORST DURING THE DAY IN DELHI, INDIA?**</font>

**Why Delhi, India?** <br>
Delhi was selected for this analysis due to its historically high PM2.5 pollution levels and strong hourly pollution patterns caused by urban activity and traffic congestion. <br>
The city also has extensive air quality monitoring coverage in OpenAQ, providing reliable and complete data for analysis.  <br>
These factors made Delhi suitable for identifying and visualizing daily pollution trends.

**What is PM2.5?**
- PM2.5 refers to fine particulate matter that is 2.5 micrometers or smaller in diameter. <br>
It is about 30 times smaller than the width of a human hair. <br>
And because it is so tiny, it can travel deep into the lungs, enter the bloodstream and affect multiple organs in the body.<br>

- PM2.5 is commonly produced by vehicle emissions, industrial activity, burning of fossil fuels, construction dust, wildfires, household fuel burning. <br>

**Why PM2.5?** <br>
- PM2.5 is selected for this analysis because it is one of the most harmful and widely monitored air pollutants. <br>
Due to its fine particle size, it can penetrate deep into the lungs and negatively impact human health. <br> 

- PM2.5 also reflects urban activity patterns clearly, making it suitable for analyzing how daily commuting behavior affects air quality.<br>

**Why is PM2.5 important?** <br>
- PM2.5 is considered one of the most harmful air pollutants because prolonged exposure is linked to:
    * respiratory diseases
    * asthma
    * cardiovascular diseases
    * lung cancer
    * premature death

**STEP 1: Import required libraries and account key. Identity endpoint & sensor_id.**

In [418]:
import requests
import pandas as pd
import plotly.express as px
import time

#Refresh Jupyter cache. Prevents use of old or previous imports / caches.
import importlib
import config

importlib.reload(config)

# Account Key is stored in a config file
from config import AIRQUALITY_API_KEY

url = 'https://api.openaq.org/v3'
sensor_id = 23534

**STEP 2: Call the API and do Error Handling.**

In [419]:
# 1. AUTHENTICATION HEADER
# Header that will be passed to the OpenAQ API

headers = {
    'X-API-Key': AIRQUALITY_API_KEY
}

# 2. API ENDPOINT & QUERY PARAMETERS TO GET THE MEASUREMENTS AGGREGATED FROM HOUR TO DAY OF WEEK BY SENSOR ID
# From the Sensors Resources:
# API Endpoint using the sensor_id

# From the Measurements Resources:
# hourofday: The hourofday aggregator returns the average (mean) value for each hour in a 24 hour day, across the selected time range. 
# This allows analyzing air quality trends on an hourly basis, offering insights into daily patterns and peak pollution times, such as diurnal patterns.

url = f"{url}/sensors/{sensor_id}/hours/hourofday"

# These parameters define the scope of the API request:
# a. datetime_from / datetime_to: filters data to April 2026
# b. limit: maximum number of records returned (up to 1000)

params = {
    'datetime_from': '2026-04-01',
    'datetime_to': '2026-04-30',
    'limit': 1000
}

# 3. API REQUEST + ERROR HANDLING
# This calls the API via requests and safely handles possible errors.

try:
    # Send GET request to OpenAQ API with headers and parameters
    response = requests.get(url, headers=headers, params=params)

    # Pause briefly to avoid hitting API rate limits
    time.sleep(1)

    # Raise an error if the response status is not successful
    response.raise_for_status()

    # Parse JSON response and extract the 'results' data
    data = response.json()['results']

# 4. HANDLE HTTP ERRORS
# Catches API-related errors (e.g., 401, 404, 408, 429)

except requests.exceptions.HTTPError as e:
    print("HTTP error:", response.status_code, response.text)
    data = [] # reset to empty dataset

# 5. HANDLE OTHER ERRORS
# Catches unexpected errors (e.g., connection issues, parsing errors)

except Exception as e:
    print("Other error:", e)
    data = [] # reset to empty dataset

In [421]:
data

[{'value': 67.3,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '00',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T12:30:00Z',
    'local': '2026-04-01T18:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T13:30:00Z',
    'local': '2026-04-29T19:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 12.0,
   'q02': 16.32,
   'q25': 34.75,
   'median': 61.5,
   'q75': 99.25,
   'q98': 126.60000000000001,
   'max': 132.0,
   'avg': 67.32142857142857,
   'sd': 34.912646091965826},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-03-31T18:30:00Z',
    'local': '2026-04-01T00:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T19:30:00Z',
    'local': '2026-04-28T01:00:00+05:30'}}},
 {'value': 69.5,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '01',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T13:30:00Z',
    'local': '2026-04-01T19:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T14:30:00Z',
    'local': '2026-04-29T20:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 21.0,
   'q02': 23.16,
   'q25': 39.25,
   'median': 62.5,
   'q75': 97.25,
   'q98': 134.82000000000002,
   'max': 144.0,
   'avg': 69.5,
   'sd': 35.77139349525809},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-03-31T19:30:00Z',
    'local': '2026-04-01T01:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T20:30:00Z',
    'local': '2026-04-28T02:00:00+05:30'}}},
 {'value': 69.9,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '02',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T14:30:00Z',
    'local': '2026-04-01T20:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T15:30:00Z',
    'local': '2026-04-29T21:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 21.0,
   'q02': 21.54,
   'q25': 42.5,
   'median': 55.5,
   'q75': 93.75,
   'q98': 152.66000000000003,
   'max': 164.0,
   'avg': 69.92857142857143,
   'sd': 38.63114131584879},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-03-31T20:30:00Z',
    'local': '2026-04-01T02:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T21:30:00Z',
    'local': '2026-04-28T03:00:00+05:30'}}},
 {'value': 75.6,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '03',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T15:30:00Z',
    'local': '2026-04-01T21:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T16:30:00Z',
    'local': '2026-04-29T22:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 22.0,
   'q02': 24.7,
   'q25': 44.5,
   'median': 59.0,
   'q75': 93.5,
   'q98': 208.98000000000002,
   'max': 216.0,
   'avg': 75.57142857142857,
   'sd': 49.36292548764116},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-03-31T21:30:00Z',
    'local': '2026-04-01T03:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T22:30:00Z',
    'local': '2026-04-28T04:00:00+05:30'}}},
 {'value': 77.8,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '04',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T16:30:00Z',
    'local': '2026-04-01T22:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T17:30:00Z',
    'local': '2026-04-29T23:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 15.0,
   'q02': 21.48,
   'q25': 46.75,
   'median': 60.5,
   'q75': 107.25,
   'q98': 188.34000000000003,
   'max': 204.0,
   'avg': 77.82142857142857,
   'sd': 47.28640362994386},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-03-31T22:30:00Z',
    'local': '2026-04-01T04:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T23:30:00Z',
    'local': '2026-04-28T05:00:00+05:30'}}},
 {'value': 84.1,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '05',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T17:30:00Z',
    'local': '2026-04-01T23:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T18:30:00Z',
    'local': '2026-04-30T00:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 15.0,
   'q02': 21.240000000000002,
   'q25': 47.0,
   'median': 69.0,
   'q75': 132.0,
   'q98': 190.36,
   'max': 194.0,
   'avg': 84.11111111111111,
   'sd': 50.98969227156326},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 27,
   'observedInterval': '27:00:00',
   'percentComplete': 93.0,
   'percentCoverage': 93.0,
   'datetimeFrom': {'utc': '2026-03-31T23:30:00Z',
    'local': '2026-04-01T05:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T00:30:00Z',
    'local': '2026-04-28T06:00:00+05:30'}}},
 {'value': 95.4,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '06',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-03-31T18:30:00Z',
    'local': '2026-04-01T00:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T19:30:00Z',
    'local': '2026-04-29T01:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 14.0,
   'q02': 17.240000000000002,
   'q25': 49.0,
   'median': 75.0,
   'q75': 132.5,
   'q98': 221.28000000000006,
   'max': 258.0,
   'avg': 95.35714285714286,
   'sd': 59.940843853792735},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T00:30:00Z',
    'local': '2026-04-01T06:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T01:30:00Z',
    'local': '2026-04-28T07:00:00+05:30'}}},
 {'value': 117.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '07',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-03-31T19:30:00Z',
    'local': '2026-04-01T01:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T20:30:00Z',
    'local': '2026-04-29T02:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 14.0,
   'q02': 22.64,
   'q25': 67.75,
   'median': 104.5,
   'q75': 157.25,
   'q98': 222.18000000000004,
   'max': 240.0,
   'avg': 117.14285714285714,
   'sd': 61.817361989866924},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T01:30:00Z',
    'local': '2026-04-01T07:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T02:30:00Z',
    'local': '2026-04-28T08:00:00+05:30'}}},
 {'value': 108.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '08',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-03-31T20:30:00Z',
    'local': '2026-04-01T02:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T21:30:00Z',
    'local': '2026-04-29T03:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 19.0,
   'q02': 26.02,
   'q25': 67.5,
   'median': 103.5,
   'q75': 140.25,
   'q98': 217.02000000000004,
   'max': 237.0,
   'avg': 108.25,
   'sd': 53.320571389786636},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T02:30:00Z',
    'local': '2026-04-01T08:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T03:30:00Z',
    'local': '2026-04-28T09:00:00+05:30'}}},
 {'value': 89.1,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '09',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-03-31T21:30:00Z',
    'local': '2026-04-01T03:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T22:30:00Z',
    'local': '2026-04-29T04:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 27.0,
   'q02': 30.78,
   'q25': 62.5,
   'median': 87.0,
   'q75': 109.5,
   'q98': 182.70000000000005,
   'max': 207.0,
   'avg': 89.07142857142857,
   'sd': 41.93374719052846},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T03:30:00Z',
    'local': '2026-04-01T09:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T04:30:00Z',
    'local': '2026-04-28T10:00:00+05:30'}}},
 {'value': 62.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '10',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-03-31T22:30:00Z',
    'local': '2026-04-01T04:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T23:30:00Z',
    'local': '2026-04-29T05:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 21.0,
   'q02': 23.16,
   'q25': 46.5,
   'median': 59.5,
   'q75': 73.0,
   'q98': 132.64000000000007,
   'max': 178.0,
   'avg': 62.0,
   'sd': 30.678741584119532},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T04:30:00Z',
    'local': '2026-04-01T10:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T05:30:00Z',
    'local': '2026-04-28T11:00:00+05:30'}}},
 {'value': 46.9,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '11',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-03-31T23:30:00Z',
    'local': '2026-04-01T05:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T00:30:00Z',
    'local': '2026-04-29T06:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 17.0,
   'q02': 18.62,
   'q25': 33.75,
   'median': 43.5,
   'q75': 56.0,
   'q98': 99.34000000000003,
   'max': 115.0,
   'avg': 46.857142857142854,
   'sd': 21.36753211232941},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T05:30:00Z',
    'local': '2026-04-01T11:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T06:30:00Z',
    'local': '2026-04-28T12:00:00+05:30'}}},
 {'value': 44.1,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '12',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T00:30:00Z',
    'local': '2026-04-01T06:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T01:30:00Z',
    'local': '2026-04-29T07:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 18.0,
   'q02': 18.0,
   'q25': 28.75,
   'median': 35.0,
   'q75': 47.0,
   'q98': 130.74,
   'max': 141.0,
   'avg': 44.142857142857146,
   'sd': 29.60069354256853},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T06:30:00Z',
    'local': '2026-04-01T12:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T07:30:00Z',
    'local': '2026-04-28T13:00:00+05:30'}}},
 {'value': 35.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '13',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T01:30:00Z',
    'local': '2026-04-01T07:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T02:30:00Z',
    'local': '2026-04-29T08:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 12.0,
   'q02': 12.54,
   'q25': 25.0,
   'median': 28.5,
   'q75': 37.0,
   'q98': 104.28000000000006,
   'max': 141.0,
   'avg': 35.0,
   'sd': 24.233432675938822},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 28,
   'observedInterval': '28:00:00',
   'percentComplete': 97.0,
   'percentCoverage': 97.0,
   'datetimeFrom': {'utc': '2026-04-01T07:30:00Z',
    'local': '2026-04-01T13:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-28T08:30:00Z',
    'local': '2026-04-28T14:00:00+05:30'}}},
 {'value': 29.5,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '14',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T02:30:00Z',
    'local': '2026-04-01T08:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T03:30:00Z',
    'local': '2026-04-29T09:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 14.0,
   'q02': 16.0,
   'q25': 22.0,
   'median': 27.5,
   'q75': 33.75,
   'q98': 52.5,
   'max': 57.0,
   'avg': 29.53846153846154,
   'sd': 10.64041641753092},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 26,
   'observedInterval': '26:00:00',
   'percentComplete': 90.0,
   'percentCoverage': 90.0,
   'datetimeFrom': {'utc': '2026-04-01T08:30:00Z',
    'local': '2026-04-01T14:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T09:30:00Z',
    'local': '2026-04-27T15:00:00+05:30'}}},
 {'value': 28.0,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '15',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T03:30:00Z',
    'local': '2026-04-01T09:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T04:30:00Z',
    'local': '2026-04-29T10:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 8.0,
   'q02': 11.64,
   'q25': 21.0,
   'median': 26.0,
   'q75': 33.0,
   'q98': 53.36,
   'max': 57.0,
   'avg': 28.037037037037038,
   'sd': 11.31534520185032},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 27,
   'observedInterval': '27:00:00',
   'percentComplete': 93.0,
   'percentCoverage': 93.0,
   'datetimeFrom': {'utc': '2026-04-01T09:30:00Z',
    'local': '2026-04-01T15:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T10:30:00Z',
    'local': '2026-04-27T16:00:00+05:30'}}},
 {'value': 29.7,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '16',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T04:30:00Z',
    'local': '2026-04-01T10:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T05:30:00Z',
    'local': '2026-04-29T11:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 8.0,
   'q02': 10.6,
   'q25': 22.5,
   'median': 25.0,
   'q75': 35.5,
   'q98': 65.88000000000001,
   'max': 82.0,
   'avg': 29.74074074074074,
   'sd': 15.403777240545686},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 27,
   'observedInterval': '27:00:00',
   'percentComplete': 93.0,
   'percentCoverage': 93.0,
   'datetimeFrom': {'utc': '2026-04-01T10:30:00Z',
    'local': '2026-04-01T16:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T11:30:00Z',
    'local': '2026-04-27T17:00:00+05:30'}}},
 {'value': 30.8,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '17',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T05:30:00Z',
    'local': '2026-04-01T11:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T06:30:00Z',
    'local': '2026-04-29T12:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 15.0,
   'q02': 16.04,
   'q25': 22.5,
   'median': 27.0,
   'q75': 38.0,
   'q98': 54.400000000000006,
   'max': 57.0,
   'avg': 30.77777777777778,
   'sd': 11.416362526362471},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 27,
   'observedInterval': '27:00:00',
   'percentComplete': 93.0,
   'percentCoverage': 93.0,
   'datetimeFrom': {'utc': '2026-04-01T11:30:00Z',
    'local': '2026-04-01T17:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T12:30:00Z',
    'local': '2026-04-27T18:00:00+05:30'}}},
 {'value': 33.9,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '18',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T06:30:00Z',
    'local': '2026-04-01T12:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T07:30:00Z',
    'local': '2026-04-29T13:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 16.0,
   'q02': 17.56,
   'q25': 25.5,
   'median': 32.0,
   'q75': 40.5,
   'q98': 57.92,
   'max': 60.0,
   'avg': 33.925925925925924,
   'sd': 11.29644575119478},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 27,
   'observedInterval': '27:00:00',
   'percentComplete': 93.0,
   'percentCoverage': 93.0,
   'datetimeFrom': {'utc': '2026-04-01T12:30:00Z',
    'local': '2026-04-01T18:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T13:30:00Z',
    'local': '2026-04-27T19:00:00+05:30'}}},
 {'value': 42.6,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '19',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T07:30:00Z',
    'local': '2026-04-01T13:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T08:30:00Z',
    'local': '2026-04-29T14:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 20.0,
   'q02': 25.2,
   'q25': 34.5,
   'median': 39.0,
   'q75': 51.5,
   'q98': 69.48,
   'max': 70.0,
   'avg': 42.55555555555556,
   'sd': 11.820234715010896},
  'coverage': {'expectedCount': 29,
   'expectedInterval': '29:00:00',
   'observedCount': 27,
   'observedInterval': '27:00:00',
   'percentComplete': 93.0,
   'percentCoverage': 93.0,
   'datetimeFrom': {'utc': '2026-04-01T13:30:00Z',
    'local': '2026-04-01T19:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-27T14:30:00Z',
    'local': '2026-04-27T20:00:00+05:30'}}},
 {'value': 55.4,
  'flagInfo': {'hasFlags': False},
  'parameter': {'id': 2,
   'name': 'pm25',
   'units': 'µg/m³',
   'displayName': None},
  'period': {'label': '20',
   'interval': 'hour',
   'datetimeFrom': {'utc': '2026-04-01T08:30:00Z',
    'local': '2026-04-01T14:00:00+05:30'},
   'datetimeTo': {'utc': '2026-04-29T09:30:00Z',
    'local': '2026-04-29T15:00:00+05:30'}},
  'coordinates': None,
  'summary': {'min': 22.0,
   'q02': 28.240000000000002,
   'q25': 44.5,
   'median': 54.0,
   'q75': 60.0,

**STEP 3: Extract the data, save in a Dataframe and analyze data.**

In [424]:
# 1. INITIALIZE EMPTY LIST
# Create an empty list to store cleaned and structured records.
# Each record will represent one hour's average PM2.5 value.

hour_data = []

# 2. TRANSFORM RAW API DATA
# Loop through each item in the API response ('data')
# and extract only the relevant fields needed for analysis.

for item in data:
    hour_data.append({
         # Extract the hour (0–23) from the 'period' label and convert to integer
        "hour": int(item["period"]["label"]),

        # Extract the average PM2.5 value for that hour
        "pm25_value": item["value"],

        # Extract the unit of measurement (µg/m³: micrograms per cubic meter)
        "unit": item["parameter"]["units"]
    })

# 3. CREATE DATAFRAME + SORT
# Convert the list of dictionaries into a pandas DataFrame
# and sort it by hour to ensure proper chronological order for plotting.

air_quality_df = pd.DataFrame(hour_data).sort_values("hour")
air_quality_df

    hour  pm25_value   unit
0      0       67.30  µg/m³
1      1       69.50  µg/m³
2      2       69.90  µg/m³
3      3       75.60  µg/m³
4      4       77.80  µg/m³
5      5       84.10  µg/m³
6      6       95.40  µg/m³
7      7      117.00  µg/m³
8      8      108.00  µg/m³
9      9       89.10  µg/m³
10    10       62.00  µg/m³
11    11       46.90  µg/m³
12    12       44.10  µg/m³
13    13       35.00  µg/m³
14    14       29.50  µg/m³
15    15       28.00  µg/m³
16    16       29.70  µg/m³
17    17       30.80  µg/m³
18    18       33.90  µg/m³
19    19       42.60  µg/m³
20    20       55.40  µg/m³
21    21       60.00  µg/m³
22    22       64.00  µg/m³
23    23       64.70  µg/m³

In [425]:
hour_data

[{'hour': 0, 'pm25_value': 67.3, 'unit': 'µg/m³'},
 {'hour': 1, 'pm25_value': 69.5, 'unit': 'µg/m³'},
 {'hour': 2, 'pm25_value': 69.9, 'unit': 'µg/m³'},
 {'hour': 3, 'pm25_value': 75.6, 'unit': 'µg/m³'},
 {'hour': 4, 'pm25_value': 77.8, 'unit': 'µg/m³'},
 {'hour': 5, 'pm25_value': 84.1, 'unit': 'µg/m³'},
 {'hour': 6, 'pm25_value': 95.4, 'unit': 'µg/m³'},
 {'hour': 7, 'pm25_value': 117.0, 'unit': 'µg/m³'},
 {'hour': 8, 'pm25_value': 108.0, 'unit': 'µg/m³'},
 {'hour': 9, 'pm25_value': 89.1, 'unit': 'µg/m³'},
 {'hour': 10, 'pm25_value': 62.0, 'unit': 'µg/m³'},
 {'hour': 11, 'pm25_value': 46.9, 'unit': 'µg/m³'},
 {'hour': 12, 'pm25_value': 44.1, 'unit': 'µg/m³'},
 {'hour': 13, 'pm25_value': 35.0, 'unit': 'µg/m³'},
 {'hour': 14, 'pm25_value': 29.5, 'unit': 'µg/m³'},
 {'hour': 15, 'pm25_value': 28.0, 'unit': 'µg/m³'},
 {'hour': 16, 'pm25_value': 29.7, 'unit': 'µg/m³'},
 {'hour': 17, 'pm25_value': 30.8, 'unit': 'µg/m³'},
 {'hour': 18, 'pm25_value': 33.9, 'unit': 'µg/m³'},
 {'hour': 19, 'pm25_value': 42.6, 'unit': 'µg/m³'},
 {'hour': 20, 'pm25_value': 55.4, 'unit': 'µg/m³'},
 {'hour': 21, 'pm25_value': 60.0, 'unit': 'µg/m³'},
 {'hour': 22, 'pm25_value': 64.0, 'unit': 'µg/m³'},
 {'hour': 23, 'pm25_value': 64.7, 'unit': 'µg/m³'}]

**STEP 4: Visualize the data.**

In [426]:
# 1. IDENTIFY KEY DATA POINTS (PEAK & LOWEST)
# Find the hour with the highest PM2.5 value (peak pollution)
peak = air_quality_df.loc[air_quality_df["pm25_value"].idxmax()]

# Find the hour with the lowest PM2.5 value (cleanest air)
low = air_quality_df.loc[air_quality_df["pm25_value"].idxmin()]

# 2. DESIGN THE DATA VISUALIZATION
# Plot a LINE CHART showing PM2.5 levels across hours of the day
# Markers are added to highlight each data point
fig = px.line(
    air_quality_df,
    x="hour",
    y="pm25_value",
    markers=True,
    title="Rush Hour Pollution: When Delhi’s Air Is Most Dangerous<br>"
          "<sup>PM2.5 levels peak during commuting hours, showing the impact of daily urban activity (April 2026)</sup>"
)

# 3. ADD ANNOTATION FOR POLLUTION PEAK HOURS
# Highlight the hour with the highest PM2.5 level
fig.add_annotation(
    x=peak["hour"],
    y=peak["pm25_value"],
    text=f"<b>Peak: {peak['hour']}h</b>",
    showarrow=False,
    yshift=-20,     # move UP
    xshift=10      # move RIGHT
)

# 4. ADD ANNOTATION FOR LOWEST POLLUTION
# Highlight the hour with the lowest PM2.5 level
fig.add_annotation(
    x=low["hour"],
    y=low["pm25_value"],
    text=f"<b>Lowest: {low['hour']}h</b>",
    showarrow=True,
    arrowhead=2
)

# 5. IMPROVE LAYOUT AND STYLING
# Enhance readability and presentation quality
fig.update_layout(
    # Centered title with styled subtitle
    template="plotly_white",

    # Set font style for entire chart
    font=dict(
        family="Helvetica",
        size=14,
        color="black"
    ),

    # Axis labels
    xaxis_title="Hour of Day",
    yaxis_title="Average PM2.5 (µg/m³)", 

    # Axis formatting
    xaxis=dict(showgrid=False, tickmode='linear'),
    yaxis=dict(showgrid=True, gridcolor="lightgray"),

    # Centered title with styled subtitle
    title={
        'text': "<b>RUSH HOUR POLLUTION: When Delhi's Air Is Most Dangerous</b><br>"
                "<span style='font-size:12px;' >PM2.5 peaks during commuting hours, highlighting the impact of daily urban activity (April 2026)</span>",
        'x': 0.5,
        'xanchor': 'center'
    }
)

# 6. ENHANCE LINE AND MARKER STYLING
# Smooth the line and improve visual emphasis
fig.update_traces(
    line_shape="spline",    # Smooth curves
    line=dict(width=2),     # Thicker line for emphasis
    marker=dict(size=8)     # Larger markers for visibility
)

# 7. ADD VISUAL HIGHLIGHT REGIONS (VRECT)
# Highlight morning peak period (commuting hours)
fig.add_vrect(
    x0=6, x1=9,
    fillcolor="red", opacity=0.1,
    line_width=0,
    annotation_text="<b>Morning Peak</b>",
    annotation_position="top left"
)

# Highlight evening rise period (commuting hours)
fig.add_vrect(
    x0=18, x1=21,
    fillcolor="orange", opacity=0.1,
    line_width=0,
    annotation_text="<b>Evening Rise</b>",
    annotation_position="top left"
)

# 8. DISPLAY THE DATA VISUALIZATION
fig.show()

**STEP 5: Output the data and graph.**

In [429]:
# Output dataset to csv file

air_quality_df.to_csv(f"sensor_id_{sensor_id}_delhi_pm25_Apr2026.csv", index=False)

fig.write_image(
    f"sensor_id_{sensor_id}_delhi_pm25_Apr2026.png",
    width=1400,
    height=800,
    scale=2
)