<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px"> 

#  APIs for financial data - Solutions

---

<br>
For both parts of this lab we will use Python to interact with the Alpha Vantage API and export data from different endpoints to answer two research questions.

# Part 1: GDP and Consumer Sentiment during the pandemic

You have been tasked with analysing how various economic indicators have behaved during the last few years. Your team has already identified a free source of this data: Alpha Vantage (https://www.alphavantage.co). It is now up to you to extract the relevant data about these indicators and write a short report about your findings.

***Note: be sure to sign up for a free API key at https://www.alphavantage.co/support/#api-key (more detailed instructions are in the instruction document for this lab)***

**0. Imports**
Put all Python imports in the cell below. If you later decide you need to import something, you must put it here and re-run!

In [42]:
import requests
import pandas as pd
import plotly.express as px
import time

#Refresh Jupyter cache. Prevents use of old or previous imports / caches.
import importlib
import config

importlib.reload(config)

from pathlib import Path

# Account Key is stored in a config file
from config import ALPHAVANTAGE_API_KEY

# Create Output Folder
output_folder = Path("API_Output_CSV")
output_folder.mkdir(exist_ok=True)

**1. Find the correct API endpoint to retrieve historical data on GDP**

Define a variable `base_url` that is a **string** that is simply the base portion of the Alpha Vantage URL endpoint. That is, if you look at any API call, this is everything before the question mark.

Next, define another variable `API_KEY` that is a **string** and is your Alpha Vantage API key (make one, they're free and you don't need to give a real email!)

Use the [Documentation](https://www.alphavantage.co/documentation/) to help you.

In [43]:
# STEP 1. DEFINE URL + PARAMETERS

# API endpoint
base_url = 'https://www.alphavantage.co/query'

# Parameters
params = {
    'function': 'REAL_GDP',
    'interval': 'quarterly',
    'datatype': 'json',             #returns the time series in JSON format
    'apikey': ALPHAVANTAGE_API_KEY
}

**2. Use Python and the `requests` library to make an API call and retrieve historical GDP data at *the highest level of granularity* (i.e. most frequent that the API allows). Remember to add your own API key to the query.**

You should convert the results to JSON so it behaves like a Python dictionary.

In [44]:
# STEP 2. API REQUEST + ERROR HANDLING

# 1. Calls the API via requests and safely handles possible errors

try:
    # Send GET request to API with headers and parameters
    response = requests.get(base_url, params=params)

    # Pause briefly to avoid hitting API rate limits
    time.sleep(1)

    # Raise an error if the response status is not successful
    response.raise_for_status()

    # Parse JSON response and convert to Python dictionary
    real_gdp_quarterly = response.json()

# 2. Handles HTTP errors 
# Catches API-related errors (e.g., 401, 404, 408, 429)

except requests.exceptions.HTTPError as e:
    print("HTTP error:", response.status_code, response.text)
    real_gdp_quarterly = [] # reset to empty dataset

# 3. Handles other errors 
# Catches unexpected errors (e.g., connection issues, parsing errors)

except Exception as e:
    print("Other error:", e)
    real_gdp_quarterly = [] # reset to empty dataset

In [45]:
real_gdp_quarterly

{'name': 'Real Gross Domestic Product',
 'interval': 'quarterly',
 'unit': 'billions of dollars',
 'data': [{'date': '2026-01-01', 'value': '5900.814'},
  {'date': '2025-10-01', 'value': '6119.385'},
  {'date': '2025-07-01', 'value': '6023.785'},
  {'date': '2025-04-01', 'value': '5943.384'},
  {'date': '2025-01-01', 'value': '5776.724'},
  {'date': '2024-10-01', 'value': '5997.184'},
  {'date': '2024-07-01', 'value': '5884.567'},
  {'date': '2024-04-01', 'value': '5829.384'},
  {'date': '2024-01-01', 'value': '5647.3'},
  {'date': '2023-10-01', 'value': '5847.063'},
  {'date': '2023-07-01', 'value': '5731.929'},
  {'date': '2023-04-01', 'value': '5655.781'},
  {'date': '2023-01-01', 'value': '5488.947'},
  {'date': '2022-10-01', 'value': '5670.022'},
  {'date': '2022-07-01', 'value': '5556.056'},
  {'date': '2022-04-01', 'value': '5495.481'},
  {'date': '2022-01-01', 'value': '5354.373'},
  {'date': '2021-10-01', 'value': '5600.549'},
  {'date': '2021-07-01', 'value': '5418.754'},
  {'date': '2021-04-01', 'value': '5368.017'},
  {'date': '2021-01-01', 'value': '5145.087'},
  {'date': '2020-10-01', 'value': '5303.186'},
  {'date': '2020-07-01', 'value': '5145.053'},
  {'date': '2020-04-01', 'value': '4780.549'},
  {'date': '2020-01-01', 'value': '5055.712'},
  {'date': '2019-10-01', 'value': '5351.022'},
  {'date': '2019-07-01', 'value': '5232.278'},
  {'date': '2019-04-01', 'value': '5159.323'},
  {'date': '2019-01-01', 'value': '4973.048'},
  {'date': '2018-10-01', 'value': '5170.563'},
  {'date': '2018-07-01', 'value': '5092.532'},
  {'date': '2018-04-01', 'value': '5039.983'},
  {'date': '2018-01-01', 'value': '4890.817'},
  {'date': '2017-10-01', 'value': '5069.624'},
  {'date': '2017-07-01', 'value': '4950.878'},
  {'date': '2017-04-01', 'value': '4893.234'},
  {'date': '2017-01-01', 'value': '4698.367'},
  {'date': '2016-10-01', 'value': '4912.331'},
  {'date': '2016-07-01', 'value': '4819.182'},
  {'date': '2016-04-01', 'value': '4768.308'},
  {'date': '2016-01-01', 'value': '4641.851'},
  {'date': '2015-10-01', 'value': '4799.354'},
  {'date': '2015-07-01', 'value': '4741.07'},
  {'date': '2015-04-01', 'value': '4696.817'},
  {'date': '2015-01-01', 'value': '4562.381'},
  {'date': '2014-10-01', 'value': '4709.584'},
  {'date': '2014-07-01', 'value': '4616.61'},
  {'date': '2014-04-01', 'value': '4532.342'},
  {'date': '2014-01-01', 'value': '4403.178'},
  {'date': '2013-10-01', 'value': '4586.321'},
  {'date': '2013-07-01', 'value': '4486.445'},
  {'date': '2013-04-01', 'value': '4419.14'},
  {'date': '2013-01-01', 'value': '4320.262'},
  {'date': '2012-10-01', 'value': '4440.555'},
  {'date': '2012-07-01', 'value': '4376.682'},
  {'date': '2012-04-01', 'value': '4345.706'},
  {'date': '2012-01-01', 'value': '4279.816'},
  {'date': '2011-10-01', 'value': '4371.813'},
  {'date': '2011-07-01', 'value': '4273.162'},
  {'date': '2011-04-01', 'value': '4251.8'},
  {'date': '2011-01-01', 'value': '4155.635'},
  {'date': '2010-10-01', 'value': '4316.573'},
  {'date': '2010-07-01', 'value': '4229.41'},
  {'date': '2010-04-01', 'value': '4188.706'},
  {'date': '2010-01-01', 'value': '4055.062'},
  {'date': '2009-10-01', 'value': '4209.064'},
  {'date': '2009-07-01', 'value': '4102.854'},
  {'date': '2009-04-01', 'value': '4060.384'},
  {'date': '2009-01-01', 'value': '3976.808'},
  {'date': '2008-10-01', 'value': '4179.959'},
  {'date': '2008-07-01', 'value': '4192.399'},
  {'date': '2008-04-01', 'value': '4226.589'},
  {'date': '2008-01-01', 'value': '4182.537'},
  {'date': '2007-10-01', 'value': '4305.666'},
  {'date': '2007-07-01', 'value': '4208.612'},
  {'date': '2007-04-01', 'value': '4184.414'},
  {'date': '2007-01-01', 'value': '4063.753'},
  {'date': '2006-10-01', 'value': '4201.0'},
  {'date': '2006-07-01', 'value': '4111.947'},
  {'date': '2006-04-01', 'value': '4116.718'},
  {'date': '2006-01-01', 'value': '4003.482'},
  {'date': '2005-10-01', 'value': '4107.378'},
  {'date': '2005-07-01', 'value': '4040.686'},
  {'date': '2005-04-01', 'value': '3972.818'},
  {'date': '2005-01-01', 'value': '3867.076'},
  {'date': '2004-10-01', 'value': '3990.913'},
  {'date': '2004-07-01', 'value': '3879.617'},
  {'date': '2004-04-01', 'value': '3837.587'},
  {'date': '2004-01-01', 'value': '3741.64'},
  {'date': '2003-10-01', 'value': '3860.185'},
  {'date': '2003-07-01', 'value': '3753.431'},
  {'date': '2003-04-01', 'value': '3680.929'},
  {'date': '2003-01-01', 'value': '3582.767'},
  {'date': '2002-10-01', 'value': '3712.845'},
  {'date': '2002-07-01', 'value': '3650.253'},
  {'date': '2002-04-01', 'value': '3608.496'},
  {'date': '2002-01-01', 'value': '3501.118'}]}

**3. Convert the data in this JSON to a Pandas dataframe and export to a csv.**

In [46]:
# STEP 3. CONVERT DATA IN JSON TO PANDAS DATAFRAME + DATA WRANGLING + COMPUTE DERIVED FIELDS + EXPORT TO A CSV FILE

# 1. Extract the 'data' portion and convert to a DataFrame

real_gdp_quarterly_df = pd.DataFrame(real_gdp_quarterly['data'])
real_gdp_quarterly_df

# 2. Convert data types

real_gdp_quarterly_df['date'] = pd.to_datetime(real_gdp_quarterly_df['date'])
real_gdp_quarterly_df['value'] = real_gdp_quarterly_df['value'].astype(float)

# 3. Sort date by ascending order and resets the order of the index 
# This is important for time series analysis

real_gdp_quarterly_df = real_gdp_quarterly_df.sort_values('date').reset_index(drop=True)

# 4. Compute the Derived fields

    # A. Quarterly Change
    # Measures the absolute change from previous quarter
    # Useful for identifying acceleration/slowing growth and recession analysis

real_gdp_quarterly_df['quarterly_change'] = (
    real_gdp_quarterly_df['value'].diff()
)

    # B. Quarterly Growth %
    # Useful for comparing economic growth periods and comparing GDP trends against VTI/VXX

real_gdp_quarterly_df['quarterly_growth_pct'] = (
    real_gdp_quarterly_df['value'].pct_change()
) * 100

    # C. Cumulative GDP Growth %
    # Good for long-term comparison
    # Useful for showing overall economic expansion

real_gdp_quarterly_df['cumulative_growth_pct'] = (
    (
        real_gdp_quarterly_df['value']
        / real_gdp_quarterly_df['value'].iloc[0]
    ) - 1
) * 100

    # D. 4-Quarter Moving Average
    # Smooths annual trend 

real_gdp_quarterly_df['moving_avg_4q'] = (
    real_gdp_quarterly_df['value']
    .rolling(4)
    .mean()
)

    # E. 8-Quarter Moving Average
    # Longer economic cycle trend

real_gdp_quarterly_df['moving_avg_8q'] = (
    real_gdp_quarterly_df['value']
    .rolling(8)
    .mean()
)

# 5. Add info from the Metadata

real_gdp_quarterly_df['name'] = real_gdp_quarterly['name']
real_gdp_quarterly_df['interval'] = real_gdp_quarterly['interval']
real_gdp_quarterly_df['unit'] = real_gdp_quarterly['unit']

# 6. Round numeric columns to 2 decimal places

numeric_columns = real_gdp_quarterly_df.select_dtypes(include='number').columns

real_gdp_quarterly_df[numeric_columns] = (
    real_gdp_quarterly_df[numeric_columns]
    .round(2)
)

# 7. View the data

real_gdp_quarterly_df

,date,value,quarterly_change,quarterly_growth_pct,cumulative_growth_pct,moving_avg_4q,moving_avg_8q,name,interval,unit
0,2002-01-01,3501.12,NaN,NaN,0.00,NaN,NaN,Real Gross Domestic Product,quarterly,billions of dollars
1,2002-04-01,3608.50,107.38,3.07,3.07,NaN,NaN,Real Gross Domestic Product,quarterly,billions of dollars
2,2002-07-01,3650.25,41.76,1.16,4.26,NaN,NaN,Real Gross Domestic Product,quarterly,billions of dollars
3,2002-10-01,3712.84,62.59,1.71,6.05,3618.18,NaN,Real Gross Domestic Product,quarterly,billions of dollars
4,2003-01-01,3582.77,-130.08,-3.50,2.33,3638.59,NaN,Real Gross Domestic Product,quarterly,billions of dollars
...,...,...,...,...,...,...,...,...,...,...
92,2025-01-01,5776.72,-220.46,-3.68,65.00,5871.96,5796.24,Real Gross Domestic Product,quarterly,billions of dollars
93,2025-04-01,5943.38,166.66,2.89,69.76,5900.46,5832.19,Real Gross Domestic Product,quarterly,billions of dollars
94,2025-07-01,6023.78,80.40,1.35,72.05,5935.27,5868.67,Real Gross Domestic Product,quarterly,billions of dollars
95,2025-10-01,6119.38,95.60,1.59,74.78,5965.82,5902.71,Real Gross Domestic Product,quarterly,billions of dollars
96,2026-01-01,5900.81,-218.57,-3.57,68.54,5996.84,5934.40,Real Gross Domestic Product,quarterly,billions of dollars

In [47]:
# 8. View dataframe: Check datatypes & count of rows
real_gdp_quarterly_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   97 non-null     datetime64[us]
 1   value                  97 non-null     float64
 2   quarterly_change       96 non-null     float64
 3   quarterly_growth_pct   96 non-null     float64
 4   cumulative_growth_pct  97 non-null     float64
 5   moving_avg_4q          94 non-null     float64
 6   moving_avg_8q          90 non-null     float64
 7   name                   97 non-null     str
 8   interval               97 non-null     str
 9   unit                   97 non-null     str
dtypes: datetime64[us](1), float64(6), str(3)
memory usage: 7.7 KB

In [48]:
# 9. Re-order columns
real_gdp_quarterly_df = real_gdp_quarterly_df[
    [
        'date',
        'name',
        'interval',
        'unit',
        'value',
        'quarterly_change',
        'quarterly_growth_pct',
        'cumulative_growth_pct',
        'moving_avg_4q',
        'moving_avg_8q'
    ]
]

real_gdp_quarterly_df

,date,name,interval,unit,value,quarterly_change,quarterly_growth_pct,cumulative_growth_pct,moving_avg_4q,moving_avg_8q
0,2002-01-01,Real Gross Domestic Product,quarterly,billions of dollars,3501.12,NaN,NaN,0.00,NaN,NaN
1,2002-04-01,Real Gross Domestic Product,quarterly,billions of dollars,3608.50,107.38,3.07,3.07,NaN,NaN
2,2002-07-01,Real Gross Domestic Product,quarterly,billions of dollars,3650.25,41.76,1.16,4.26,NaN,NaN
3,2002-10-01,Real Gross Domestic Product,quarterly,billions of dollars,3712.84,62.59,1.71,6.05,3618.18,NaN
4,2003-01-01,Real Gross Domestic Product,quarterly,billions of dollars,3582.77,-130.08,-3.50,2.33,3638.59,NaN
...,...,...,...,...,...,...,...,...,...,...
92,2025-01-01,Real Gross Domestic Product,quarterly,billions of dollars,5776.72,-220.46,-3.68,65.00,5871.96,5796.24
93,2025-04-01,Real Gross Domestic Product,quarterly,billions of dollars,5943.38,166.66,2.89,69.76,5900.46,5832.19
94,2025-07-01,Real Gross Domestic Product,quarterly,billions of dollars,6023.78,80.40,1.35,72.05,5935.27,5868.67
95,2025-10-01,Real Gross Domestic Product,quarterly,billions of dollars,6119.38,95.60,1.59,74.78,5965.82,5902.71
96,2026-01-01,Real Gross Domestic Product,quarterly,billions of dollars,5900.81,-218.57,-3.57,68.54,5996.84,5934.40

In [49]:
# 10. Export to CSV and save inside output folder
real_gdp_quarterly_df.to_csv(
    output_folder / "real_gdp_quarterly.csv",
    index=False
)

**4. Next, identify the endpoint for finding daily stock price values and query the VXX ticker.**

Make sure to get as much data as possible using the `outputsize` parameter at this endpoint.

VXX is a mutual fund that that adequately represents the [VIX](https://www.investopedia.com/articles/optioninvestor/09/implied-volatility-contrary-indicator.asp#:~:text=VIX%20measures%20the%20market%27s%20expectation%20of%20volatility%20over,trends%20in%20the%20VIX%20can%20inform%20trading%20strategies.) index that represents the fear and volatility in the market. When VIX (or VXX) is high, fear controls the market, and when VIX (or VXX) is low, people have more confidence in the market.

#### <font color='green'>**The Volatility Index: Reading Market Sentiment**</font><br>

Known ominously among investors as the "fear index" and launched by the Chicago Board Options Exchange (now the Cboe) in 1993, <br>
the Volatility Index (VIX) is meant to present the market's expectation of volatility over the coming 30 days.<br> 
The metric is derived from options prices on the S&P 500 Index and captures the anticipated swings that drive investor sentiment.<br>

A mantra investors learn early on is, "When the VIX is high, it's time to buy. When the VIX is low, look out below!"<br>

**Why is the VIX Sometimes Referred to as the "Fear Gauge"?**<br>
The VIX is sometimes called the "fear gauge" because it reflects market participants' anxiety about future market downturns.

**The Bottom Line**<br>
VIX measures the market's expectation of volatility over the next 30 days based on S&P 500 index options.<br> 
A higher VIX value indicates greater anticipated volatility and market uncertainty, while a lower VIX value suggests market stability.<br>
Key levels and trends in the VIX can inform trading strategies.

In [80]:
# STEP 1. DEFINE URL AND PARAMETERS

# API endpoint
base_url = 'https://www.alphavantage.co/query'

# Parameters
params = {
    'function': 'TIME_SERIES_WEEKLY',    # returns raw (as-traded) daily time series of the global equity specified
    'symbol': 'VXX',                    # the global equity specified: VXX is a mutual fund that that adequately represents the VIX
    'datatype': 'json',          # returns the daily time series in JSON format
    'apikey': ALPHAVANTAGE_API_KEY
}

In [81]:
# STEP 2. API REQUEST + ERROR HANDLING

# 1. Calls the API via requests and safely handles possible errors

try:
    # Send GET request to API with headers and parameters
    response = requests.get(base_url, params=params)

    # Pause briefly to avoid hitting API rate limits
    time.sleep(1)

    # Raise an error if the response status is not successful
    response.raise_for_status()

    # Parse JSON response and convert to Python dictionary
    time_series_weekly_vxx = response.json()

# 2. Handles HTTP errors 
# Catches API-related errors (e.g., 401, 404, 408, 429)

except requests.exceptions.HTTPError as e:
    print("HTTP error:", response.status_code, response.text)
    time_series_weekly_vxx = [] # reset to empty dataset

# 3. Handles other errors 
# Catches unexpected errors (e.g., connection issues, parsing errors)

except Exception as e:
    print("Other error:", e)
    time_series_weekly_vxx = [] # reset to empty dataset

**5. Cast the result as a dataframe and export it to a csv.**

In [82]:
time_series_weekly_vxx

{'Meta Data': {'1. Information': 'Weekly Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'VXX',
  '3. Last Refreshed': '2026-05-08',
  '4. Time Zone': 'US/Eastern'},
 'Weekly Time Series': {'2026-05-08': {'1. open': '28.3500',
   '2. high': '29.2400',
   '3. low': '27.5600',
   '4. close': '28.0600',
   '5. volume': '38682038'},
  '2026-05-01': {'1. open': '29.4800',
   '2. high': '29.6300',
   '3. low': '27.7700',
   '4. close': '28.4000',
   '5. volume': '29256666'},
  '2026-04-24': {'1. open': '29.2900',
   '2. high': '30.9450',
   '3. low': '29.0700',
   '4. close': '29.7900',
   '5. volume': '39941119'},
  '2026-04-17': {'1. open': '31.1600',
   '2. high': '31.3000',
   '3. low': '28.3700',
   '4. close': '28.9800',
   '5. volume': '35726903'},
  '2026-04-10': {'1. open': '34.8000',
   '2. high': '36.3300',
   '3. low': '30.0950',
   '4. close': '30.7700',
   '5. volume': '49587252'},
  '2026-04-02': {'1. open': '37.9100',
   '2. high': '39.9288',
   '3. low': '34.2107',
   '4. close': '34.7000',
   '5. volume': '62411359'},
  '2026-03-27': {'1. open': '33.5800',
   '2. high': '39.8000',
   '3. low': '32.7300',
   '4. close': '39.4100',
   '5. volume': '74462318'},
  '2026-03-20': {'1. open': '33.8000',
   '2. high': '36.7050',
   '3. low': '31.3950',
   '4. close': '35.9700',
   '5. volume': '78431596'},
  '2026-03-13': {'1. open': '36.1000',
   '2. high': '37.4300',
   '3. low': '30.7500',
   '4. close': '35.1000',
   '5. volume': '84540791'},
  '2026-03-06': {'1. open': '30.5900',
   '2. high': '35.7600',
   '3. low': '28.7200',
   '4. close': '35.6700',
   '5. volume': '90705744'},
  '2026-02-27': {'1. open': '28.4450',
   '2. high': '29.7450',
   '3. low': '27.2300',
   '4. close': '28.9000',
   '5. volume': '42646189'},
  '2026-02-20': {'1. open': '29.4800',
   '2. high': '30.2200',
   '3. low': '27.6300',
   '4. close': '28.3700',
   '5. volume': '48498890'},
  '2026-02-13': {'1. open': '27.5100',
   '2. high': '29.7500',
   '3. low': '26.4800',
   '4. close': '29.2500',
   '5. volume': '57127712'},
  '2026-02-06': {'1. open': '27.2300',
   '2. high': '29.7700',
   '3. low': '26.0100',
   '4. close': '27.6200',
   '5. volume': '63912896'},
  '2026-01-30': {'1. open': '26.4500',
   '2. high': '28.7709',
   '3. low': '26.1350',
   '4. close': '27.5000',
   '5. volume': '43871939'},
  '2026-01-23': {'1. open': '28.7300',
   '2. high': '29.8800',
   '3. low': '25.8400',
   '4. close': '26.5300',
   '5. volume': '64691924'},
  '2026-01-16': {'1. open': '26.3300',
   '2. high': '27.8500',
   '3. low': '25.6900',
   '4. close': '26.4200',
   '5. volume': '65896549'},
  '2026-01-09': {'1. open': '25.8500',
   '2. high': '26.6300',
   '3. low': '25.6350',
   '4. close': '25.7500',
   '5. volume': '33843811'},
  '2026-01-02': {'1. open': '27.2150',
   '2. high': '27.2300',
   '3. low': '25.9300',
   '4. close': '26.1000',
   '5. volume': '25850512'},
  '2025-12-26': {'1. open': '27.3800',
   '2. high': '27.4601',
   '3. low': '26.8750',
   '4. close': '26.9700',
   '5. volume': '24652042'},
  '2025-12-19': {'1. open': '29.2500',
   '2. high': '30.2400',
   '3. low': '27.8100',
   '4. close': '27.8600',
   '5. volume': '44076658'},
  '2025-12-12': {'1. open': '30.6400',
   '2. high': '31.5455',
   '3. low': '29.1100',
   '4. close': '29.5300',
   '5. volume': '37978882'},
  '2025-12-05': {'1. open': '32.8700',
   '2. high': '32.8700',
   '3. low': '30.6600',
   '4. close': '30.7200',
   '5. volume': '27959126'},
  '2025-11-28': {'1. open': '36.7900',
   '2. high': '36.8700',
   '3. low': '32.0700',
   '4. close': '32.1000',
   '5. volume': '31394909'},
  '2025-11-21': {'1. open': '35.2000',
   '2. high': '40.5200',
   '3. low': '34.0900',
   '4. close': '37.3200',
   '5. volume': '94759776'},
  '2025-11-14': {'1. open': '33.4200',
   '2. high': '36.7850',
   '3. low': '32.5000',
   '4. close': '34.5700',
   '5. volume': '43148105'},
  '2025-11-07': {'1. open': '33.5700',
   '2. high': '37.0700',
   '3. low': '33.1900',
   '4. close': '34.8100',
   '5. volume': '41829951'},
  '2025-10-31': {'1. open': '32.0300',
   '2. high': '34.6800',
   '3. low': '31.8400',
   '4. close': '34.0000',
   '5. volume': '32974508'},
  '2025-10-24': {'1. open': '35.8100',
   '2. high': '36.0300',
   '3. low': '32.5700',
   '4. close': '33.0800',
   '5. volume': '43872256'},
  '2025-10-17': {'1. open': '35.3600',
   '2. high': '40.8250',
   '3. low': '34.4100',
   '4. close': '36.9500',
   '5. volume': '81429565'},
  '2025-10-10': {'1. open': '33.0900',
   '2. high': '37.8700',
   '3. low': '32.8600',
   '4. close': '37.4700',
   '5. volume': '66327728'},
  '2025-10-03': {'1. open': '32.7200',
   '2. high': '33.7100',
   '3. low': '32.6800',
   '4. close': '33.2500',
   '5. volume': '28806414'},
  '2025-09-26': {'1. open': '33.5000',
   '2. high': '34.8684',
   '3. low': '32.8400',
   '4. close': '32.8400',
   '5. volume': '33121546'},
  '2025-09-19': {'1. open': '33.2800',
   '2. high': '34.6000',
   '3. low': '32.6350',
   '4. close': '33.1800',
   '5. volume': '32884608'},
  '2025-09-12': {'1. open': '35.1000',
   '2. high': '35.4150',
   '3. low': '33.2500',
   '4. close': '33.6800',
   '5. volume': '25982682'},
  '2025-09-05': {'1. open': '38.2100',
   '2. high': '38.9400',
   '3. low': '34.5000',
   '4. close': '35.4700',
   '5. volume': '38811307'},
  '2025-08-29': {'1. open': '36.3750',
   '2. high': '36.6200',
   '3. low': '35.2813',
   '4. close': '36.2700',
   '5. volume': '22650145'},
  '2025-08-22': {'1. open': '38.9700',
   '2. high': '40.0750',
   '3. low': '35.9700',
   '4. close': '35.9800',
   '5. volume': '44335992'},
  '2025-08-15': {'1. open': '40.6700',
   '2. high': '41.2300',
   '3. low': '38.6500',
   '4. close': '39.0400',
   '5. volume': '31182349'},
  '2025-08-08': {'1. open': '44.6300',
   '2. high': '44.7400',
   '3. low': '40.7500',
   '4. close': '40.8100',
   '5. volume': '26367404'},
  '2025-08-01': {'1. open': '41.4500',
   '2. high': '46.9700',
   '3. low': '40.4600',
   '4. close': '45.9100',
   '5. volume': '40524800'},
  '2025-07-25': {'1. open': '44.6400',
   '2. high': '45.7675',
   '3. low': '42.1600',
   '4. close': '42.3300',
   '5. volume': '22673510'},
  '2025-07-18': {'1. open': '45.6700',
   '2. high': '48.1000',
   '3. low': '44.8350',
   '4. close': '45.0100',
   '5. volume': '25022810'},
  '2025-07-11': {'1. open': '48.0750',
   '2. high': '48.9700',
   '3. low': '44.6900',
   '4. close': '45.2000',
   '5. volume': '19558362'},
  '2025-07-03': {'1. open': '47.7400',
   '2. high': '48.4500',
   '3. low': '46.8100',
   '4. close': '47.5700',
   '5. volume': '12791623'},
  '2025-06-27': {'1. open': '53.3100',
   '2. high': '55.5700',
   '3. low': '47.8400',
   '4. close': '48.2700',
   '5. volume': '21482221'},
  '2025-06-20': {'1. open': '52.9700',
   '2. high': '55.2200',
   '3. low': '50.8400',
   '4. close': '53.4600',
   '5. volume': '26596762'},
  '2025-06-13': {'1. open': '50.5000',
   '2. high': '56.0096',
   '3. low': '48.6700',
   '4. close': '55.1500',
   '5. volume': '28864571'},
  '2025-06-06': {'1. open': '54.3400',
   '2. high': '54.8100',
   '3. low': '50.5600',
   '4. close': '50.8100',
   '5. volume': '17103394'},
  '2025-05-30': {'1. open': '55.1300',
   '2. high': '55.9600',
   '3. low': '52.0900',
   '4. close': '53.8300',
   '5. volume': '14865447'},
  '2025-05-23': {'1. open': '53.8800',
   '2. high': '59.3600',
   '3. low': '51.8800',
   '4. close': '58.7900',
   '5. volume': '26033267'},
  '2025-05-16': {'1. open': '55.4400',
   '2. high': '55.5000',
   '3. low': '50.2850',
   '4. close': '51.8300',
   '5. volume': '26315005'},
  '2025-05-09': {'1. open': '62.0000',
   '2. high': '64.9900',
   '3. low': '59.2800',
   '4. close': '59.9500',
   '5. volume': '16748206'},
  '2025-05-02': {'1. open': '62.3200',
   '2. high': '68.4700',
   '3. low': '60.7900',
   '4. close': '61.0100',
   '5. volume': '21645401'},
  '2025-04-25': {'1. open': '72.2500',
   '2. high': '77.6200',
   '3. low': '63.2100',
   '4. close': '63.3400',
   '5. volume': '32214468'},
  '2025-04-17': {'1. open': '70.5200',
   '2. high': '75.7500',
   '3. low': '65.6900',
   '4. close': '71.3400',
   '5. volume': '32038121'},
  '2025-04-11': {'1. open': '81.7400',
   '2. high': '91.1900',
   '3. low': '63.3500',
   '4. close': '77.1200',
   '5. volume': '97035386'},
  '2025-04-04': {'1. open': '54.3500',
   '2. high': '76.4600',
   '3. low': '49.1800',
   '4. close': '74.8500',
   '5. volume': '63198241'},
  '2025-03-28': {'1. open': '46.7100',
   '2. high': '51.6999',
   '3. low': '44.8500',
   '4. close': '51.4200',
   '5. volume': '27921639'},
  '2025-03-21': {'1. open': '50.9430',
   '2. high': '51.6400',
   '3. low': '47.8941',
   '4. close': '48.1000',
   '5. volume': '28393207'},
  '2025-03-14': {'1. open': '53.9400',
   '2. high': '60.2750',
   '3. low': '51.2700',
   '4. close': '51.5300',
   '5. volume': '48182287'},
  '2025-03-07': {'1. open': '44.5100',
   '2. high': '55.3400',
   '3. low': '44.5100',
   '4. close': '51.2300',
   '5. volume': '56437957'},
  '2025-02-28': {'1. open': '43.8500',
   '2. high': '48.1500',
   '3. low': '43.0400',
   '4. close': '45.8300',
   '5. volume': '45340185'},
  '2025-02-21': {'1. open': '41.7500',
   '2. high': '44.8650',
   '3. low': '41.0400',
   '4. close': '44.3300',
   '5. volume': '30467381'},
  '2025-02-14': {'1. open': '43.1700',
   '2. high': '44.2600',
   '3. low': '41.8299',
   '4. close': '42.0000',
   '5. volume': '23161560'},
  '2025-02-07': {'1. open': '47.1300',
   '2. high': '48.2000',
   '3. low': '42.1300',
   '4. close': '43.9600',
   '5. volume': '29240892'},
  '2025-01-31': {'1. open': '46.7000',
   '2. high': '46.9200',
   '3. low': '41.9200',
   '4. close': '44.1200',
   '5. volume': '37179206'},
  '2025-01-24': {'1. open': '43.0300',
   '2. high': '43.4000',
   '3. low': '41.4600',
   '4. close': '41.7400',
   '5. volume': '22835186'},
  '2025-01-17': {'1. open': '51.1100',
   '2. high': '51.5000',
   '3. low': '42.7700',
   '4. close': '43.9600',
   '5. volume': '29057032'},
  '2025-01-10': {'1. open': '43.8200',
   '2. high': '50.4700',
   '3. low': '43.2800',
   '4. close': '49.4500',
   '5. volume': '23546070'},
  '2025-01-03': {'1. open': '46.9200',
   '2. high': '49.0179',
   '3. low': '44.0900',
   '4. close': '44.1000',
   '5. volume': '17348706'},
  '2024-12-27': {'1. open': '46.9200',
   '2. high': '48.8200',
   '3. low': '42.1800',
   '4. close': '44.4300',
   '5. volume': '16459036'},
  '2024-12-20': {'1. open': '42.3000',
   '2. high': '56.8500',
   '3. low': '42.3000',
   '4. close': '48.0800',
   '5. volume': '37704705'},
  '2024-12-13': {'1. open': '41.6700',
   '2. high': '43.0700',
   '3. low': '41.3800',
   '4. close': '42.5000',
   '5. volume': '15669947'},
  '2024-12-06': {'1. open': '42.6200',
   '2. high': '43.2400',
   '3. low': '41.3000',
   '4. close': '41.7600',
   '5. volume': '13185536'},
  '2024-11-29': {'1. open': '44.3900',
   '2. high': '46.2463',
   '3. low': '42.4200',
   '4. close': '42.5850',
   '5. volume': '11378219'},
  '2024-11-22': {'1. open': '46.3100',
   '2. high': '49.8300',
   '3. low': '44.1500',
   '4. close': '45.7600',
   '5. volume': '28192916'},
  '2024-11-15': {'1. open': '44.3700',
   '2. high': '48.6300',
   '3. low': '42.7800',
   '4. close': '46.5900',
   '5. volume': '21134966'},
  '2024-11-08': {'1. open': '56.3700',
   '2. high': '56.7102',
   '3. low': '44.5700',
   '4. close': '44.7700',
   '5. volume': '26263466'},
  '2024-11-01': {'1. open': '53.0600',
   '2. high': '58.0000',
   '3. low': '51.7100',
   '4. close': '56.8500',
   '5. volume': '23388084'},
  '2024-10-25': {'1. open': '51.6000',
   '2. high': '55.3900',
   '3. low': '50.8100',
   '4. close': '55.2900',
   '5. volume': '19822451'},
  '2024-10-18': {'1. open': '53.3100',
   '2. high': '54.6100',
   '3. low': '50.8600',
   '4. close': '51.2100',
   '5. volume': '16015116'},
  '2024-10-11': {'1. open': '53.9700',
   '2. high': '58.1600',
   '3. low': '53.6300',
   '4. close': '54.0700',
   '5. volume': '20089253'},
  '2024-10-04': {'1. open': '51.0000',
   '2. high': '55.4000',
   '3. low': '49.5000',
   '4. close': '53.0000',
   '5. volume': '28397165'},
  '2024-09-27': {'1. open': '47.0600',
   '2. high': '50.7680',
   '3. low': '46.6300',
   '4. close': '50.7300',
   '5. volume': '14897681'},
  '2024-09-20': {'1. open': '49.0700',
   '2. high': '51.0700',
   '3. low': '46.9300',
   '4. close': '47.4300',
   '5. volume': '24543473'},
  '2024-09-13': {'1. open': '54.9800',
   '2. high': '55.7050',
   '3. low': '47.7100',
   '4. close': '48.7900',
   '5. volume': '27333545'},
  '2024-09-06': {'1. open': '45.6200',
   '2. high': '58.5800',
   '3. low': '45.5200',
   '4. close': '56.1100',
   '5. volume': '36632915'},
  '2024-08-30': {'1. open': '45.6600',
   '2. high': '48.2399',
   '3. low': '44.3600',
   '4. close': '44.5000',
   '5. volume': '21533053'},
  '2024-08-23': {'1. open': '45.2900',
   '2. high': '49.1600',
   '3. low': '44.0300',
   '4. close': '45.9400',
   '5. volume': '28276963'},
  '2024-08-16': {'1. open': '54.7250',
   '2. high': '56.1700',
   '3. low': '44.6600',
   '4. close': '45.2300',
   '5. volume': '27112901'},
  '2024-08-09': {'1. open': '90.0800',
   '2. high': '91.0200',
   '3. low': '54.5100',
   '4. close': '55.7800',
   '5. volume': '79239848'},
  '2024-08-02': {'1. open': '46.3700',
   '2. high': '64.4500',
   '3. low': '44.6200',
   '4. close': '62.6800',
   '5. volume': '63799751'},
  '2024-07-26': {'1. open': '11.3100',
   '2. high': '51.0400',
   '3. low': '10.6700',
   '4. close': '46.7800',
   '5. volume': '71070791'},
  '2024-07-19': {'1. open': '10.0800',
   '2. high': '11.6700',
   '3. low': '10.0300',
   '4. close': '11.5300',
   '5. volume': '96178562'},
  '2024-07-12': {'1. open': '10.3400',
   '2. high': '10.4650',
   '3. low': '9.9950',
   '4. close': '10.1600',
   '5. volume': '50695807'},
  '2024-07-05': {'1. open': '10.8100',
   '2. high': '10.8600',
   '3. low': '10.3200',
   '4. close': '10.4600',
   '5. volume': '25960338'},
  '2024-06-28': {'1. open': '11.3600',
   '2. high': '11.3800',
   '3. low': '10.7200',
   '4. close': '10.9200',
   '5. volume': '40838073'},
  '2024-06-21': {'1. open': '11.2300',
   '2. high': '11.7100',
   '3. low': '11.0050',
   '4. close': '11.2900',
   '5. volume': '47497761'},
  '2024-06-14': {'1. open': '11.2900',
   '2. high': '11.4400',
   '3. low': '10.8050',
   '4. close': '11.2100',
   '5. volume': '56136583'},
  '2024-06-07': {'1. open': '11.4100',
   '2. high': '11.9000',
   '3. low': '11.0300',
   '4. close': '11.1300',
   '5. volume': '62193314'},
  '2024-05-31': {'1. open': '11.2100',
   '2. high': '12.2100',
   '3. low': '11.1900',
   '4. close': '11.5300',
   '5. volume': '60683124'},
  '2024-05-24': {'1. open': '11.3700',
   '2. high': '11.7300',
   '3. low': '11.1200',
   '4. close': '11.2500',
   '5. volume': '69201375'},
  '2024-05-17': {'1. open': '12.0400',
   '2. high': '12.2700',
   '3. low': '11.3400',
   '4. close': '11.3600',
   '5. volume': '45686214'},
  '2024-05-10': {'1. open': '12.5900',
   '2. high': '12.6100',
   '3. low': '12.0400',
   '4. close': '12.0600',
   '5. volume': '46577129'},
  '2024-05-03': {'1. open': '13.2900',
   '2. high': '13.8600',
   '3. low': '12.7200',
   '4. close': '12.7900',
   '5. volume': '63972737'},
  '2024-04-26': {'1. open': '14.8700',
   '2. high': '14.8900',
   '3. low': '13.3600',
   '4. close': '13.4300',
   '5. volume': '79334755'},
  '2024-04-19': {'1. open': '14.3500',
   '2. high': '15.7050',
   '3. low': '14.1800',
   '4. close': '15.4600',
   '5. volume': '136359350'},
  '2024-04-12': {'1. open': '14.0000',
   '2. high': '15.4850',
   '3. low': '13.5300',
   '4. close': '14.7900',
   '5. volume': '145534808'},
  '2024-04-05': {'1. open': '12.9900',
   '2. high': '14.4300',
   '3. low': '12.9250',
   '4. close': '14.2600',
   '5. volume': '115288260'},
  '2024-03-28': {'1. open': '13.1400',
   '2. high': '13.1500',
   '3. low': '12.7300',
   '4. close': '12.9700',
   '5. volume': '37744662'},
  '2024-03-22': {'1. open': '13.9700',
   '2. high': '13.9858',
   '3. low': '12.9200',
   '4. close': '13.1300',
   '5. volume': '63505932'},
  '2024-03-15': {'1. open': '14.6100',
   '2. high': '14.8610',
   '3. low': '13.3900',
   '4. close': '14.1900',
   '5. volume': '85533281'},
  '2024-03-08': {'1. open': '13.5400',
   '2. high': '14.9600',
   '3. low': '13.4900',
   '4. close': '14.4800',
   '5. volume': '72670800'},
  '2024-03-01': {'1. open': '13.8100',
   '2. high': '13.8700',
   '3. low': '13.3500',
   '4. close': '13.6000',
   '5. volume': '43491549'},
  '2024-02-23': {'1. open': '14.6200',
   '2. high': '15.2400',
   '3. low': '13.9100',
   '4. close': '13.9300',
   '5. volume': '56864545'},
  '2024-02-16': {'1. open': '13.9300',
   '2. high': '16.3100',
   '3. low': '13.8900',
   '4. close': '14.4000',
   '5. volume': '90624441'},
  '2024-02-09': {'1. open': '14.8600',
   '2. high': '15.1700',
   '3. low': '13.7500',
   '4. close': '14.0200',
   '5. volume': '43817374'},
  '2024-02-02': {'1. open': '14.5400',
   '2. high': '15.2900',
   '3. low': '14.3600',
   '4. close': '14.9900',
   '5. volume': '57492051'},
  '2024-01-26': {'1. open': '14.8100',
   '2. high': '14.9200',
   '3. low': '13.9305',
   '4. close': '14.5300',
   '5. volume': '45991128'},
  '2024-01-19': {'1. open': '15.2000',
   '2. high': '16.3000',
   '3. low': '14.8800',
   '4. close': '15.0000',
   '5. volume': '49710389'},
  '2024-01-12': {'1. open': '15.5400',
   '2. high': '15.6100',
   '3. low': '14.4300',
   '4. close': '14.8400',
   '5. volume': '46634912'},
  '2024-01-05': {'1. open': '15.9500',
   '2. high': '16.3500',
   '3. low': '15.4000',
   '4. close': '15.5500',
   '5. volume': '47365335'},
  '2023-12-29': {'1. open': '16.5700',
   '2. high': '16.6800',
   '3. low': '15.3800',
   '4. close': '15.5200',
   '5. volume': '28214482'},
  '2023-12-22': {'1. open': '16.1200',
   '2. high': '17.6300',
   '3. low': '16.0700',
   '4. close': '16.6100',
   '5. volume': '50338136'},
  '2023-12-15': {'1. open': '16.6900',
   '2. high': '16.7400',
   '3. low': '15.5200',
   '4. close': '16.1400',
   '5. volume': '55528043'},
  '2023-12-08': {'1. open': '17.5200',
   '2. high': '17.8200',
   '3. low': '16.7200',
   '4. close': '16.7500',
   '5. volume': '31544910'},
  '2023-12-01': {'1. open': '17.5800',
   '2. high': '17.6900',
   '3. low': '17.0000',
   '4. close': '17.2300',
   '5. volume': '36335156'},
  '2023-11-24': {'1. open': '18.4500',
   '2. high': '18.5100',
   '3. low': '17.3400',
   '4. close': '17.4200',
   '5. volume': '26256519'},
  '2023-11-17': {'1. open': '20.0700',
   '2. high': '20.1800',
   '3. low': '18.5000',
   '4. close': '18.5600',
   '5. volume': '41114112'},
  '2023-11-10': {'1. open': '20.9200',
   '2. high': '21.0855',
   '3. low': '19.7350',
   '4. close': '19.9300',
   '5. volume': '44482927'},
  '2023-11-03': {'1. open': '26.0400',
   '2. high': '26.0990',
   '3. low': '21.0400',
   '4. close': '21.1800',
   '5. volume': '54068624'},
  '2023-10-27': {'1. open': '26.9400',
   '2. high': '27.3550',
   '3. low': '24.2950',
   '4. close': '27.0800',
   '5. volume': '67278523'},
  '2023-10-20': {'1. open': '24.3700',
   '2. high': '26.9300',
   '3. low': '22.5500',
   '4. close': '26.4600',
   '5. volume': '78062852'},
  '2023-10-13': {'1. open': '24.4300',
   '2. high': '25.9100',
   '3. low': '21.4300',
   '4. close': '25.3200',
   '5. volume': '61944701'},
  '2023-10-06': {'1. open': '23.4400',
   '2. high': '25.9600',
   '3. low': '22.7500',
   '4. close': '23.6400',
   '5. volume': '64372216'},
  '2023-09-29': {'1. open': '23.5300',
   '2. high': '25.4400',
   '3. low': '21.8700',
   '4. close': '23.3200',
   '5. volume': '64473490'},
  '2023-09-22': {'1. open': '20.9400',
   '2. high': '22.9900',
   '3. low': '19.9350',
   '4. close': '22.8700',
   '5. volume': '61824795'},
  '2023-09-15': {'1. open': '20.9100',

In [94]:
# STEP 3. CONVERT DATA IN JSON TO PANDAS DATAFRAME + DATA WRANGLING + COMPUTE DERIVED FIELDS + EXPORT TO A CSV FILE

# 1. Extract the 'Weekly Prices (open, high, low, close) and Volumes' portion and convert to a DataFrame
time_series_weekly_vxx_df = pd.DataFrame.from_dict(
    time_series_weekly_vxx['Weekly Time Series'],
    orient='index'
)

# 2. Reset index so dates become a column instead of an index
time_series_weekly_vxx_df.reset_index(inplace=True)

# 3. Rename columns
time_series_weekly_vxx_df.columns = [
    'date',
    'open',
    'high',
    'low',
    'close',
    'volume'
]

# 4. Convert data types
time_series_weekly_vxx_df['date'] = pd.to_datetime(time_series_weekly_vxx_df['date'])

numeric_columns = ['open', 'high', 'low', 'close', 'volume']

time_series_weekly_vxx_df[numeric_columns] = (
    time_series_weekly_vxx_df[numeric_columns].astype(float)
)

time_series_weekly_vxx_df['volume'] = time_series_weekly_vxx_df['volume'].astype(int)

# 5. Sort date by ascending order and resets the order of the index
# This is important for time series analysis

time_series_weekly_vxx_df = time_series_weekly_vxx_df.sort_values('date').reset_index(drop=True)

# 6. Compute the Derived fields

    # A. Daily Price Movement
time_series_weekly_vxx_df['daily_change'] = (
    time_series_weekly_vxx_df['close'] - time_series_weekly_vxx_df['open']
)

    # B. Intraday Return %
time_series_weekly_vxx_df['intraday_return_pct'] = (
    (time_series_weekly_vxx_df['close'] - time_series_weekly_vxx_df['open'])
    / time_series_weekly_vxx_df['open']
) * 100

    # C. Day-over-day return
time_series_weekly_vxx_df['daily_return_pct'] = (
    time_series_weekly_vxx_df['close']
    .pct_change()
) * 100

    # D. Cumulative return %
    # iloc[0] refers to the initial close
time_series_weekly_vxx_df["cumulative_return_pct"] = (
    (time_series_weekly_vxx_df["close"] / time_series_weekly_vxx_df["close"].iloc[0]) - 1
) * 100

    # E. Intraday Volatility
time_series_weekly_vxx_df['intraday_volatility_abs'] = (
    time_series_weekly_vxx_df['high'] - time_series_weekly_vxx_df['low']
)

    # F. Volatility Ratio
time_series_weekly_vxx_df['volatility_ratio'] = (
    time_series_weekly_vxx_df['intraday_volatility_abs']
    / time_series_weekly_vxx_df['close']
)

    # G. Intraday Volatility %
time_series_weekly_vxx_df['intraday_volatility_pct'] = (
    (
        time_series_weekly_vxx_df['high']
        - time_series_weekly_vxx_df['low']
    )
    / time_series_weekly_vxx_df['open']
) * 100

    # H. Volume Change %
time_series_weekly_vxx_df['volume_change_pct'] = (
    time_series_weekly_vxx_df['volume']
    .pct_change()
) * 100

    # I. 7-Day Moving Average
time_series_weekly_vxx_df['moving_avg_7d'] = (
    time_series_weekly_vxx_df['close']
    .rolling(7)
    .mean()
)

    # J. 30-Day Moving Average
time_series_weekly_vxx_df['moving_avg_30d'] = (
    time_series_weekly_vxx_df['close']
    .rolling(30)
    .mean()
)

# 7. Add Symbol and Time Zone from the Metadata

time_series_weekly_vxx_df['symbol'] = time_series_weekly_vxx['Meta Data']['2. Symbol']
time_series_weekly_vxx_df['dt_last_refreshed'] = time_series_weekly_vxx['Meta Data']['3. Last Refreshed']
time_series_weekly_vxx_df['timezone'] = time_series_weekly_vxx['Meta Data']['4. Time Zone']

# 8. Convert data types from string to date
time_series_weekly_vxx_df['dt_last_refreshed'] = pd.to_datetime(time_series_weekly_vxx_df['dt_last_refreshed'])

# 8. Round numeric columns to 2 decimal places
numeric_columns = time_series_weekly_vxx_df.select_dtypes(include='number').columns

time_series_weekly_vxx_df[numeric_columns] = (
    time_series_weekly_vxx_df[numeric_columns]
    .round(2)
)

# 9. View the data
time_series_weekly_vxx_df

,date,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,volatility_ratio,intraday_volatility_pct,volume_change_pct,moving_avg_7d,moving_avg_30d,symbol,dt_last_refreshed,timezone
0,2009-02-06,108.10,108.10,95.06,97.70,1024000,-10.40,-9.62,NaN,0.00,13.04,0.13,12.06,NaN,NaN,NaN,VXX,2026-05-08,US/Eastern
1,2009-02-13,98.33,108.00,97.87,101.99,665600,3.66,3.72,4.39,4.39,10.13,0.10,10.30,-35.00,NaN,NaN,VXX,2026-05-08,US/Eastern
2,2009-02-20,107.00,116.40,105.00,113.32,358400,6.32,5.91,11.11,15.99,11.40,0.10,10.65,-46.15,NaN,NaN,VXX,2026-05-08,US/Eastern
3,2009-02-27,111.00,120.00,102.96,108.67,569600,-2.33,-2.10,-4.10,11.23,17.04,0.16,15.35,58.93,NaN,NaN,VXX,2026-05-08,US/Eastern
4,2009-03-06,111.02,118.55,104.79,113.38,870400,2.36,2.13,4.33,16.05,13.76,0.12,12.39,52.81,NaN,NaN,VXX,2026-05-08,US/Eastern
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,2026-04-10,34.80,36.33,30.10,30.77,49587252,-4.03,-11.58,-11.33,-68.51,6.24,0.20,17.92,-20.55,34.36,31.76,VXX,2026-05-08,US/Eastern
897,2026-04-17,31.16,31.30,28.37,28.98,35726903,-2.18,-7.00,-5.82,-70.34,2.93,0.10,9.40,-27.95,34.37,31.62,VXX,2026-05-08,US/Eastern
898,2026-04-24,29.29,30.94,29.07,29.79,39941119,0.50,1.71,2.80,-69.51,1.88,0.06,6.40,11.80,33.53,31.52,VXX,2026-05-08,US/Eastern
899,2026-05-01,29.48,29.63,27.77,28.40,29256666,-1.08,-3.66,-4.67,-70.93,1.86,0.07,6.31,-26.75,32.57,31.35,VXX,2026-05-08,US/Eastern
900,2026-05-08,28.35,29.24,27.56,28.06,38682038,-0.29,-1.02,-1.20,-71.28,1.68,0.06,5.93,32.22,31.44,31.04,VXX,2026-05-08,US/Eastern

In [95]:
# 10. View dataframe: Check datatypes & count of rows
time_series_weekly_vxx_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 901 entries, 0 to 900
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     901 non-null    datetime64[us]
 1   open                     901 non-null    float64
 2   high                     901 non-null    float64
 3   low                      901 non-null    float64
 4   close                    901 non-null    float64
 5   volume                   901 non-null    int64
 6   daily_change             901 non-null    float64
 7   intraday_return_pct      901 non-null    float64
 8   daily_return_pct         900 non-null    float64
 9   cumulative_return_pct    901 non-null    float64
 10  intraday_volatility_abs  901 non-null    float64
 11  volatility_ratio         901 non-null    float64
 12  intraday_volatility_pct  901 non-null    float64
 13  volume_change_pct        900 non-null    float64
 14  moving_avg_7d            895 non-null    float64
 15  moving_avg_30d           872 non-null    float64
 16  symbol                   901 non-null    str
 17  dt_last_refreshed        901 non-null    datetime64[us]
 18  timezone                 901 non-null    str
dtypes: datetime64[us](2), float64(14), int64(1), str(2)
memory usage: 133.9 KB

In [96]:
# 11. Re-order columns

time_series_weekly_vxx_df = time_series_weekly_vxx_df[
    [
        'date',
        'symbol',
        'dt_last_refreshed',
        'timezone',
        'open',
        'high',
        'low',
        'close',
        'volume',
        'daily_change',
        'intraday_return_pct',
        'daily_return_pct',
        'cumulative_return_pct',
        'intraday_volatility_abs',
        'volatility_ratio',
        'intraday_volatility_pct',
        'volume_change_pct',
        'moving_avg_7d',
        'moving_avg_30d'
    ]
]

time_series_weekly_vxx_df

,date,symbol,dt_last_refreshed,timezone,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,volatility_ratio,intraday_volatility_pct,volume_change_pct,moving_avg_7d,moving_avg_30d
0,2009-02-06,VXX,2026-05-08,US/Eastern,108.10,108.10,95.06,97.70,1024000,-10.40,-9.62,NaN,0.00,13.04,0.13,12.06,NaN,NaN,NaN
1,2009-02-13,VXX,2026-05-08,US/Eastern,98.33,108.00,97.87,101.99,665600,3.66,3.72,4.39,4.39,10.13,0.10,10.30,-35.00,NaN,NaN
2,2009-02-20,VXX,2026-05-08,US/Eastern,107.00,116.40,105.00,113.32,358400,6.32,5.91,11.11,15.99,11.40,0.10,10.65,-46.15,NaN,NaN
3,2009-02-27,VXX,2026-05-08,US/Eastern,111.00,120.00,102.96,108.67,569600,-2.33,-2.10,-4.10,11.23,17.04,0.16,15.35,58.93,NaN,NaN
4,2009-03-06,VXX,2026-05-08,US/Eastern,111.02,118.55,104.79,113.38,870400,2.36,2.13,4.33,16.05,13.76,0.12,12.39,52.81,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
896,2026-04-10,VXX,2026-05-08,US/Eastern,34.80,36.33,30.10,30.77,49587252,-4.03,-11.58,-11.33,-68.51,6.24,0.20,17.92,-20.55,34.36,31.76
897,2026-04-17,VXX,2026-05-08,US/Eastern,31.16,31.30,28.37,28.98,35726903,-2.18,-7.00,-5.82,-70.34,2.93,0.10,9.40,-27.95,34.37,31.62
898,2026-04-24,VXX,2026-05-08,US/Eastern,29.29,30.94,29.07,29.79,39941119,0.50,1.71,2.80,-69.51,1.88,0.06,6.40,11.80,33.53,31.52
899,2026-05-01,VXX,2026-05-08,US/Eastern,29.48,29.63,27.77,28.40,29256666,-1.08,-3.66,-4.67,-70.93,1.86,0.07,6.31,-26.75,32.57,31.35
900,2026-05-08,VXX,2026-05-08,US/Eastern,28.35,29.24,27.56,28.06,38682038,-0.29,-1.02,-1.20,-71.28,1.68,0.06,5.93,32.22,31.44,31.04

In [97]:
# 12. Export to CSV and save inside output folder
time_series_weekly_vxx_df.to_csv(
    output_folder / "time_series_weekly_vxx_df.csv",
    index=False
)

**6. Repeat steps 4 and 5, but this time for VTI**

Use all of the same settings to now gather data for VTI, a mutual fund that consists of _every_ US stock. VTI can be considered an indicator for the overall market.

Again, as in step 5, save this data out to a csv.

#### <font color='green'>**VTI is the ticker symbol for the Vanguard Total Stock Market ETF**</font><br>

- It is a popular, low-cost exchange-traded fund designed to track the performance of the entire U.S. equity market, including large, mid, and small-cap stocks. 
- As of May 8, 2026, it trades around \(\$362-\$363\) with a very low expense ratio of 0.03%.

**Key Details (as of May 2026):**<br>
* Exchange: NYSE Arca
* Asset Class: Broad U.S. Equity
* Expense Ratio: 0.03% (approx. \(\$3\) annually per \(\$10,000\) invested)
* Top Holdings: Heavily weighted in major tech and growth companies like Apple, Microsoft, Nvidia, Amazon, and Meta.
* Purpose: Provides diversified exposure to ~3,700+ U.S. companies in a single fund.

VTI is often compared to the S&P 500 (VOO), with VTI offering broader exposure to smaller companies, whereas VOO focuses on ~500 large-cap, established companies.

In [98]:
# STEP 1. DEFINE URL AND PARAMETERS

# API endpoint
base_url = 'https://www.alphavantage.co/query'

# Parameters
params = {
    'function': 'TIME_SERIES_WEEKLY',    # returns raw (as-traded) daily time series of the global equity specified
    'symbol': 'VTI',             # the global equity specified: Vanguard Total Stock Market ETF
    'datatype': 'json',          # returns the daily time series in JSON format
    'apikey': ALPHAVANTAGE_API_KEY
}

In [99]:
# STEP 2. API REQUEST + ERROR HANDLING

# 1. Calls the API via requests and safely handles possible errors

try:
    # Send GET request to API with headers and parameters
    response = requests.get(base_url, params=params)

    # Pause briefly to avoid hitting API rate limits
    time.sleep(1)

    # Raise an error if the response status is not successful
    response.raise_for_status()

    # Parse JSON response and convert to Python dictionary
    time_series_weekly_vti = response.json()

# 2. Handles HTTP errors 
# Catches API-related errors (e.g., 401, 404, 408, 429)

except requests.exceptions.HTTPError as e:
    print("HTTP error:", response.status_code, response.text)
    time_series_weekly_vti = [] # reset to empty dataset

# 3. Handles other errors 
# Catches unexpected errors (e.g., connection issues, parsing errors)

except Exception as e:
    print("Other error:", e)
    time_series_weekly_vti = [] # reset to empty dataset

In [101]:
time_series_weekly_vti

{'Meta Data': {'1. Information': 'Weekly Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'VTI',
  '3. Last Refreshed': '2026-05-08',
  '4. Time Zone': 'US/Eastern'},
 'Weekly Time Series': {'2026-05-08': {'1. open': '355.0800',
   '2. high': '363.1250',
   '3. low': '352.5300',
   '4. close': '362.8700',
   '5. volume': '15897275'},
  '2026-05-01': {'1. open': '352.0000',
   '2. high': '357.1500',
   '3. low': '348.6700',
   '4. close': '355.2900',
   '5. volume': '15103707'},
  '2026-04-24': {'1. open': '349.9000',
   '2. high': '352.3700',
   '3. low': '346.5500',
   '4. close': '352.0500',
   '5. volume': '17522660'},
  '2026-04-17': {'1. open': '333.9400',
   '2. high': '351.7450',
   '3. low': '333.6400',
   '4. close': '350.5300',
   '5. volume': '18482054'},
  '2026-04-10': {'1. open': '323.9500',
   '2. high': '336.5500',
   '3. low': '321.4650',
   '4. close': '335.0500',
   '5. volume': '19371807'},
  '2026-04-02': {'1. open': '315.9000',
   '2. high': '325.0900',
   '3. low': '310.3990',
   '4. close': '323.7600',
   '5. volume': '22468826'},
  '2026-03-27': {'1. open': '325.0150',
   '2. high': '327.8500',
   '3. low': '312.5000',
   '4. close': '313.0900',
   '5. volume': '27717972'},
  '2026-03-20': {'1. open': '329.2200',
   '2. high': '332.3200',
   '3. low': '318.5650',
   '4. close': '320.3400',
   '5. volume': '22583741'},
  '2026-03-13': {'1. open': '328.2000',
   '2. high': '336.9000',
   '3. low': '325.6700',
   '4. close': '326.1300',
   '5. volume': '38212142'},
  '2026-03-06': {'1. open': '335.0100',
   '2. high': '340.1300',
   '3. low': '330.0000',
   '4. close': '331.4100',
   '5. volume': '40740228'},
  '2026-02-27': {'1. open': '339.5000',
   '2. high': '342.1300',
   '3. low': '335.4350',
   '4. close': '338.7700',
   '5. volume': '29423949'},
  '2026-02-20': {'1. open': '336.1100',
   '2. high': '340.7100',
   '3. low': '333.5700',
   '4. close': '340.2700',
   '5. volume': '24283716'},
  '2026-02-13': {'1. open': '340.3700',
   '2. high': '344.3000',
   '3. low': '334.2700',
   '4. close': '336.6500',
   '5. volume': '28550116'},
  '2026-02-06': {'1. open': '339.5500',
   '2. high': '343.4000',
   '3. low': '333.1900',
   '4. close': '340.9600',
   '5. volume': '37979564'},
  '2026-01-30': {'1. open': '341.1500',
   '2. high': '344.4200',
   '3. low': '337.6900',
   '4. close': '340.5700',
   '5. volume': '33336083'},
  '2026-01-23': {'1. open': '336.7200',
   '2. high': '342.0100',
   '3. low': '334.6700',
   '4. close': '340.5600',
   '5. volume': '33188271'},
  '2026-01-16': {'1. open': '340.9100',
   '2. high': '343.6650',
   '3. low': '338.9100',
   '4. close': '341.8500',
   '5. volume': '40734228'},
  '2026-01-09': {'1. open': '338.0000',
   '2. high': '342.9400',
   '3. low': '337.8500',
   '4. close': '342.4000',
   '5. volume': '31780307'},
  '2026-01-02': {'1. open': '338.4000',
   '2. high': '339.2700',
   '3. low': '334.6000',
   '4. close': '336.3100',
   '5. volume': '16043088'},
  '2025-12-26': {'1. open': '337.0000',
   '2. high': '340.3250',
   '3. low': '336.6100',
   '4. close': '339.6700',
   '5. volume': '14943312'},
  '2025-12-19': {'1. open': '337.9800',
   '2. high': '338.0000',
   '3. low': '330.6300',
   '4. close': '336.2200',
   '5. volume': '19051747'},
  '2025-12-12': {'1. open': '338.2000',
   '2. high': '339.9400',
   '3. low': '334.8500',
   '4. close': '335.9900',
   '5. volume': '20200999'},
  '2025-12-05': {'1. open': '333.9600',
   '2. high': '338.9600',
   '3. low': '333.7500',
   '4. close': '337.5600',
   '5. volume': '17898824'},
  '2025-11-28': {'1. open': '325.5100',
   '2. high': '336.4201',
   '3. low': '324.9400',
   '4. close': '336.3100',
   '5. volume': '12855705'},
  '2025-11-21': {'1. open': '328.7050',
   '2. high': '331.6000',
   '3. low': '319.4350',
   '4. close': '323.8000',
   '5. volume': '22309603'},
  '2025-11-14': {'1. open': '333.3200',
   '2. high': '336.9250',
   '3. low': '325.6200',
   '4. close': '329.8600',
   '5. volume': '16779226'},
  '2025-11-07': {'1. open': '337.0000',
   '2. high': '337.1400',
   '3. low': '324.9700',
   '4. close': '330.0900',
   '5. volume': '17450290'},
  '2025-10-31': {'1. open': '336.7000',
   '2. high': '339.0601',
   '3. low': '333.8500',
   '4. close': '335.4200',
   '5. volume': '23348842'},
  '2025-10-24': {'1. open': '328.9500',
   '2. high': '334.5400',
   '3. low': '326.6500',
   '4. close': '333.7100',
   '5. volume': '22113074'},
  '2025-10-17': {'1. open': '325.7850',
   '2. high': '330.9900',
   '3. low': '322.0800',
   '4. close': '327.3000',
   '5. volume': '26004891'},
  '2025-10-10': {'1. open': '331.4100',
   '2. high': '332.1987',
   '3. low': '321.6200',
   '4. close': '321.8000',
   '5. volume': '24694660'},
  '2025-10-03': {'1. open': '327.6900',
   '2. high': '331.7350',
   '3. low': '325.8800',
   '4. close': '329.9700',
   '5. volume': '22810336'},
  '2025-09-26': {'1. open': '327.7550',
   '2. high': '330.3600',
   '3. low': '323.3800',
   '4. close': '327.1800',
   '5. volume': '17124288'},
  '2025-09-19': {'1. open': '325.4700',
   '2. high': '328.8500',
   '3. low': '322.7650',
   '4. close': '328.4400',
   '5. volume': '17276196'},
  '2025-09-12': {'1. open': '320.4400',
   '2. high': '325.2000',
   '3. low': '319.4500',
   '4. close': '324.3100',
   '5. volume': '17596381'},
  '2025-09-05': {'1. open': '314.5200',
   '2. high': '322.0550',
   '3. low': '313.3000',
   '4. close': '319.5500',
   '5. volume': '14887593'},
  '2025-08-29': {'1. open': '317.5800',
   '2. high': '320.4000',
   '3. low': '316.3347',
   '4. close': '318.2000',
   '5. volume': '17761661'},
  '2025-08-22': {'1. open': '316.3200',
   '2. high': '318.8300',
   '3. low': '311.2400',
   '4. close': '318.1800',
   '5. volume': '20359957'},
  '2025-08-15': {'1. open': '313.3300',
   '2. high': '317.9400',
   '3. low': '311.8200',
   '4. close': '316.4700',
   '5. volume': '17432635'},
  '2025-08-08': {'1. open': '307.5800',
   '2. high': '313.4024',
   '3. low': '307.5800',
   '4. close': '313.0300',
   '5. volume': '17692014'},
  '2025-08-01': {'1. open': '314.2000',
   '2. high': '314.8400',
   '3. low': '304.4000',
   '4. close': '305.7400',
   '5. volume': '24803465'},
  '2025-07-25': {'1. open': '309.9400',
   '2. high': '313.9300',
   '3. low': '308.2300',
   '4. close': '313.6900',
   '5. volume': '16188141'},
  '2025-07-18': {'1. open': '306.7400',
   '2. high': '310.2000',
   '3. low': '304.0000',
   '4. close': '309.0900',
   '5. volume': '16444147'},
  '2025-07-11': {'1. open': '306.9900',
   '2. high': '308.9250',
   '3. low': '304.2153',
   '4. close': '307.0200',
   '5. volume': '16101167'},
  '2025-07-03': {'1. open': '303.7400',
   '2. high': '308.4000',
   '3. low': '302.6000',
   '4. close': '308.0300',
   '5. volume': '13783517'},
  '2025-06-27': {'1. open': '293.4900',
   '2. high': '304.2600',
   '3. low': '291.9700',
   '4. close': '303.3100',
   '5. volume': '15067210'},
  '2025-06-20': {'1. open': '295.4500',
   '2. high': '297.3699',
   '3. low': '292.7200',
   '4. close': '293.4300',
   '5. volume': '10928875'},
  '2025-06-13': {'1. open': '295.4600',
   '2. high': '298.0677',
   '3. low': '292.8400',
   '4. close': '293.5700',
   '5. volume': '15124789'},
  '2025-06-06': {'1. open': '289.3400',
   '2. high': '295.8800',
   '3. low': '287.5800',
   '4. close': '295.1200',
   '5. volume': '14403121'},
  '2025-05-30': {'1. open': '288.4600',
   '2. high': '291.8200',
   '3. low': '286.8550',
   '4. close': '289.8800',
   '5. volume': '12424313'},
  '2025-05-23': {'1. open': '289.4600',
   '2. high': '293.1250',
   '3. low': '283.0000',
   '4. close': '285.0400',
   '5. volume': '14671929'},
  '2025-05-16': {'1. open': '286.7800',
   '2. high': '292.7500',
   '3. low': '284.3685',
   '4. close': '292.5800',
   '5. volume': '18457407'},
  '2025-05-09': {'1. open': '276.6500',
   '2. high': '280.8673',
   '3. low': '273.5800',
   '4. close': '277.9700',
   '5. volume': '12894817'},
  '2025-05-02': {'1. open': '271.0200',
   '2. high': '279.6000',
   '3. low': '266.2500',
   '4. close': '278.8000',
   '5. volume': '15165183'},
  '2025-04-25': {'1. open': '256.2300',
   '2. high': '270.8983',
   '3. low': '249.9400',
   '4. close': '270.6400',
   '5. volume': '22876724'},
  '2025-04-17': {'1. open': '266.4300',
   '2. high': '266.7300',
   '3. low': '255.4450',
   '4. close': '258.7500',
   '5. volume': '16416754'},
  '2025-04-11': {'1. open': '240.0000',
   '2. high': '268.4800',
   '3. low': '236.4200',
   '4. close': '261.7400',
   '5. volume': '51812596'},
  '2025-04-04': {'1. open': '270.2700',
   '2. high': '279.2500',
   '3. low': '248.1808',
   '4. close': '248.4700',
   '5. volume': '36699806'},
  '2025-03-28': {'1. open': '282.2500',
   '2. high': '285.0900',
   '3. low': '273.0500',
   '4. close': '273.4300',
   '5. volume': '14500598'},
  '2025-03-21': {'1. open': '276.7300',
   '2. high': '281.3800',
   '3. low': '275.3350',
   '4. close': '278.8500',
   '5. volume': '15608747'},
  '2025-03-14': {'1. open': '279.4300',
   '2. high': '280.2800',
   '3. low': '270.2000',
   '4. close': '276.9900',
   '5. volume': '23048504'},
  '2025-03-07': {'1. open': '293.9100',
   '2. high': '294.7200',
   '3. low': '278.1100',
   '4. close': '283.3400',
   '5. volume': '26652568'},
  '2025-02-28': {'1. open': '296.9600',
   '2. high': '297.3400',
   '3. low': '287.3500',
   '4. close': '292.9600',
   '5. volume': '17014959'},
  '2025-02-21': {'1. open': '302.3700',
   '2. high': '303.3904',
   '3. low': '295.6350',
   '4. close': '295.9200',
   '5. volume': '11876973'},
  '2025-02-14': {'1. open': '299.5600',
   '2. high': '302.5500',
   '3. low': '296.2400',
   '4. close': '301.8400',
   '5. volume': '14071110'},
  '2025-02-07': {'1. open': '293.3200',
   '2. high': '301.6597',
   '3. low': '292.7000',
   '4. close': '298.0000',
   '5. volume': '16397651'},
  '2025-01-31': {'1. open': '295.0000',
   '2. high': '302.6000',
   '3. low': '294.4400',
   '4. close': '298.6000',
   '5. volume': '16888457'},
  '2025-01-24': {'1. open': '297.7500',
   '2. high': '302.6724',
   '3. low': '296.9092',
   '4. close': '301.3000',
   '5. volume': '12415984'},
  '2025-01-17': {'1. open': '285.0000',
   '2. high': '297.1175',
   '3. low': '284.6300',
   '4. close': '296.2000',
   '5. volume': '15985716'},
  '2025-01-10': {'1. open': '295.2000',
   '2. high': '296.8950',
   '3. low': '286.2200',
   '4. close': '287.3000',
   '5. volume': '14370658'},
  '2025-01-03': {'1. open': '290.8800',
   '2. high': '293.3500',
   '3. low': '287.3450',
   '4. close': '293.0600',
   '5. volume': '15391399'},
  '2024-12-27': {'1. open': '292.5300',
   '2. high': '297.7800',
   '3. low': '290.5401',
   '4. close': '294.0700',
   '5. volume': '14292601'},
  '2024-12-20': {'1. open': '300.5700',
   '2. high': '301.7500',
   '3. low': '288.1100',
   '4. close': '293.2800',
   '5. volume': '18159396'},
  '2024-12-13': {'1. open': '302.5300',
   '2. high': '302.6500',
   '3. low': '299.0700',
   '4. close': '299.9300',
   '5. volume': '12145478'},
  '2024-12-06': {'1. open': '300.3000',
   '2. high': '302.9450',
   '3. low': '299.6401',
   '4. close': '302.4500',
   '5. volume': '13459193'},
  '2024-11-29': {'1. open': '298.6700',
   '2. high': '300.3800',
   '3. low': '296.9000',
   '4. close': '299.8600',
   '5. volume': '11219647'},
  '2024-11-22': {'1. open': '290.6400',
   '2. high': '296.8100',
   '3. low': '289.4500',
   '4. close': '296.5100',
   '5. volume': '13205570'},
  '2024-11-15': {'1. open': '297.9300',
   '2. high': '298.1200',
   '3. low': '289.3500',
   '4. close': '290.3100',
   '5. volume': '16811310'},
  '2024-11-08': {'1. open': '282.1700',
   '2. high': '297.3700',
   '3. low': '280.8650',
   '4. close': '296.7100',
   '5. volume': '18372291'},
  '2024-11-01': {'1. open': '287.0600',
   '2. high': '288.1000',
   '3. low': '280.9600',
   '4. close': '282.2300',
   '5. volume': '12058521'},
  '2024-10-25': {'1. open': '288.5100',
   '2. high': '288.8000',
   '3. low': '283.3400',
   '4. close': '285.5400',
   '5. volume': '12036168'},
  '2024-10-18': {'1. open': '286.8600',
   '2. high': '289.6977',
   '3. low': '285.9100',
   '4. close': '288.8900',
   '5. volume': '12105895'},
  '2024-10-11': {'1. open': '282.0400',
   '2. high': '286.3900',
   '3. low': '279.5400',
   '4. close': '286.1100',
   '5. volume': '20100680'},
  '2024-10-04': {'1. open': '281.6200',
   '2. high': '283.3856',
   '3. low': '278.8700',
   '4. close': '282.7500',
   '5. volume': '16048820'},
  '2024-09-27': {'1. open': '282.2000',
   '2. high': '284.3500',
   '3. low': '281.1400',
   '4. close': '282.0500',
   '5. volume': '10878090'},
  '2024-09-20': {'1. open': '277.1200',
   '2. high': '283.0000',
   '3. low': '276.2500',
   '4. close': '281.4600',
   '5. volume': '12543024'},
  '2024-09-13': {'1. open': '268.3900',
   '2. high': '277.6999',
   '3. low': '265.9200',
   '4. close': '277.2200',
   '5. volume': '12381485'},
  '2024-09-06': {'1. open': '276.8000',
   '2. high': '277.0000',
   '3. low': '266.0100',
   '4. close': '266.4400',
   '5. volume': '14360855'},
  '2024-08-30': {'1. open': '278.1300',
   '2. high': '278.5300',
   '3. low': '273.9195',
   '4. close': '278.3800',
   '5. volume': '10955379'},
  '2024-08-23': {'1. open': '273.6200',
   '2. high': '277.8300',
   '3. low': '273.0200',
   '4. close': '277.5900',
   '5. volume': '11521748'},
  '2024-08-16': {'1. open': '263.6300',
   '2. high': '273.5400',
   '3. low': '261.7600',
   '4. close': '273.1700',
   '5. volume': '12803490'},
  '2024-08-09': {'1. open': '251.2100',
   '2. high': '263.6400',
   '3. low': '251.0000',
   '4. close': '262.9200',
   '5. volume': '22707237'},
  '2024-08-02': {'1. open': '270.7300',
   '2. high': '274.5100',
   '3. low': '260.6900',
   '4. close': '262.9000',
   '5. volume': '16041548'},
  '2024-07-26': {'1. open': '272.7800',
   '2. high': '275.1395',
   '3. low': '265.9450',
   '4. close': '269.6900',
   '5. volume': '13803270'},
  '2024-07-19': {'1. open': '276.8000',
   '2. high': '279.2100',
   '3. low': '270.5000',
   '4. close': '271.0600',
   '5. volume': '15311649'},
  '2024-07-12': {'1. open': '272.6500',
   '2. high': '277.3570',
   '3. low': '271.9100',
   '4. close': '275.6400',
   '5. volume': '13359768'},
  '2024-07-05': {'1. open': '268.4900',
   '2. high': '272.2600',
   '3. low': '266.7300',
   '4. close': '272.1200',
   '5. volume': '13274912'},
  '2024-06-28': {'1. open': '268.3400',
   '2. high': '270.4100',
   '3. low': '266.9500',
   '4. close': '267.5100',
   '5. volume': '11637066'},
  '2024-06-21': {'1. open': '266.4100',
   '2. high': '270.1900',
   '3. low': '266.0400',
   '4. close': '268.3100',
   '5. volume': '10324415'},
  '2024-06-14': {'1. open': '262.3300',
   '2. high': '268.2150',
   '3. low': '261.8800',
   '4. close': '266.6900',
   '5. volume': '12413413'},
  '2024-06-07': {'1. open': '261.6600',
   '2. high': '264.3000',
   '3. low': '258.0772',
   '4. close': '262.9500',
   '5. volume': '15106401'},
  '2024-05-31': {'1. open': '262.4700',
   '2. high': '262.4700',
   '3. low': '256.2500',
   '4. close': '260.4400',
   '5. volume': '12695772'},
  '2024-05-24': {'1. open': '262.4300',
   '2. high': '263.9200',
   '3. low': '259.4300',
   '4. close': '261.8700',
   '5. volume': '16691309'},
  '2024-05-17': {'1. open': '259.0800',
   '2. high': '263.2800',
   '3. low': '257.5600',
   '4. close': '262.3000',
   '5. volume': '11577659'},
  '2024-05-10': {'1. open': '254.8000',
   '2. high': '259.0300',
   '3. low': '254.6200',
   '4. close': '258.0500',
   '5. volume': '11582619'},
  '2024-05-03': {'1. open': '252.7500',
   '2. high': '254.4000',
   '3. low': '247.5950',
   '4. close': '253.5300',
   '5. volume': '13028688'},
  '2024-04-26': {'1. open': '246.5900',
   '2. high': '252.5399',
   '3. low': '245.3800',
   '4. close': '251.7800',
   '5. volume': '13508258'},
  '2024-04-19': {'1. open': '255.0000',
   '2. high': '255.2050',
   '3. low': '244.5700',
   '4. close': '245.2300',
   '5. volume': '17593165'},
  '2024-04-12': {'1. open': '257.8000',
   '2. high': '258.5000',
   '3. low': '252.1600',
   '4. close': '253.0000',
   '5. volume': '16298861'},
  '2024-04-05': {'1. open': '260.3200',
   '2. high': '260.3800',
   '3. low': '254.4400',
   '4. close': '257.1800',
   '5. volume': '17020358'},
  '2024-03-28': {'1. open': '258.1000',
   '2. high': '260.5800',
   '3. low': '257.2800',
   '4. close': '259.9000',
   '5. volume': '12005259'},
  '2024-03-22': {'1. open': '255.5800',
   '2. high': '261.0700',
   '3. low': '254.1716',
   '4. close': '258.5000',
   '5. volume': '15024870'},
  '2024-03-15': {'1. open': '253.8900',
   '2. high': '256.8700',
   '3. low': '252.7000',
   '4. close': '253.7100',
   '5. volume': '16482800'},
  '2024-03-08': {'1. open': '254.7800',
   '2. high': '257.7100',
   '3. low': '250.9100',
   '4. close': '254.4300',
   '5. volume': '17217633'},
  '2024-03-01': {'1. open': '252.0200',
   '2. high': '255.0650',
   '3. low': '250.9450',
   '4. close': '254.9000',
   '5. volume': '13106943'},
  '2024-02-23': {'1. open': '247.5500',
   '2. high': '252.9200',
   '3. low': '245.1300',
   '4. close': '252.0000',
   '5. volume': '12348955'},
  '2024-02-16': {'1. open': '249.0400',
   '2. high': '250.3359',
   '3. low': '243.3500',
   '4. close': '248.4600',
   '5. volume': '17300327'},
  '2024-02-09': {'1. open': '244.8300',
   '2. high': '249.1500',
   '3. low': '242.7400',
   '4. close': '248.9000',
   '5. volume': '13234784'},
  '2024-02-02': {'1. open': '242.3400',
   '2. high': '246.0100',
   '3. low': '239.8560',
   '4. close': '245.1800',
   '5. volume': '18310186'},
  '2024-01-26': {'1. open': '240.5400',
   '2. high': '243.0200',
   '3. low': '240.0500',
   '4. close': '242.1200',
   '5. volume': '15820767'},
  '2024-01-19': {'1. open': '236.2900',
   '2. high': '239.7350',
   '3. low': '233.4300',
   '4. close': '239.5400',
   '5. volume': '14343972'},
  '2024-01-12': {'1. open': '233.2700',
   '2. high': '238.3700',
   '3. low': '233.2600',
   '4. close': '237.1100',
   '5. volume': '18453717'},
  '2024-01-05': {'1. open': '235.6500',
   '2. high': '236.5100',
   '3. low': '232.4000',
   '4. close': '233.1200',
   '5. volume': '15758387'},
  '2023-12-29': {'1. open': '236.9800',
   '2. high': '238.7399',
   '3. low': '236.4800',
   '4. close': '237.2200',
   '5. volume': '17207867'},
  '2023-12-22': {'1. open': '235.8600',
   '2. high': '238.6900',
   '3. low': '234.0600',
   '4. close': '236.6300',
   '5. volume': '20767727'},
  '2023-12-15': {'1. open': '228.6900',
   '2. high': '236.5800',
   '3. low': '228.5100',
   '4. close': '235.3100',
   '5. volume': '19835693'},
  '2023-12-08': {'1. open': '226.5800',
   '2. high': '229.0900',
   '3. low': '225.8800',
   '4. close': '228.8500',
   '5. volume': '15491828'},
  '2023-12-01': {'1. open': '225.1200',
   '2. high': '228.3300',
   '3. low': '224.4500',
   '4. close': '228.1700',
   '5. volume': '15052222'},
  '2023-11-24': {'1. open': '223.1100',
   '2. high': '225.7600',
   '3. low': '223.0000',
   '4. close': '225.3800',
   '5. volume': '9490727'},
  '2023-11-17': {'1. open': '216.8100',
   '2. high': '223.8000',
   '3. low': '216.3400',
   '4. close': '223.1100',
   '5. volume': '15582504'},
  '2023-11-10': {'1. open': '215.8300',
   '2. high': '217.6100',
   '3. low': '214.0600',
   '4. close': '217.4600',
   '5. volume': '14998268'},
  '2023-11-03': {'1. open': '204.5300',
   '2. high': '216.2000',
   '3. low': '203.7600',
   '4. close': '215.4100',
   '5. volume': '21005844'},
  '2023-10-27': {'1. open': '207.6700',
   '2. high': '210.2100',
   '3. low': '202.4400',
   '4. close': '203.1200',
   '5. volume': '20532429'},
  '2023-10-20': {'1. open': '214.7300',
   '2. high': '217.3800',
   '3. low': '208.3800',
   '4. close': '208.4700',
   '5. volume': '19014513'},
  '2023-10-13': {'1. open': '211.9100',
   '2. high': '216.9500',
   '3. low': '211.7550',

In [102]:
# STEP 3. CONVERT DATA IN JSON TO PANDAS DATAFRAME + DATA WRANGLING + COMPUTE DERIVED FIELDS + EXPORT TO A CSV FILE

# 1. Extract the 'Weekly Prices (open, high, low, close) and Volumes' portion and convert to a DataFrame
time_series_weekly_vti_df = pd.DataFrame.from_dict(
    time_series_weekly_vti['Weekly Time Series'],
    orient='index'
)

# 2. Reset index so dates become a column instead of an index
time_series_weekly_vti_df.reset_index(inplace=True)

# 3. Rename columns
time_series_weekly_vti_df.columns = [
    'date',
    'open',
    'high',
    'low',
    'close',
    'volume'
]

# 4. Convert data types
time_series_weekly_vti_df['date'] = pd.to_datetime(time_series_weekly_vti_df['date'])

numeric_columns = ['open', 'high', 'low', 'close', 'volume']

time_series_weekly_vti_df[numeric_columns] = (
    time_series_weekly_vti_df[numeric_columns].astype(float)
)

time_series_weekly_vti_df['volume'] = time_series_weekly_vti_df['volume'].astype(int)

# 5. Sort date by ascending order and resets the order of the index
# This is important for time series analysis

time_series_weekly_vti_df = time_series_weekly_vti_df.sort_values('date').reset_index(drop=True)

# 6. Compute the Derived fields

    # A. Daily Price Movement
time_series_weekly_vti_df['daily_change'] = (
    time_series_weekly_vti_df['close'] - time_series_weekly_vti_df['open']
)

    # B. Intraday Return %
time_series_weekly_vti_df['intraday_return_pct'] = (
    (time_series_weekly_vti_df['close'] - time_series_weekly_vti_df['open'])
    / time_series_weekly_vti_df['open']
) * 100

    # C. Day-over-day return
time_series_weekly_vti_df['daily_return_pct'] = (
    time_series_weekly_vti_df['close']
    .pct_change()
) * 100

    # D. Cumulative return %
    # iloc[0] refers to the initial close
time_series_weekly_vti_df["cumulative_return_pct"] = (
    (time_series_weekly_vti_df["close"] / time_series_weekly_vti_df["close"].iloc[0]) - 1
) * 100

    # E. Intraday Volatility
time_series_weekly_vti_df['intraday_volatility_abs'] = (
    time_series_weekly_vti_df['high'] - time_series_weekly_vti_df['low']
)

    # F. Volatility Ratio
time_series_weekly_vti_df['volatility_ratio'] = (
    time_series_weekly_vti_df['intraday_volatility_abs']
    / time_series_weekly_vti_df['close']
)

    # G. Intraday Volatility %
time_series_weekly_vti_df['intraday_volatility_pct'] = (
    (
        time_series_weekly_vti_df['high']
        - time_series_weekly_vti_df['low']
    )
    / time_series_weekly_vti_df['open']
) * 100

    # H. Volume Change %
time_series_weekly_vti_df['volume_change_pct'] = (
    time_series_weekly_vti_df['volume']
    .pct_change()
) * 100

    # I. 7-Day Moving Average
time_series_weekly_vti_df['moving_avg_7d'] = (
    time_series_weekly_vti_df['close']
    .rolling(7)
    .mean()
)

    # J. 30-Day Moving Average
time_series_weekly_vti_df['moving_avg_30d'] = (
    time_series_weekly_vti_df['close']
    .rolling(30)
    .mean()
)

# 7. Add Symbol and Time Zone from the Metadata

time_series_weekly_vti_df['symbol'] = time_series_weekly_vti['Meta Data']['2. Symbol']
time_series_weekly_vti_df['dt_last_refreshed'] = time_series_weekly_vti['Meta Data']['3. Last Refreshed']
time_series_weekly_vti_df['timezone'] = time_series_weekly_vti['Meta Data']['4. Time Zone']

# 8. Convert data types from string to date
time_series_weekly_vti_df['dt_last_refreshed'] = pd.to_datetime(time_series_weekly_vti_df['dt_last_refreshed'])

# 8. Round numeric columns to 2 decimal places
numeric_columns = time_series_weekly_vti_df.select_dtypes(include='number').columns

time_series_weekly_vti_df[numeric_columns] = (
    time_series_weekly_vti_df[numeric_columns]
    .round(2)
)

# 9. View the data
time_series_weekly_vti_df

,date,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,volatility_ratio,intraday_volatility_pct,volume_change_pct,moving_avg_7d,moving_avg_30d,symbol,dt_last_refreshed,timezone
0,2001-06-08,116.10,118.00,115.30,116.40,2265500,0.30,0.26,NaN,0.00,2.70,0.02,2.33,NaN,NaN,NaN,VTI,2026-05-08,US/Eastern
1,2001-06-15,116.10,116.10,110.40,111.30,853500,-4.80,-4.13,-4.38,-4.38,5.70,0.05,4.91,-62.33,NaN,NaN,VTI,2026-05-08,US/Eastern
2,2001-06-22,111.60,113.50,110.50,112.30,1478600,0.70,0.63,0.90,-3.52,3.00,0.03,2.69,73.24,NaN,NaN,VTI,2026-05-08,US/Eastern
3,2001-06-29,112.20,113.60,110.10,113.00,431700,0.80,0.71,0.62,-2.92,3.50,0.03,3.12,-70.80,NaN,NaN,VTI,2026-05-08,US/Eastern
4,2001-07-06,112.60,113.90,109.00,109.00,875700,-3.60,-3.20,-3.54,-6.36,4.90,0.04,4.35,102.85,NaN,NaN,VTI,2026-05-08,US/Eastern
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,2026-04-10,323.95,336.55,321.46,335.05,19371807,11.10,3.43,3.49,187.84,15.09,0.05,4.66,-13.78,326.94,332.71,VTI,2026-05-08,US/Eastern
1297,2026-04-17,333.94,351.74,333.64,350.53,18482054,16.59,4.97,4.62,201.14,18.11,0.05,5.42,-4.59,328.62,333.45,VTI,2026-05-08,US/Eastern
1298,2026-04-24,349.90,352.37,346.55,352.05,17522660,2.15,0.61,0.43,202.45,5.82,0.02,1.66,-5.19,331.56,334.28,VTI,2026-05-08,US/Eastern
1299,2026-05-01,352.00,357.15,348.67,355.29,15103707,3.29,0.93,0.92,205.23,8.48,0.02,2.41,-13.80,335.73,335.12,VTI,2026-05-08,US/Eastern
1300,2026-05-08,355.08,363.12,352.53,362.87,15897275,7.79,2.19,2.13,211.74,10.60,0.03,2.98,5.25,341.81,336.49,VTI,2026-05-08,US/Eastern

In [103]:
# 10. Check info
time_series_weekly_vti_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1301 entries, 0 to 1300
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     1301 non-null   datetime64[us]
 1   open                     1301 non-null   float64
 2   high                     1301 non-null   float64
 3   low                      1301 non-null   float64
 4   close                    1301 non-null   float64
 5   volume                   1301 non-null   int64
 6   daily_change             1301 non-null   float64
 7   intraday_return_pct      1301 non-null   float64
 8   daily_return_pct         1300 non-null   float64
 9   cumulative_return_pct    1301 non-null   float64
 10  intraday_volatility_abs  1301 non-null   float64
 11  volatility_ratio         1301 non-null   float64
 12  intraday_volatility_pct  1301 non-null   float64
 13  volume_change_pct        1300 non-null   float64
 14  moving_avg_7d            1295 non-null   float64
 15  moving_avg_30d           1272 non-null   float64
 16  symbol                   1301 non-null   str
 17  dt_last_refreshed        1301 non-null   datetime64[us]
 18  timezone                 1301 non-null   str
dtypes: datetime64[us](2), float64(14), int64(1), str(2)
memory usage: 193.2 KB

In [104]:
# 11. Re-order columns

time_series_weekly_vti_df = time_series_weekly_vti_df[
    [
        'date',
        'symbol',
        'timezone',
        'open',
        'high',
        'low',
        'close',
        'volume',
        'daily_change',
        'intraday_return_pct',
        'daily_return_pct',
        'cumulative_return_pct',
        'intraday_volatility_abs',
        'volatility_ratio',
        'intraday_volatility_pct',
        'volume_change_pct',
        'moving_avg_7d',
        'moving_avg_30d'
    ]
]

time_series_weekly_vti_df

,date,symbol,timezone,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,volatility_ratio,intraday_volatility_pct,volume_change_pct,moving_avg_7d,moving_avg_30d
0,2001-06-08,VTI,US/Eastern,116.10,118.00,115.30,116.40,2265500,0.30,0.26,NaN,0.00,2.70,0.02,2.33,NaN,NaN,NaN
1,2001-06-15,VTI,US/Eastern,116.10,116.10,110.40,111.30,853500,-4.80,-4.13,-4.38,-4.38,5.70,0.05,4.91,-62.33,NaN,NaN
2,2001-06-22,VTI,US/Eastern,111.60,113.50,110.50,112.30,1478600,0.70,0.63,0.90,-3.52,3.00,0.03,2.69,73.24,NaN,NaN
3,2001-06-29,VTI,US/Eastern,112.20,113.60,110.10,113.00,431700,0.80,0.71,0.62,-2.92,3.50,0.03,3.12,-70.80,NaN,NaN
4,2001-07-06,VTI,US/Eastern,112.60,113.90,109.00,109.00,875700,-3.60,-3.20,-3.54,-6.36,4.90,0.04,4.35,102.85,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,2026-04-10,VTI,US/Eastern,323.95,336.55,321.46,335.05,19371807,11.10,3.43,3.49,187.84,15.09,0.05,4.66,-13.78,326.94,332.71
1297,2026-04-17,VTI,US/Eastern,333.94,351.74,333.64,350.53,18482054,16.59,4.97,4.62,201.14,18.11,0.05,5.42,-4.59,328.62,333.45
1298,2026-04-24,VTI,US/Eastern,349.90,352.37,346.55,352.05,17522660,2.15,0.61,0.43,202.45,5.82,0.02,1.66,-5.19,331.56,334.28
1299,2026-05-01,VTI,US/Eastern,352.00,357.15,348.67,355.29,15103707,3.29,0.93,0.92,205.23,8.48,0.02,2.41,-13.80,335.73,335.12
1300,2026-05-08,VTI,US/Eastern,355.08,363.12,352.53,362.87,15897275,7.79,2.19,2.13,211.74,10.60,0.03,2.98,5.25,341.81,336.49

In [105]:
# 12. Export to CSV and save inside output folder
time_series_weekly_vti_df.to_csv(
    output_folder / "time_series_weekly_vti_df.csv",
    index=False
)

In [106]:
# 13. Merge the VXX and VTI dataframes into 1
# Advantages when doing Data Visualization in Tableau
# A combined dataset allows filtering by symbol. line comparisons, dual-axis charts, easier dashboards and cleaner storytelling

combined_market_df = pd.concat(
    [
        time_series_weekly_vti_df,
        time_series_weekly_vxx_df
    ],
    ignore_index=True
)

combined_market_df

,date,symbol,timezone,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,volatility_ratio,intraday_volatility_pct,volume_change_pct,moving_avg_7d,moving_avg_30d,dt_last_refreshed
0,2001-06-08,VTI,US/Eastern,116.10,118.00,115.30,116.40,2265500,0.30,0.26,NaN,0.00,2.70,0.02,2.33,NaN,NaN,NaN,NaT
1,2001-06-15,VTI,US/Eastern,116.10,116.10,110.40,111.30,853500,-4.80,-4.13,-4.38,-4.38,5.70,0.05,4.91,-62.33,NaN,NaN,NaT
2,2001-06-22,VTI,US/Eastern,111.60,113.50,110.50,112.30,1478600,0.70,0.63,0.90,-3.52,3.00,0.03,2.69,73.24,NaN,NaN,NaT
3,2001-06-29,VTI,US/Eastern,112.20,113.60,110.10,113.00,431700,0.80,0.71,0.62,-2.92,3.50,0.03,3.12,-70.80,NaN,NaN,NaT
4,2001-07-06,VTI,US/Eastern,112.60,113.90,109.00,109.00,875700,-3.60,-3.20,-3.54,-6.36,4.90,0.04,4.35,102.85,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2197,2026-04-10,VXX,US/Eastern,34.80,36.33,30.10,30.77,49587252,-4.03,-11.58,-11.33,-68.51,6.24,0.20,17.92,-20.55,34.36,31.76,2026-05-08
2198,2026-04-17,VXX,US/Eastern,31.16,31.30,28.37,28.98,35726903,-2.18,-7.00,-5.82,-70.34,2.93,0.10,9.40,-27.95,34.37,31.62,2026-05-08
2199,2026-04-24,VXX,US/Eastern,29.29,30.94,29.07,29.79,39941119,0.50,1.71,2.80,-69.51,1.88,0.06,6.40,11.80,33.53,31.52,2026-05-08
2200,2026-05-01,VXX,US/Eastern,29.48,29.63,27.77,28.40,29256666,-1.08,-3.66,-4.67,-70.93,1.86,0.07,6.31,-26.75,32.57,31.35,2026-05-08
2201,2026-05-08,VXX,US/Eastern,28.35,29.24,27.56,28.06,38682038,-0.29,-1.02,-1.20,-71.28,1.68,0.06,5.93,32.22,31.44,31.04,2026-05-08

In [107]:
# 14. Export to CSV and save inside output folder

combined_market_df.to_csv(
    output_folder / "combined_market_data.csv",
    index=False
)

# Part 2: Cryptocurrencies

Your stakeholders are becoming aware of the rise in cryptocurrencies, and would like to understand the recent growth of this market. Your task is to use the Alpha Vantage API to extract historical data on cryptocurrency market performance, and tell a story about their growth using visuals created in a BI tool of your choice (Tableau/Power BI).

**1. Find the correct API endpoints to retrieve historical data on cryptocurrency prices over time. Daily should be a sufficient level of granularity for your purposes.**

Use any specific cryptocurrency you wish (e.g. Bitcoin) against the US Dollar.

Use the [Documentation](https://www.alphavantage.co/documentation/) to help you.

In [68]:
# STEP 1. DEFINE URL AND PARAMETERS

# API endpoint
base_url = 'https://www.alphavantage.co/query'

# Parameters
params = {
    'function': 'DIGITAL_CURRENCY_DAILY',    # returns the daily historical time series for a cryptocurrency traded on a specific market refreshed daily at midnight (UTC)
    'symbol': 'BTC',             # the cryptocurrency
    'market': 'USD',             # the exchange market
    'datatype': 'json',          # returns the daily time series in JSON format
    'apikey': ALPHAVANTAGE_API_KEY
}

**2. Use Python to read the data as JSON**

In [69]:
# STEP 2. API REQUEST + ERROR HANDLING

# 1. Calls the API via requests and safely handles possible errors

try:
    # Send GET request to API with headers and parameters
    response = requests.get(base_url, params=params)

    # Pause briefly to avoid hitting API rate limits
    time.sleep(1)

    # Raise an error if the response status is not successful
    response.raise_for_status()

    # Parse JSON response and convert to Python dictionary
    digital_currency_daily_btc_usd = response.json()

# 2. Handles HTTP errors 
# Catches API-related errors (e.g., 401, 404, 408, 429)

except requests.exceptions.HTTPError as e:
    print("HTTP error:", response.status_code, response.text)
    digital_currency_daily_btc_usd = [] # reset to empty dataset

# 3. Handles other errors 
# Catches unexpected errors (e.g., connection issues, parsing errors)

except Exception as e:
    print("Other error:", e)
    digital_currency_daily_btc_usd = [] # reset to empty dataset

In [70]:
digital_currency_daily_btc_usd

{'Meta Data': {'1. Information': 'Daily Prices and Volumes for Digital Currency',
  '2. Digital Currency Code': 'BTC',
  '3. Digital Currency Name': 'Bitcoin',
  '4. Market Code': 'USD',
  '5. Market Name': 'United States Dollar',
  '6. Last Refreshed': '2026-05-11 00:00:00',
  '7. Time Zone': 'UTC'},
 'Time Series (Digital Currency Daily)': {'2026-05-11': {'1. open': '82199.99000000',
   '2. high': '82379.00000000',
   '3. low': '81377.20000000',
   '4. close': '81789.99000000',
   '5. volume': '252.44843487'},
  '2026-05-10': {'1. open': '80655.97000000',
   '2. high': '82450.00000000',
   '3. low': '80273.86000000',
   '4. close': '82199.99000000',
   '5. volume': '3971.08807704'},
  '2026-05-09': {'1. open': '80188.82000000',
   '2. high': '81065.32000000',
   '3. low': '80115.33000000',
   '4. close': '80655.96000000',
   '5. volume': '2056.58900174'},
  '2026-05-08': {'1. open': '80005.38000000',
   '2. high': '80487.39000000',
   '3. low': '79520.44000000',
   '4. close': '80188.82000000',
   '5. volume': '3086.74170459'},
  '2026-05-07': {'1. open': '81438.11000000',
   '2. high': '81709.17000000',
   '3. low': '79456.00000000',
   '4. close': '80005.38000000',
   '5. volume': '7038.15097074'},
  '2026-05-06': {'1. open': '80907.72000000',
   '2. high': '82814.23000000',
   '3. low': '80699.66000000',
   '4. close': '81438.10000000',
   '5. volume': '8276.53099017'},
  '2026-05-05': {'1. open': '79852.37000000',
   '2. high': '81799.60000000',
   '3. low': '79789.50000000',
   '4. close': '80907.72000000',
   '5. volume': '9129.50056534'},
  '2026-05-04': {'1. open': '78558.88000000',
   '2. high': '80750.00000000',
   '3. low': '78205.00000000',
   '4. close': '79852.37000000',
   '5. volume': '11539.41548269'},
  '2026-05-03': {'1. open': '78682.31000000',
   '2. high': '79428.60000000',
   '3. low': '78073.01000000',
   '4. close': '78558.89000000',
   '5. volume': '2766.87588315'},
  '2026-05-02': {'1. open': '78234.05000000',
   '2. high': '79155.00000000',
   '3. low': '78034.28000000',
   '4. close': '78682.31000000',
   '5. volume': '2444.21427844'},
  '2026-05-01': {'1. open': '76305.78000000',
   '2. high': '78961.14000000',
   '3. low': '76275.01000000',
   '4. close': '78234.05000000',
   '5. volume': '8786.48048854'},
  '2026-04-30': {'1. open': '75752.87000000',
   '2. high': '76655.95000000',
   '3. low': '75290.10000000',
   '4. close': '76305.78000000',
   '5. volume': '6282.45727649'},
  '2026-04-29': {'1. open': '76317.99000000',
   '2. high': '77906.84000000',
   '3. low': '74914.00000000',
   '4. close': '75752.88000000',
   '5. volume': '9665.58304734'},
  '2026-04-28': {'1. open': '77364.48000000',
   '2. high': '77478.99000000',
   '3. low': '75646.84000000',
   '4. close': '76317.99000000',
   '5. volume': '6625.83124653'},
  '2026-04-27': {'1. open': '78673.84000000',
   '2. high': '79496.00000000',
   '3. low': '76447.51000000',
   '4. close': '77364.42000000',
   '5. volume': '9288.76247228'},
  '2026-04-26': {'1. open': '77650.72000000',
   '2. high': '78943.00000000',
   '3. low': '77346.44000000',
   '4. close': '78673.83000000',
   '5. volume': '3942.05709744'},
  '2026-04-25': {'1. open': '77461.79000000',
   '2. high': '77911.09000000',
   '3. low': '77179.20000000',
   '4. close': '77650.72000000',
   '5. volume': '2871.67459101'},
  '2026-04-24': {'1. open': '78281.32000000',
   '2. high': '78607.38000000',
   '3. low': '77289.00000000',
   '4. close': '77461.80000000',
   '5. volume': '7766.77212029'},
  '2026-04-23': {'1. open': '78208.52000000',
   '2. high': '78722.96000000',
   '3. low': '76979.99000000',
   '4. close': '78281.32000000',
   '5. volume': '9366.75503457'},
  '2026-04-22': {'1. open': '76355.73000000',
   '2. high': '79523.00000000',
   '3. low': '76145.00000000',
   '4. close': '78208.52000000',
   '5. volume': '11757.91950096'},
  '2026-04-21': {'1. open': '75864.86000000',
   '2. high': '76926.37000000',
   '3. low': '74817.27000000',
   '4. close': '76348.58000000',
   '5. volume': '7556.91793671'},
  '2026-04-20': {'1. open': '73823.27000000',
   '2. high': '76600.00000000',
   '3. low': '73741.53000000',
   '4. close': '75864.86000000',
   '5. volume': '8979.33512634'},
  '2026-04-19': {'1. open': '75736.00000000',
   '2. high': '76278.36000000',
   '3. low': '73777.86000000',
   '4. close': '73823.14000000',
   '5. volume': '5477.34091341'},
  '2026-04-18': {'1. open': '77098.01000000',
   '2. high': '77450.15000000',
   '3. low': '75473.81000000',
   '4. close': '75736.82000000',
   '5. volume': '4245.34274580'},
  '2026-04-17': {'1. open': '75163.09000000',
   '2. high': '78390.00000000',
   '3. low': '74558.21000000',
   '4. close': '77098.01000000',
   '5. volume': '15414.90050977'},
  '2026-04-16': {'1. open': '74839.97000000',
   '2. high': '75539.91000000',
   '3. low': '73298.01000000',
   '4. close': '75163.09000000',
   '5. volume': '8138.95301491'},
  '2026-04-15': {'1. open': '74176.09000000',
   '2. high': '75458.81000000',
   '3. low': '73545.00000000',
   '4. close': '74836.31000000',
   '5. volume': '7732.11670824'},
  '2026-04-14': {'1. open': '74448.00000000',
   '2. high': '76127.18000000',
   '3. low': '73854.50000000',
   '4. close': '74179.04000000',
   '5. volume': '21086.20700901'},
  '2026-04-13': {'1. open': '70755.35000000',
   '2. high': '74936.90000000',
   '3. low': '70576.27000000',
   '4. close': '74446.00000000',
   '5. volume': '17452.66428951'},
  '2026-04-12': {'1. open': '73085.99000000',
   '2. high': '73172.14000000',
   '3. low': '70512.70000000',
   '4. close': '70755.35000000',
   '5. volume': '4443.04188961'},
  '2026-04-11': {'1. open': '72997.88000000',
   '2. high': '73822.95000000',
   '3. low': '72564.35000000',
   '4. close': '73086.00000000',
   '5. volume': '2795.93594516'},
  '2026-04-10': {'1. open': '71798.01000000',
   '2. high': '73477.87000000',
   '3. low': '71431.55000000',
   '4. close': '72997.88000000',
   '5. volume': '10066.64303661'},
  '2026-04-09': {'1. open': '71083.99000000',
   '2. high': '73147.81000000',
   '3. low': '70468.74000000',
   '4. close': '71798.01000000',
   '5. volume': '10707.78813462'},
  '2026-04-08': {'1. open': '71910.21000000',
   '2. high': '72861.38000000',
   '3. low': '70684.65000000',
   '4. close': '71085.99000000',
   '5. volume': '11083.24086941'},
  '2026-04-07': {'1. open': '68853.60000000',
   '2. high': '72753.97000000',
   '3. low': '67710.01000000',
   '4. close': '71910.20000000',
   '5. volume': '11156.72732306'},
  '2026-04-06': {'1. open': '69005.00000000',
   '2. high': '70378.48000000',
   '3. low': '68332.00000000',
   '4. close': '68853.61000000',
   '5. volume': '11182.35365631'},
  '2026-04-05': {'1. open': '67291.72000000',
   '2. high': '69117.60000000',
   '3. low': '66600.00000000',
   '4. close': '69005.00000000',
   '5. volume': '3810.37749315'},
  '2026-04-04': {'1. open': '66959.98000000',
   '2. high': '67535.20000000',
   '3. low': '66770.64000000',
   '4. close': '67291.73000000',
   '5. volume': '2412.86305009'},
  '2026-04-03': {'1. open': '66899.11000000',
   '2. high': '67375.70000000',
   '3. low': '66275.01000000',
   '4. close': '66959.99000000',
   '5. volume': '4181.03967015'},
  '2026-04-02': {'1. open': '68112.34000000',
   '2. high': '68652.00000000',
   '3. low': '65696.96000000',
   '4. close': '66894.48000000',
   '5. volume': '8813.97029196'},
  '2026-04-01': {'1. open': '68221.84000000',
   '2. high': '69285.99000000',
   '3. low': '67525.59000000',
   '4. close': '68112.35000000',
   '5. volume': '9804.65444480'},
  '2026-03-31': {'1. open': '66737.08000000',
   '2. high': '68518.10000000',
   '3. low': '65924.82000000',
   '4. close': '68221.85000000',
   '5. volume': '11831.58350430'},
  '2026-03-30': {'1. open': '65957.95000000',
   '2. high': '68129.33000000',
   '3. low': '65736.63000000',
   '4. close': '66737.18000000',
   '5. volume': '10707.53083699'},
  '2026-03-29': {'1. open': '66320.16000000',
   '2. high': '67076.07000000',
   '3. low': '64938.66000000',
   '4. close': '65956.94000000',
   '5. volume': '4588.31530898'},
  '2026-03-28': {'1. open': '66353.33000000',
   '2. high': '67249.65000000',
   '3. low': '65876.61000000',
   '4. close': '66320.15000000',
   '5. volume': '4011.39625322'},
  '2026-03-27': {'1. open': '68769.02000000',
   '2. high': '69128.75000000',
   '3. low': '65498.75000000',
   '4. close': '66353.34000000',
   '5. volume': '13681.42559929'},
  '2026-03-26': {'1. open': '71301.52000000',
   '2. high': '71414.33000000',
   '3. low': '68102.36000000',
   '4. close': '68769.02000000',
   '5. volume': '8225.19395173'},
  '2026-03-25': {'1. open': '70533.48000000',
   '2. high': '72030.29000000',
   '3. low': '70357.10000000',
   '4. close': '71301.53000000',
   '5. volume': '7665.36824144'},
  '2026-03-24': {'1. open': '70874.22000000',
   '2. high': '71389.00000000',
   '3. low': '68889.00000000',
   '4. close': '70533.49000000',
   '5. volume': '7238.74499869'},
  '2026-03-23': {'1. open': '67844.94000000',
   '2. high': '71811.00000000',
   '3. low': '67425.00000000',
   '4. close': '70874.23000000',
   '5. volume': '10354.71705596'},
  '2026-03-22': {'1. open': '68912.02000000',
   '2. high': '69577.00000000',
   '3. low': '67332.05000000',
   '4. close': '67844.94000000',
   '5. volume': '4889.89870785'},
  '2026-03-21': {'1. open': '70497.01000000',
   '2. high': '71075.92000000',
   '3. low': '68562.13000000',
   '4. close': '68912.02000000',
   '5. volume': '2856.70812643'},
  '2026-03-20': {'1. open': '69917.19000000',
   '2. high': '71384.62000000',
   '3. low': '69360.00000000',
   '4. close': '70497.01000000',
   '5. volume': '7315.89355875'},
  '2026-03-19': {'1. open': '71245.01000000',
   '2. high': '71628.00000000',
   '3. low': '68772.78000000',
   '4. close': '69918.30000000',
   '5. volume': '7794.02546506'},
  '2026-03-18': {'1. open': '73934.11000000',
   '2. high': '74700.00000000',
   '3. low': '70474.83000000',
   '4. close': '71245.02000000',
   '5. volume': '9248.11451050'},
  '2026-03-17': {'1. open': '74886.46000000',
   '2. high': '76022.60000000',
   '3. low': '73400.01000000',
   '4. close': '73934.11000000',
   '5. volume': '11357.85437394'},
  '2026-03-16': {'1. open': '72830.01000000',
   '2. high': '74913.69000000',
   '3. low': '72276.24000000',
   '4. close': '74886.47000000',
   '5. volume': '12657.43153702'},
  '2026-03-15': {'1. open': '71232.01000000',
   '2. high': '73220.80000000',
   '3. low': '70868.41000000',
   '4. close': '72830.01000000',
   '5. volume': '5785.61944649'},
  '2026-03-14': {'1. open': '70944.32000000',
   '2. high': '71316.00000000',
   '3. low': '70236.02000000',
   '4. close': '71232.02000000',
   '5. volume': '3174.08339322'},
  '2026-03-13': {'1. open': '70530.02000000',
   '2. high': '73968.00000000',
   '3. low': '70398.01000000',
   '4. close': '70944.33000000',
   '5. volume': '12304.21633821'},
  '2026-03-12': {'1. open': '70208.03000000',
   '2. high': '70819.84000000',
   '3. low': '69180.01000000',
   '4. close': '70531.56000000',
   '5. volume': '9708.42046678'},
  '2026-03-11': {'1. open': '69960.83000000',
   '2. high': '71358.48000000',
   '3. low': '68980.74000000',
   '4. close': '70208.00000000',
   '5. volume': '9851.72870494'},
  '2026-03-10': {'1. open': '68432.16000000',
   '2. high': '71800.00000000',
   '3. low': '68383.50000000',
   '4. close': '69960.83000000',
   '5. volume': '13322.43399947'},
  '2026-03-09': {'1. open': '65970.56000000',
   '2. high': '69543.00000000',
   '3. low': '65820.93000000',
   '4. close': '68432.17000000',
   '5. volume': '13303.95615379'},
  '2026-03-08': {'1. open': '67259.62000000',
   '2. high': '68201.16000000',
   '3. low': '65618.51000000',
   '4. close': '65970.56000000',
   '5. volume': '5505.17926548'},
  '2026-03-07': {'1. open': '68108.23000000',
   '2. high': '68544.79000000',
   '3. low': '66921.33000000',
   '4. close': '67259.62000000',
   '5. volume': '3245.05107908'},
  '2026-03-06': {'1. open': '70887.61000000',
   '2. high': '71428.40000000',
   '3. low': '67725.14000000',
   '4. close': '68108.24000000',
   '5. volume': '11045.21439575'},
  '2026-03-05': {'1. open': '72683.26000000',
   '2. high': '73588.24000000',
   '3. low': '70639.01000000',
   '4. close': '70887.60000000',
   '5. volume': '10891.71826063'},
  '2026-03-04': {'1. open': '68335.99000000',
   '2. high': '74100.00000000',
   '3. low': '67391.17000000',
   '4. close': '72683.26000000',
   '5. volume': '21142.77079177'},
  '2026-03-03': {'1. open': '68832.00000000',
   '2. high': '69255.36000000',
   '3. low': '66138.20000000',
   '4. close': '68335.99000000',
   '5. volume': '12823.72759460'},
  '2026-03-02': {'1. open': '65771.56000000',
   '2. high': '70128.74000000',
   '3. low': '65250.12000000',
   '4. close': '68832.01000000',
   '5. volume': '17772.46881037'},
  '2026-03-01': {'1. open': '66971.54000000',
   '2. high': '68200.00000000',
   '3. low': '65008.38000000',
   '4. close': '65769.00000000',
   '5. volume': '8511.88788603'},
  '2026-02-28': {'1. open': '65859.93000000',
   '2. high': '67761.55000000',
   '3. low': '63019.60000000',
   '4. close': '66967.85000000',
   '5. volume': '9093.24916408'},
  '2026-02-27': {'1. open': '67490.50000000',
   '2. high': '68223.07000000',
   '3. low': '64942.87000000',
   '4. close': '65859.94000000',
   '5. volume': '10276.79604611'},
  '2026-02-26': {'1. open': '67992.68000000',
   '2. high': '68866.86000000',
   '3. low': '66500.92000000',
   '4. close': '67490.51000000',
   '5. volume': '10678.27331982'},
  '2026-02-25': {'1. open': '64068.33000000',
   '2. high': '70020.00000000',
   '3. low': '63912.25000000',
   '4. close': '67992.68000000',
   '5. volume': '17322.54859823'},
  '2026-02-24': {'1. open': '64625.78000000',
   '2. high': '64988.32000000',
   '3. low': '62534.61000000',
   '4. close': '64068.33000000',
   '5. volume': '12517.40763597'},
  '2026-02-23': {'1. open': '67616.01000000',
   '2. high': '67656.42000000',
   '3. low': '63855.00000000',
   '4. close': '64625.78000000',
   '5. volume': '15198.01176266'},
  '2026-02-22': {'1. open': '67955.78000000',
   '2. high': '68241.40000000',
   '3. low': '67132.81000000',
   '4. close': '67617.98000000',
   '5. volume': '3263.53347230'},
  '2026-02-21': {'1. open': '67984.42000000',
   '2. high': '68683.27000000',
   '3. low': '67516.93000000',
   '4. close': '67955.78000000',
   '5. volume': '3287.06467470'},
  '2026-02-20': {'1. open': '66972.49000000',
   '2. high': '68294.86000000',
   '3. low': '66427.23000000',
   '4. close': '67984.42000000',
   '5. volume': '11349.70677085'},
  '2026-02-19': {'1. open': '66419.78000000',
   '2. high': '67288.22000000',
   '3. low': '65604.63000000',
   '4. close': '66972.50000000',
   '5. volume': '8505.29632895'},
  '2026-02-18': {'1. open': '67466.70000000',
   '2. high': '68438.84000000',
   '3. low': '65812.57000000',
   '4. close': '66419.79000000',
   '5. volume': '9687.16921753'},
  '2026-02-17': {'1. open': '68859.55000000',
   '2. high': '69199.51000000',
   '3. low': '66569.58000000',
   '4. close': '67466.70000000',
   '5. volume': '9122.62622708'},
  '2026-02-16': {'1. open': '68792.00000000',
   '2. high': '70089.99000000',
   '3. low': '67251.81000000',
   '4. close': '68858.13000000',
   '5. volume': '6626.85996745'},
  '2026-02-15': {'1. open': '69786.96000000',
   '2. high': '70941.65000000',
   '3. low': '68020.00000000',
   '4. close': '68792.00000000',
   '5. volume': '5965.51322769'},
  '2026-02-14': {'1. open': '68812.00000000',
   '2. high': '70531.53000000',
   '3. low': '68697.63000000',
   '4. close': '69786.96000000',
   '5. volume': '5586.98146780'},
  '2026-02-13': {'1. open': '66207.99000000',
   '2. high': '69434.20000000',
   '3. low': '65799.71000000',
   '4. close': '68812.00000000',
   '5. volume': '12104.28673482'},
  '2026-02-12': {'1. open': '67032.71000000',
   '2. high': '68382.90000000',
   '3. low': '65065.47000000',
   '4. close': '66208.00000000',
   '5. volume': '13823.46090185'},
  '2026-02-11': {'1. open': '68803.65000000',
   '2. high': '69248.00000000',
   '3. low': '65702.95000000',
   '4. close': '67024.93000000',
   '5. volume': '15121.43118138'},
  '2026-02-10': {'1. open': '70101.98000000',
   '2. high': '70489.99000000',
   '3. low': '67857.00000000',
   '4. close': '68803.65000000',
   '5. volume': '11566.41314985'},
  '2026-02-09': {'1. open': '70279.32000000',
   '2. high': '71380.13000000',
   '3. low': '68233.01000000',
   '4. close': '70101.99000000',
   '5. volume': '15546.49393947'},
  '2026-02-08': {'1. open': '69250.00000000',
   '2. high': '72232.17000000',
   '3. low': '68840.83000000',
   '4. close': '70279.33000000',
   '5. volume': '8090.44858999'},
  '2026-02-07': {'1. open': '70521.08000000',
   '2. high': '71648.05000000',
   '3. low': '67293.26000000',
   '4. close': '69244.74000000',
   '5. volume': '11251.84383408'},
  '2026-02-06': {'1. open': '62788.28000000',
   '2. high': '71707.18000000',
   '3. low': '60001.00000000',
   '4. close': '70527.70000000',
   '5. volume': '43810.88328386'},
  '2026-02-05': {'1. open': '72999.00000000',
   '2. high': '73173.96000000',
   '3. low': '62181.65000000',
   '4. close': '62791.00000000',
   '5. volume': '49371.20579141'},
  '2026-02-04': {'1. open': '75661.49000000',
   '2. high': '76876.54000000',
   '3. low': '71703.72000000',
   '4. close': '72998.00000000',
   '5. volume': '19764.62442772'},
  '2026-02-03': {'1. open': '78666.84000000',
   '2. high': '79123.75000000',
   '3. low': '72859.00000000',
   '4. close': '75661.49000000',
   '5. volume': '16467.12531015'},
  '2026-02-02': {'1. open': '76895.99000000',
   '2. high': '79339.00000000',
   '3. low': '74502.21000000',
   '4. close': '78666.85000000',
   '5. volume': '21193.37373311'},
  '2026-02-01': {'1. open': '78648.00000000',
   '2. high': '79337.99000000',
   '3. low': '75612.75000000',
   '4. close': '76895.53000000',
   '5. volume': '11545.98714740'},
  '2026-01-31': {'1. open': '84110.99000000',
   '2. high': '84138.00000000',
   '3. low': '75644.15000000',
   '4. close': '78648.00000000',
   '5. volume': '14855.07344290'},
  '2026-01-30': {'1. open': '84513.19000000',
   '2. high': '84599.00000000',
   '3. low': '81000.12000000',
   '4. close': '84110.99000000',
   '5. volume': '15232.81199203'},
  '2026-01-29': {'1. open': '89162.40000000',
   '2. high': '89210.16000000',
   '3. low': '83216.21000000',
   '4. close': '84513.20000000',
   '5. volume': '14860.94029344'},
  '2026-01-28': {'1. open': '89116.96000000',
   '2. high': '90476.81000000',
   '3. low': '88706.32000000',
   '4. close': '89162.40000000',
   '5. volume': '6636.13609913'},
  '2026-01-27': {'1. open': '88250.00000000',
   '2. high': '89447.21000000',
   '3. low': '87180.01000000',
   '4. close': '89116.96000000',
   '5. volume': '6475.09716863'},
  '2026-01-26': {'1. open': '86561.94000000',
   '2. high': '88787.97000000',
   '3. low': '86411.70000000',
   '4. close': '88250.01000000',
   '5. volume': '8219.90069049'},
  '2026-01-25': {'1. open': '89082.16000000',
   '2. high': '89177.95000000',
   '3. low': '86000.13000000',
   '4. close': '86561.94000000',
   '5. volume': '5428.58128865'},
  '2026-01-24': {'1. open': '89474.94000000',
   '2. high': '89832.72000000',
   '3. low': '89007.01000000',
   '4. close': '89082.17000000',
   '5. volume': '1801.82109589'},
  '2026-01-23': {'1. open': '89463.51000000',
   '2. high': '91147.01000000',
   '3. low': '88440.65000000',
   '4. close': '89474.93000000',
   '5. volume': '7381.22299218'},
  '2026-01-22': {'1. open': '89363.71000000',
   '2. high': '90273.35000000',
   '3. low': '88408.65000000',
   '4. close': '89463.50000000',
   '5. volume': '7075.16869109'},
  '2026-01-21': {'1. open': '88310.60000000',
   '2. high': '90500.00000000',
   '3. low': '87156.00000000',
   '4. close': '89363.71000000',
   '5. volume': '12539.43992250'},
  '2026-01-20': {'1. open': '92559.65000000',

**3. Identify the key which holds the data itself and export it as a csv.**

In [ ]:
# STEP 3. CONVERT DATA IN JSON TO PANDAS DATAFRAME + DATA WRANGLING + COMPUTE DERIVED FIELDS + EXPORT TO A CSV FILE

# 1. Extract the 'Time Series (Digital Currency Daily)' portion and convert to a DataFrame
digital_currency_daily_btc_usd_df = pd.DataFrame.from_dict(
    digital_currency_daily_btc_usd['Time Series (Digital Currency Daily)'],
    orient='index'
) 

# 2. Reset index so date become a column instead of an index
digital_currency_daily_btc_usd_df.reset_index(inplace=True)

# 3. Rename columns
digital_currency_daily_btc_usd_df.columns = [
    'date',
    'open',
    'high',
    'low',
    'close',
    'volume'
]

# 4. Convert data types from string to date and float
digital_currency_daily_btc_usd_df['date'] = pd.to_datetime(digital_currency_daily_btc_usd_df['date'])

numeric_columns = ['open', 'high', 'low', 'close', 'volume']

digital_currency_daily_btc_usd_df[numeric_columns] = (
    digital_currency_daily_btc_usd_df[numeric_columns].astype(float)
)

# 5. Sort date by ascending order and resets the order of the index
# This is important for time series analysis

digital_currency_daily_btc_usd_df = digital_currency_daily_btc_usd_df.sort_values('date').reset_index(drop=True)

# 6. Compute the Derived fields

    # A. Daily Price Movement
digital_currency_daily_btc_usd_df['daily_change'] = (
    digital_currency_daily_btc_usd_df['close'] - digital_currency_daily_btc_usd_df['open']
)

    # B. Intraday Return %
digital_currency_daily_btc_usd_df['intraday_return_pct'] = (
    (digital_currency_daily_btc_usd_df['close'] - digital_currency_daily_btc_usd_df['open'])
    / digital_currency_daily_btc_usd_df['open']
) * 100

    # C. Day-over-day return
digital_currency_daily_btc_usd_df['daily_return_pct'] = (
    digital_currency_daily_btc_usd_df['close']
    .pct_change()
) * 100

    # D. Cumulative return %
    # iloc[0] refers to the initial close
digital_currency_daily_btc_usd_df["cumulative_return_pct"] = (
    (digital_currency_daily_btc_usd_df["close"] / digital_currency_daily_btc_usd_df["close"].iloc[0]) - 1
) * 100

    # E. Intraday Volatility
digital_currency_daily_btc_usd_df['intraday_volatility_abs'] = (
    digital_currency_daily_btc_usd_df['high'] - digital_currency_daily_btc_usd_df['low']
)

    # F. Intraday Volatility %
digital_currency_daily_btc_usd_df['intraday_volatility_pct'] = (
    (
        digital_currency_daily_btc_usd_df['high']
        - digital_currency_daily_btc_usd_df['low']
    )
    / digital_currency_daily_btc_usd_df['open']
) * 100

    # G. 7-Day Moving Average
digital_currency_daily_btc_usd_df['moving_avg_7d'] = (
    digital_currency_daily_btc_usd_df['close']
    .rolling(7)
    .mean()
)

    # H. 30-Day Moving Average
digital_currency_daily_btc_usd_df['moving_avg_30d'] = (
    digital_currency_daily_btc_usd_df['close']
    .rolling(30)
    .mean()
)

# 7. Add Symbol and Time Zone from the Metadata

digital_currency_daily_btc_usd_df['digital_ccy_code'] = digital_currency_daily_btc_usd['Meta Data']['2. Digital Currency Code']
digital_currency_daily_btc_usd_df['market_code'] = digital_currency_daily_btc_usd['Meta Data']['4. Market Code']
digital_currency_daily_btc_usd_df['dt_last_refreshed'] = digital_currency_daily_btc_usd['Meta Data']['6. Last Refreshed']
digital_currency_daily_btc_usd_df['time_zone'] = digital_currency_daily_btc_usd['Meta Data']['7. Time Zone']

# 8. Convert data types from string to date
digital_currency_daily_btc_usd_df['dt_last_refreshed'] = pd.to_datetime(digital_currency_daily_btc_usd_df['dt_last_refreshed'])

# 9. Round numeric columns to 2 decimal places
numeric_columns = digital_currency_daily_btc_usd_df.select_dtypes(include='number').columns

digital_currency_daily_btc_usd_df[numeric_columns] = (
    digital_currency_daily_btc_usd_df[numeric_columns]
    .round(2)
)

# 9. View the data
digital_currency_daily_btc_usd_df

,date,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,intraday_volatility_pct,moving_avg_7d,moving_avg_30d,digital_ccy_code,market_code,dt_last_refreshed,time_zone
0,2010-07-17,0.05,0.05,0.05,0.05,0.00,0.00,0.00,NaN,0.0,0.00,0.00,NaN,NaN,BTC,USD,2026-05-11,UTC
1,2010-07-18,0.09,0.09,0.09,0.09,0.00,0.00,0.00,71.60,71.6,0.00,0.00,NaN,NaN,BTC,USD,2026-05-11,UTC
2,2010-07-19,0.08,0.08,0.08,0.08,0.00,0.00,0.00,-5.83,61.6,0.00,0.00,NaN,NaN,BTC,USD,2026-05-11,UTC
3,2010-07-20,0.07,0.07,0.07,0.07,0.00,0.00,0.00,-7.55,49.4,0.00,0.00,NaN,NaN,BTC,USD,2026-05-11,UTC
4,2010-07-21,0.08,0.08,0.08,0.08,0.00,0.00,0.00,6.02,58.4,0.00,0.00,NaN,NaN,BTC,USD,2026-05-11,UTC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5773,2026-05-07,81438.11,81709.17,79456.00,80005.38,7038.15,-1432.73,-1.76,-1.76,160010660.0,2253.17,2.77,79668.40,76363.84,BTC,USD,2026-05-11,UTC
5774,2026-05-08,80005.38,80487.39,79520.44,80188.82,3086.74,183.44,0.23,0.23,160377540.0,966.95,1.21,79947.66,76667.27,BTC,USD,2026-05-11,UTC
5775,2026-05-09,80188.82,81065.32,80115.33,80655.96,2056.59,467.14,0.58,0.58,161311820.0,949.99,1.18,80229.61,76962.53,BTC,USD,2026-05-11,UTC
5776,2026-05-10,80655.97,82450.00,80273.86,82199.99,3971.09,1544.02,1.91,1.91,164399880.0,2176.14,2.70,80749.76,77269.27,BTC,USD,2026-05-11,UTC
5777,2026-05-11,82199.99,82379.00,81377.20,81789.99,252.45,-410.00,-0.50,-0.50,163579880.0,1001.80,1.22,81026.57,77559.40,BTC,USD,2026-05-11,UTC

In [72]:
digital_currency_daily_btc_usd_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5778 entries, 0 to 5777
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     5778 non-null   datetime64[us]
 1   open                     5778 non-null   float64
 2   high                     5778 non-null   float64
 3   low                      5778 non-null   float64
 4   close                    5778 non-null   float64
 5   volume                   5778 non-null   float64
 6   daily_change             5778 non-null   float64
 7   intraday_return_pct      5778 non-null   float64
 8   daily_return_pct         5777 non-null   float64
 9   cumulative_return_pct    5778 non-null   float64
 10  intraday_volatility_abs  5778 non-null   float64
 11  intraday_volatility_pct  5778 non-null   float64
 12  moving_avg_7d            5772 non-null   float64
 13  moving_avg_30d           5749 non-null   float64
 14  digital_ccy_code         5778 non-null   str
 15  market_code              5778 non-null   str
 16  dt_last_refreshed        5778 non-null   datetime64[us]
 17  time_zone                5778 non-null   str
dtypes: datetime64[us](2), float64(13), str(3)
memory usage: 812.7 KB

In [73]:
# 10. Re-order columns

digital_currency_daily_btc_usd_df = digital_currency_daily_btc_usd_df[
    [
        'date',
        'digital_ccy_code',
        'market_code',
        'dt_last_refreshed',
        'time_zone',
        'open',
        'high',
        'low',
        'close',
        'volume',
        'daily_change',
        'intraday_return_pct',
        'daily_return_pct',
        'cumulative_return_pct',
        'intraday_volatility_abs',
        'intraday_volatility_pct',
        'moving_avg_7d',
        'moving_avg_30d'
    ]
]

digital_currency_daily_btc_usd_df

,date,digital_ccy_code,market_code,dt_last_refreshed,time_zone,open,high,low,close,volume,daily_change,intraday_return_pct,daily_return_pct,cumulative_return_pct,intraday_volatility_abs,intraday_volatility_pct,moving_avg_7d,moving_avg_30d
0,2010-07-17,BTC,USD,2026-05-11,UTC,0.05,0.05,0.05,0.05,0.00,0.00,0.00,NaN,0.0,0.00,0.00,NaN,NaN
1,2010-07-18,BTC,USD,2026-05-11,UTC,0.09,0.09,0.09,0.09,0.00,0.00,0.00,71.60,71.6,0.00,0.00,NaN,NaN
2,2010-07-19,BTC,USD,2026-05-11,UTC,0.08,0.08,0.08,0.08,0.00,0.00,0.00,-5.83,61.6,0.00,0.00,NaN,NaN
3,2010-07-20,BTC,USD,2026-05-11,UTC,0.07,0.07,0.07,0.07,0.00,0.00,0.00,-7.55,49.4,0.00,0.00,NaN,NaN
4,2010-07-21,BTC,USD,2026-05-11,UTC,0.08,0.08,0.08,0.08,0.00,0.00,0.00,6.02,58.4,0.00,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5773,2026-05-07,BTC,USD,2026-05-11,UTC,81438.11,81709.17,79456.00,80005.38,7038.15,-1432.73,-1.76,-1.76,160010660.0,2253.17,2.77,79668.40,76363.84
5774,2026-05-08,BTC,USD,2026-05-11,UTC,80005.38,80487.39,79520.44,80188.82,3086.74,183.44,0.23,0.23,160377540.0,966.95,1.21,79947.66,76667.27
5775,2026-05-09,BTC,USD,2026-05-11,UTC,80188.82,81065.32,80115.33,80655.96,2056.59,467.14,0.58,0.58,161311820.0,949.99,1.18,80229.61,76962.53
5776,2026-05-10,BTC,USD,2026-05-11,UTC,80655.97,82450.00,80273.86,82199.99,3971.09,1544.02,1.91,1.91,164399880.0,2176.14,2.70,80749.76,77269.27
5777,2026-05-11,BTC,USD,2026-05-11,UTC,82199.99,82379.00,81377.20,81789.99,252.45,-410.00,-0.50,-0.50,163579880.0,1001.80,1.22,81026.57,77559.40

In [74]:
# 11. Export CSV and Save inside folder
digital_currency_daily_btc_usd_df.to_csv(
    output_folder / "digital_currency_daily_btc_usd_df.csv",
    index=False
)